### ISSUE TITLE
Create `age` validator (Deprecates `minimumAge`)

### ISSUE THREAD

**Issue by Petah** [Respect/Validation#103]
This resumes the discussion happened below until @caferrari [comment][1]:

1. Create an `age` validation rule: `v::age($min, $max=null)`.
2. Deprecate (remove) `mininumAge` validation rule in favor of the `age` rule.

Original message (for historical purposes):
> There is a minimumAge but no maximumAge.
> Any reason, or just missed? 

[1]: https://github.com/Respect/Validation/issues/103#issuecomment-12889825

**Comment by henriquemoody** [comment]
This rule is going to be available in `9.0` version.
