### ISSUE TITLE
Default URL validation message template should be "a URL" not "an URL"

### ISSUE THREAD

**Issue by bc-luke** [Respect/Validation#1037]
The [default URL validation messages](https://github.com/Respect/Validation/blob/1.1/library/Exceptions/UrlException.php#L16-L23) are `"{{name}} must be an URL"` and `"{{name}} must not be an URL"`. 

Because of [how URL is pronounced](https://itknowledgeexchange.techtarget.com/writing-for-business/which-is-correct-a-url-or-an-url/), I suggest changing these to `"{{name}} must be a URL"` and `"{{name}} must not be a URL"`.

**Comment by nickl-** [comment]
hmmm ... if u ask me it's a typed message and not spoken word so therefor not pronunciation applies.

As far as I know: U is a vowel so it gets preceded by an. 

Never heard of any grammar rules based on pronunciation, this is a first.
an URL... Now it sounds funny to me too. lol. Kill the meme.

**Comment by henriquemoody** [comment]
Yeah, that was new to me too. It's been fixed in `master` (see #856). I'm still reluctant to release that in the version 1.1.19 because it may break backwards compatibility if someone is using a template with that rule.

**Comment by nickl-** [comment]
Is also breaking if someone pronounces it differently, URL - like the tea =)


- earl grey tea

**Comment by henriquemoody** [comment]
I decided to release that in version 1.1.19, please upgrade your version.

Thanks for reporting! 🐼
