### ISSUE TITLE
IntVal validates for `boolean true`

### ISSUE THREAD

**Issue by precariouspanther** [Respect/Validation#1038]
https://github.com/Respect/Validation/commit/54d17abcee9c6e734691754c77641a5f51ecc608#r29514787

Recent update to `IntVal::validate()` means passing a boolean `true` passes validation.

**Comment by precariouspanther** [comment]
Candidate fix PR: https://github.com/Respect/Validation/pull/1039

**Comment by henriquemoody** [comment]
Fixed by f5ca4a298a4475a64f0d8526041c1a58167e8c7c

Thanks for reporting and sending the fix, @precariouspanther! 🐼
