### ISSUE TITLE
how to use special validation rule？ 

### ISSUE THREAD

**Issue by cwl168** [Respect/Validation#1042]
```json
{
    "ImagesList":[
        {
            "LinkType":"1",
            "LinkValue":"s.boqii.com"
        },
        {
            "LinkType":"2",
            "LinkValue":[
                {
                    "GoodsId":"5112",
                    "Tag":"test",
                    "Sort":"1"
                },
                {
                    "GoodsId":"9104",
                    "Tag":"test",
                    "Sort":"2"
                },
                {
                    "GoodsId":"9240",
                    "Tag":"宣传测试3",
                    "Sort":"3"
                }
            ]
        }
    ]
}
```
In the json above, if LinkType equal one, then LinkValue must be a string. If LinkType equal two, then it must a array.How to use validation ? Can you help me ?

**Comment by henriquemoody** [comment]
```php
v::key(
    'ImagesList',
    v::each(
        v::when(
            v::key('LinkType', v::equals(1)),
            v::key('LinkValue', v::stringType()),
            v::key('LinkValue', v::arrayType())
        )
    )
)
->assert(json_decode($json, true);
```

First you use [Key][] because you want to validate what is inside `ImagesList`, then you use [Each][] because you want to validate each value inside `ImagesList`.

For each value inside `ImagesList` you need to apply a conditional validation, for that you will use [When][] which the condition: _if the [Key][]  `LinkType` is [Equals][] to `1`, then I validate if the [Key][]  `LinkValue` has a [StringType][], or `else` I validate if the [Key][]  `LinkValue` has an [ArrayType][]_.

I hope that helps! 

[ArrayType]: http://respect.github.io/Validation/docs/arraytype.html
[Key]: http://respect.github.io/Validation/docs/key.html
[Each]: http://respect.github.io/Validation/docs/each.html
[Equals]: http://respect.github.io/Validation/docs/equals.html
[When]: http://respect.github.io/Validation/docs/when.html
[StringType]: http://respect.github.io/Validation/docs/stringtype.html

**Comment by cwl168** [comment]
Thank you, but I still have a question, how to use with keyset? I mean there can only be "ImagesList" attribute in json, only "LinkType" attribute, only "LinkValue" attribute. If json has other Attribute, verification does not pass.

**Comment by cwl168** [comment]
Have you seen my reply? Thank you.

**Comment by henriquemoody** [comment]
I'm afraid you have to combine the validation of each item in the `ImageList` with the when. You can not do that thought "KeySet" because you only have access to the key value in the validation. It should be something like that.

```php
v::keySet(
    'ImagesList',
    v::each(
        v::create()
            ->keySet(v::key('LinkType'), v::key('LinkValue'))
            ->when(
                v::key('LinkType', v::equals(1)),
                v::key('LinkValue', v::stringType()),
                v::key('LinkValue', v::arrayType())
            )
    )
)
->assert(json_decode($json, true);
```

**Comment by cwl168** [comment]
I tested this code in phpstorm and reported the following error:

Respect\Validation\Exceptions\ComponentException : KeySet rule accepts only Key rules
 /home/vagrant/Code/api/vendor/respect/validation/library/Validator.php:231
 /home/vagrant/Code/api/vendor/respect/validation/library/Validator.php:243
 /home/vagrant/Code/api/vendor/respect/validation/library/Validator.php:217
 /home/vagrant/Code/api/tests/Api/Home/CommonTest.php:262
 
 Caused by
 Respect\Validation\Exceptions\ComponentException: KeySet rule accepts only Key rules
 
 /home/vagrant/Code/api/vendor/respect/validation/library/Rules/KeySet.php:50
 /home/vagrant/Code/api/vendor/respect/validation/library/Rules/KeySet.php:64
 /home/vagrant/Code/api/vendor/respect/validation/library/Rules/AbstractComposite.php:24
 /home/vagrant/Code/api/vendor/respect/validation/library/Factory.php:61
 /home/vagrant/Code/api/vendor/respect/validation/library/Validator.php:229
 /home/vagrant/Code/api/vendor/respect/validation/library/Validator.php:243
 /home/vagrant/Code/api/vendor/respect/validation/library/Validator.php:217
 /home/vagrant/Code/api/tests/Api/Home/CommonTest.php:262

**Comment by cwl168** [comment]
Does it support this scenario?

**Comment by henriquemoody** [comment]
Sorry, my bad. The first `KeySet` (of `ImageList`) is not correct:

```php
v::keySet(
    v::key(
        'ImagesList',
        v::each(
            v::create()
                ->keySet(
                    v::key('LinkType'),
                    v::key('LinkValue')
                )
                ->when(
                    v::key('LinkType', v::equals(1)),
                    v::key('LinkValue', v::stringType()),
                    v::key('LinkValue', v::arrayType())
                )
        )
    )
)
->assert(json_decode($json, true));
```
