### ISSUE TITLE
Way small $maxCountStringify

### ISSUE THREAD

**Issue by dvv** [Respect/Validation#1048]
I need a more verbose report of valid options in `InException` and wonder how `\Respect\Validation\Exceptions\ValidationException::$maxCountStringify` could be increased?

TIA,
--Vladimir

**Comment by nickl-** [comment]
No that is a good question that class variable is private, the same goes for `$maxDepthStringify`.

```php
private static $maxDepthStringify = 5;
private static $maxCountStringify = 10;
```

However the method where it is used considers only changing the depth not the count. 

```php
public static function stringifyArray(array $value, $depth = 1) {
}
```

Perhaps overloading this method would be the most appropriate choice for addressing your requirement... but alas it will require an API change.

**Comment by henriquemoody** [comment]
In the version 1.1, I'm afraid there is no way to do it. In the version 2.0 it will be possible to overwrite the parameter stringifier: https://github.com/Respect/Validation/blob/master/docs/feature-guide.md#message-placeholder-conversion

I hope I can release the version 2.0 very soon!

Thanks for reporting! 🐼
