### ISSUE TITLE
【question】Does "respect" support this scenario? How to deal with it ？

### ISSUE THREAD

**Issue by cwl168** [Respect/Validation#1049]
<pre>
{
    "ImagesList":[
        {
            "LinkType":"1",
            "LinkValue":"s.boqii.com"
        },
        {
            "LinkType":"2",
            "LinkValue":[
                {
                    "GoodsId":"5112",
                    "Tag":"test",
                    "Sort":"1"
                },
                {
                    "GoodsId":"9104",
                    "Tag":"test",
                    "Sort":"2"
                },
                {
                    "GoodsId":"9240",
                    "Tag":"",
                    "Sort":"3"
                }
            ]
        }
    ]
}
</pre>
In the json above, if LinkType equal one, then LinkValue must be a string. If LinkType equal two, then it must a array.There can only be "ImagesList" attribute in the json, only "LinkType" attribute and only "LinkValue" attribute in array. If the json has other Attribute, verification does not pass.

The above is my problem, How to deal with it ？

 @henriquemoody  [https://github.com/Respect/Validation/issues/1042](url) He provided a solution:
<pre>
v::keySet(
    'ImagesList',
    v::each(
        v::create()
            ->keySet(v::key('LinkType'), v::key('LinkValue'))
            ->when(
                v::key('LinkType', v::equals(1)),
                v::key('LinkValue', v::stringType()),
                v::key('LinkValue', v::arrayType())
            )
    )
)
->assert(json_decode($json, true));
</pre>
I tested this code in phpstorm and reported the following error: 

**Respect\Validation\Exceptions\ComponentException : KeySet rule accepts only Key rules**

Does it support this scenario? @henriquemoody  How should I write verification rules? Can you help me？Thank you very much.

**Comment by henriquemoody** [comment]
Sorry, it was a wrong answer see https://github.com/Respect/Validation/issues/1042#issuecomment-403276431
