### ISSUE TITLE
Requesting UUID/GUID v4 validator

### ISSUE THREAD

**Issue by alystair** [Respect/Validation#1052]
Version 4 UUIDs have the form `xxxxxxxx-xxxx-4xxx-Yxxx-xxxxxxxxxxxx` where `x` is any hexadecimal digit and `y` is one of `8`, `9`, `a`, or `b`.

Regex equiv `/^[0-9A-F]{8}-[0-9A-F]{4}-4[0-9A-F]{3}-[89AB][0-9A-F]{3}-[0-9A-F]{12}$/i`

**Comment by weeman1337** [comment]
I'll do this one. The validation will cover all uuid versions, not just version 4 :)

**Comment by henriquemoody** [comment]
This issue was fixed on #1150 and will be available in version 2.0.

I hope I can release version 2.0 very soon!

Thank you for reporting, @alystair!  And that you very much for contributing, @weeman1337! 🐼
