### ISSUE TITLE
Why phpdoc @method is defined only for static?

### ISSUE THREAD

**Issue by maur** [Respect/Validation#1058]
Right now, with phpdoc inside library/Validator.php like: 
`@method static Validator numeric()`
I have code completion working when trying Validator::
But when I expect completion further when writing next rules in chain: Validator::numeric()-> - here completion doesn't work. 
If I have to choose then I think normal calls are used more often, since static is only on first rule.

Yeah, I know I can use `Rules\AllOf(new Rules\alnum(), new Rules\Length(1,20)) `.. but v::numeric()->length(1,20) seems much easier, faster.

**Comment by henriquemoody** [comment]
Which IDE are you using, @maur?

**Comment by maur** [comment]
PhpStorm

**Comment by henriquemoody** [comment]
I tried here too, and indeed PHPStorm doesn't recognise them as non-static (which makes sense because that's how they're declared). We have to choose one or another, and I'm not sure which one would be the best.

If we choose the non-static, to have autocomplete one would have to do something like `v::create()->numeric()->length(1,20)` 🤔 

Any thoughts, @Respect/respect-validation?

**Comment by unguul** [comment]
@henriquemoody I support the instance method variant. Doing `v::create()->numeric()->length(1,20)` is *constantly cheaper*. i.e. writing `create` every time is a constant const regardless of how many validation rules you want to write while the current setup means you could potentially have to move back and forward between the docs/source code to make sure you write the method name correctly.

You'd also be more correct from a technical perspective as the methods actually belong to the instance of `Validator` and not, statically, to the class even if they can be used statically.

**Comment by henriquemoody** [comment]
finally managed to fix it on d532e942a505d5caaeb60cdddfcb9b24ebbfcde1

This will be available on version 2.1.

Thanks for reporting and everyone else for their comments! 🐼

**Comment by ccerrillo** [comment]
@henriquemoody 

This is not valid for Netbeans IDE 12, autocomplete don't work on chained methods, any thoughts?
