### ISSUE TITLE
How to set 'translator' param for every validation exception

### ISSUE THREAD

**Issue by GusAntoniassi** [Respect/Validation#1070]
Hello all.
I would like to know if there is any way to set the 'translator' param for every validations done with Respect, instead of having to do it on every exception.

Instead of using: 
```
try {
    v::alnum()->noWhitespace()->length(1, 15)->assert('really messed up screen#name');
} catch(NestedValidationException $exception) {
    $exception->setParam('translator', 'gettext');
    print_r($exception->getMessage());
}
```

Something like: 
```
try {
    v::setParam('translator', 'gettext')->alnum()->noWhitespace()->length(1, 15)->assert('really messed up screen#name');
} catch(NestedValidationException $exception) {
    print_r($exception->getMessage());
}
```

Thanks in advance.

**Comment by henriquemoody** [comment]
Hey, @GusAntoniassi! Unfortunately in the current version of Validation you cannot set a translator for every exception. That's already possible in the next version yet to be released thought.

However I would like to know a bit more about the use case you're having if that's possible. Are you validating user data and showing this message to the final users?

BTW I've checked [GusAntoniassi/respect-validation-localization](https://github.com/GusAntoniassi/respect-validation-localization), that's a lot of work!

**Comment by GusAntoniassi** [comment]
Hey @henriquemoody, sorry for the late reply.

Yes, I'm hoping to validate all exceptions through Respect in the back-end and display them to the user through an alert box or something like that. 

I'm also thinking on the possibility to parse the field name from the error message, so I would be able to show each message next to their relevant form input, but for now just the alert box will do.

Thanks for the reply! Best regards

**Comment by henriquemoody** [comment]
Hey, @meglio! `setParam()` is a method that is available since version 0.3.9.

**Comment by henriquemoody** [comment]
@GusAntoniassi, unfortunately for now it's not possible yet. In `master` that's possible already by setting a translator to the Factory, but that's also gonna change.

It's not pretty, but you could do something _like_ that:

```php
use Respect\Validation\Validatable;

final class Assertor
{
    public static function assert(Validatable $rule, $input): void
    {
        try {
            $rule->assert($input);
        } catch (NestedValidationException $exception) {
            $exception->setParam('translator', 'gettext');
            throw $exception;
        }
    }
}

Assertor::assert(v::alnum()->noWhitespace()->length(1, 15), 'really messed up screen#name');
```

I don't miss this feature too much because I usually create abstractions on top of it because I like to customise depending on my use case (not mine, but here's an example of using Validation for what you want to use https://github.com/maxmind/minfraud-api-php)

**Comment by GusAntoniassi** [comment]
Hello @henriquemoody! Next week I'll finally have some time to work on this feature again, and I'm thinking how am I going to structure it. Passing the translator in the factory would be useful for me, is this going to be changed or removed? Could you share why?

Also, I am going to try and implement a parser to build a JSON from the exceptions with the format  `"fieldname": "Error message"`. Do you think this would be a good feature to add to `master`?

Best regards!

**Comment by henriquemoody** [comment]
Sorry for the very late reply. 

I'm not changing how it is on `master`, at least not for now. I hope I can release the version 2.0 very soon, this is how it's gonna look like: https://github.com/Respect/Validation/blob/master/docs/feature-guide.md#message-localization

**Comment by henriquemoody** [comment]
I'm closing this issue for now, since the code is already implemented.

I hope I can release version 2.0 very soon!

Thanks for reporting! 🐼
