### ISSUE TITLE
Colombian postal code returns invalid format with correctly formatted postal code.

### ISSUE THREAD

**Issue by jamacon36** [Respect/Validation#1078]
Entering a valid postal code `######` with the country code set to `CO` returns an error claiming it to be an invalid format. Other postal codes validate as expected.

**Comment by henriquemoody** [comment]
Could you give us an example, @jamacon36?

**Comment by jamacon36** [comment]
Totally:
```
<?php
Use Respect\Validation\Validator as validator;
Use Respect\Validation\Exceptions\NestedValidationException;

$validator = validator::postalCode('CO')->setName('Post Code');
try {
      return $validator->assert('110231');
} catch (NestedValidationException $exception) {
      return $exception->getMessages();
      // Returns 'Post Code must be a valid postal code on "CO"'
}
```

Thanks for getting back!

**Comment by henriquemoody** [comment]
I wrote a fix for Colombian postal code but also updating the whole list of postal codes.

Please update your version of Validation to 1.1.25 to have this fixed!

Thanks for reporting! 🐼

**Comment by jamacon36** [comment]
awesome, thanks @henriquemoody !
