### ISSUE TITLE
Problem with validation

### ISSUE THREAD

**Issue by GoldraK** [Respect/Validation#1091]
Hello,
First, thanks for the help.

I'm doing an API with slim Framework and I want to use Respect/Validation, for the validations, to integrate it with slim I am using the following package

https://github.com/awurth/SlimValidation

The validation that I'm trying to do is the next, you have 8 options from 1 to 7 is defined by us and 8 activates a free write box, the back has to control if the select is sent, if it is sent between 1 and 8, if it is 8 that if the input is sent and if the input is sent that is not empty

```
v::key('use_building',v::key('use_building', v::optional(v::intVal()->between(1,8)))
                    ->when(v::key('use_building', v::equals(8)),
                        v::key('other_use_building', v::notEmpty()),
                        v::key('use_building', v::optional(v::intVal()->between(1,7)))
                    ), false)
```

As the system of the previous repositiro not only sent a parameters to validate, I made a modification so that in special cases that are indicated the whole array will be sent to be able to use the key

https://github.com/GoldraK/SlimValidation

**Comment by henriquemoody** [comment]
With so many open issues, it's become hard to really know what's really important and what I have fixed already.

I'm closing issues that are too old, and I'm not really looking at them all. If this is still relevant, please comment here and I will reopen this issue.

Thanks for reporting! 🐼
