### ISSUE TITLE
Validate two keys after formatting one

### ISSUE THREAD

**Issue by geryguilbon** [Respect/Validation#1120]
Hello,
I can't figure out how to do this .I've this array :
```php
'price' => [
  'numbers' => '53',
  'words'     => 'fifty three'
]
```
I'd like to check if the numbers value is identical to the words one by using the php class 'NumberFormatter'

Thanks for your help

**Comment by henriquemoody** [comment]
Hey, @geryguilbon! First of all you need to create custom rule) that uses `NumberFormatter`, something _like_":

```php
class NumberString extends AbstractRule
{
    public function __construct($number)
    {
        $this->number = $number;
    }

    public function validate($input)
    {
        return $input === (new NumberFormatter("en", NumberFormatter::SPELLOUT))->format($this->number);
    }
}
```

Then you can do something like `v::keyValue('words', 'numberString', 'numbers')`.

Take a look at this to know how to implement a custom rule: https://respect-validation.readthedocs.io/en/1.1/feature-guide/#custom-rules

Good luck! 🐼

**Comment by geryguilbon** [comment]
Thank you very much for your quick answer. I've finished by doing it as you
did but hoped there was a way to do it with the help of the Call or
Callback Rules.

Thanks again :)

Le mar. 18 sept. 2018 à 18:20, Henrique Moody <notifications@github.com> a
écrit :
