### ISSUE TITLE
Invalid email

### ISSUE THREAD

**Issue by julzpalomiano** [Respect/Validation#1125]
I tried to key in my email `me@domain.com.sg` and I got this error `"Email address must be valid email"`
How to validate email with extension? thanks

**Comment by raheelkhan** [comment]
`v::email()->validate('me@domain.com.sg');` works fine for me.

**Comment by henriquemoody** [comment]
I'm closing it since it seems to work fine and no further comments were added.

Feel free to open another issue if needed! 🐼
