### ISSUE TITLE
how should I replace addOr() shortcut?

### ISSUE THREAD

**Issue by martinburch** [Respect/Validation#1126]
I have some code like this, from a few years ago...

```php
foreach($this->sort as $column){
	$this->sort_validator->addOr(v::equals($column));
}
```

I can see `addOr()` was removed in #444 but I don't see any discussion on what to do instead.

**Comment by henriquemoody** [comment]
Hey, @martinburch! Depending on what is `$this->sort_validator` it can be simpler, but:

```php
$rules = [];
foreach($this->sort as $column){
    $rules[] = v::equals($column);
}
$rules[] = $this->sort_validator;

// PHP < 5.6
$this->sort_validator = call_user_func_array([$this->sort_validator, 'oneOf'], $rules);

// or  PHP >= 5.6
$this->sort_validator = v::oneOf(...$rules);
```

Hope it works for you, let me know if it works as expected!

**Comment by martinburch** [comment]
$this->sort_validator starts off as one type of validator but is extended by adding other validation rules.

```php
public static $search_validator;

function __construct() {
     $this->sort_validator = v::stringType();
}
```

**Comment by martinburch** [comment]
Thanks! This is working for me.

Just a quick note to say call_user_func_array() is still a valid php7 function, so, although the ` ...` operator works, it's not required.
