### ISSUE TITLE
Confusing message on empty string

### ISSUE THREAD

**Issue by martinburch** [Respect/Validation#1127]
The [feature guide](https://github.com/Respect/Validation/blob/1.1/docs/feature-guide.md#input-optional) mentions that now empty strings passed to validators aren't valid, unless the validator is enclosed by v::optional

The error returned for empty strings failing validation is not helpful when searching for a solution to this problem.

```
Uncaught "" must contain only letters (a-z), digits (0-9) and "_"
  thrown in /app/vendor/respect/validation/library/Rules/AbstractRule.php on line 83
```

I would instead suggest a message on empty string that is more explicit.
`Uncaught empty string ""` or `Uncaught empty string "" without use of v::optional()`

**Comment by raheelkhan** [comment]
How can I reproduce it ? I am trying on `1.1` and it is not throwing any exception when passing empty string without the `v::optional`. Thanks

**Comment by batusa** [comment]
Hi @martinburch, you can use `->setName(string)` to enhance the error message, by "labeling" your set of rules. 

If I do something like

```php
 ->setName('Field x')
```

It's gonna replace `""` for `Field x` and then I get something such as: `Uncaught Field x must contain only letters (a-z)`.

I hope it helps.

**Comment by henriquemoody** [comment]
With so many open issues, it's become hard to really know what's really important and what I have fixed already.

I'm closing issues that are too old, and I'm not really looking at them all. If this is still relevant, please comment here and I will reopen this issue.

Thanks for reporting! 🐼
