### ISSUE TITLE
underline,alnum

### ISSUE THREAD

**Issue by md51111** [Respect/Validation#1128]
don't have validation about underline

**Comment by henriquemoody** [comment]
hey, @md51111! Can you elaborate? I couldn't quite understand what did you mean by that.

**Comment by md51111** [comment]
example user_order or user_order123 
underlie validation

**Comment by henriquemoody** [comment]
The "Alnum" rule allows you to define a list of additional chars, therefor you could use:

```php
v::alnum('_')->validate('user_order123'); // true
```

Check https://respect-validation.readthedocs.io/en/1.1/rules/Alnum/ for more information.
