### ISSUE TITLE
Validator name (setName) and localization (translator)?

### ISSUE THREAD

**Issue by tmtben** [Respect/Validation#1130]
Hi all,

Is there a way to translate the validator name (I mean the value set using setName() method)?

I would like to use a dedicated translator for my field names, a translator different than the one I already use for exception messages.

For instance:
• I use gettext and a dedicated language respectvalidation.po/.mo file for Respect\Validation
• I use gettext and a messages.po/.mo file for field names and other stuff

For the moment, I overwrite the setName() method like this:

```
    public function setName($name)
    {

		if ( preg_match('/\{\{([a-zA-Z0-9]+)\}\}/i', $name, $match) ) {
			$name = str_replace('{{' . $match[1] . '}}', _($match[1]), $name);
			unset($match);
		} else {
			$name = _($name);
		}

        $this->name = $name;
        return $this;
    }
```
So I can use this kind of validator:

`'name' => v::alnum()->noWhitespace()->length(1, 10)->contains('b')->setName('<div>"{{name}}"</div>')
`

Is there a better way to get the same result?

Many thanks for your job.

Ben

**Comment by maxw3st** [comment]
$name = str_replace('{{' . $match[1] . '}}',_($match[1]), $name);
unset($match);
//* not sure why the _($match[1]), $name);
//* unset($match); part is necessary

**Comment by alganet** [comment]
I'm closing this. It's a really old issue and a use case I don't understand (the HTML tags and stuff).

@tmtben if you still need this, please reopen the issue and mention me. I might be able to help you.
