### ISSUE TITLE
Alnum validator

### ISSUE THREAD

**Issue by ghost** [Respect/Validation#114]
The Alnum validator is not respecting the additional chars param.

If I do both:

``` php
<?php
use \Respect\Validation\Validator as v;

v::alnum('#')->validate('abc 123 #'); // returns false
(new \Respect\Validation\Rules\Alnum('#'))->validate('abc 123 #'); // returns false
```

**Comment by eedithz** [comment]
Hi, can you reopen this issue? I am trying 

v::alnum("@")->validate("my@email.com")

but it return false.

**Comment by henriquemoody** [comment]
@eedithz, no need to reopen, your validation is not passing because you also have a `.` which is not an alphanumeric character.

**Comment by eedithz** [comment]
Ah, silly me.. thanks for your answer..
