### ISSUE TITLE
getFullMessage() skips root error message when only one object attribute is invalid

### ISSUE THREAD

**Issue by BelkinaDasha** [Respect/Validation#1140]
Hi! 

I've noticed some incosistent behavior: I get different full error messages in case when one object attribute validation fails and in case of 2 or more violations.
Take a look at this code and its output:
```php
<?php
use Respect\Validation\Validator as v;

class ParamObject {
    public $mustBeStringType;

    public $mustBeIntType;

    public function __construct($mustBeStringType, $mustBeIntType)
    {
        $this->mustBeStringType = $mustBeStringType;
        $this->mustBeIntType = $mustBeIntType;
    }
}

$params1 = new ParamObject(1, 2); // only `mustBeIntType` is invalid
$params2 = new ParamObject(1, '2'); // both invalid

$validator = v::create();
$validator
   ->setName('Param object')
   ->attribute('mustBeStringType', v::stringType())
   ->attribute('mustBeIntType', v::intType());

try {
   $validator->assert($params1);
} catch (\Respect\Validation\Exceptions\NestedValidationException $e) {
    print_r(PHP_EOL . '----CASE 1-----' . PHP_EOL);
    print_r($e->getFullMessage() . PHP_EOL);
}

try {
    $validator->assert($params2);
} catch (\Respect\Validation\Exceptions\NestedValidationException $e) {
    print_r(PHP_EOL . '----CASE 2-----' . PHP_EOL);
    print_r($e->getFullMessage().PHP_EOL);
}
```
Outputs:
```
----CASE 1-----
- mustBeStringType must be a string

----CASE 2-----
- All of the required rules must pass for Param object
  - mustBeStringType must be a string
  - mustBeIntType must be of the type integer
```
In case 1 the root message is being skipped.

While I expect something like that:
```
----CASE 1-----
- These rules must pass for Param object
  - mustBeStringType must be a string

----CASE 2-----
- All of the required rules must pass for Param object
  - mustBeStringType must be a string
  - mustBeIntType must be of the type integer
```
I've figured out that it happens because in the 1st case the root exception message is considered as skippable because it has no related exceptions: https://github.com/Respect/Validation/blob/83bb6e3fc9b4cd3fe50b6e37c7d27aff54fc99cf/library/Exceptions/NestedValidationException.php#L131-L133 
But I lose human understandable full error path that way. Does it happen on purpose? 

Thank you!

**Comment by henriquemoody** [comment]
With so many open issues, it's become hard to really know what's really important and what I have fixed already.

I'm closing issues that are too old, and I'm not really looking at them all. If this is still relevant, please comment here and I will reopen this issue.

Thanks for reporting! 🐼
