### ISSUE TITLE
Custom Rule - error message string from template has double quotes

### ISSUE THREAD

**Issue by nomayonnaise** [Respect/Validation#1157]
So I may be using this the wrong way, but I want my custom ValidationException to return a message in the following format

>Max tries (5) exceeded in 24 hours, try again in 5 hours, 45 minutes

but what I get is

>Max tries (5) exceeded in 24 hours, try again in "5 hours, 45 minutes"

The `self::STANDARD` template string in the custom ValidationException is
`Max tries ({{max}}) exceeded in ({{period}}), try again in {{tryAgainStringFormatted}}`

The 3 variables are set in my custom Rule as public.
`$max` and `$period` are `integers` and `$tryAgainStringFormatted` is a `string`

`$max` and `$period` are set in the `_constructor()` and `$tryAgainStringFormatted` is set inside `validate()`, using a database call (only if `$max` is exceeded in the `$period`).

I'm currently parsing the output to replace the double quotes before passing it to the client, but it's not ideal.

I've had a look through ValidationException in the library and can't figure out how these double quotes get added or if there's a variable/flag I can set to stop this happening.

Any help or guidance would be greatly appreciated!

**Comment by nomayonnaise** [comment]
I got around this by using `$name` and `{{name}}` instead of `$tryAgainStringFormatted` and `{{tryAgainStringFormatted}}`

I just can't figure out why any other string other than `{{name}}` get's put in doube quotes!

**Comment by nomayonnaise** [comment]
Figured it out!

Returns the value untouched
https://github.com/Respect/Validation/blob/48b06254c4af1a2d6c1715eb3a2bb3cb72e08bfc/library/Exceptions/ValidationException.php#L65-L67

JSON encodes the string, which adds the quotes.
https://github.com/Respect/Validation/blob/48b06254c4af1a2d6c1715eb3a2bb3cb72e08bfc/library/Exceptions/ValidationException.php#L109

I'll add my own `format()` function to my custom Exception to override this.

**Comment by henriquemoody** [comment]
In the version 1.1 there is way to do it _out of the box_. In the version 2.0 it will be possible to overwrite the parameter stringifier: https://github.com/Respect/Validation/blob/master/docs/feature-guide.md#message-placeholder-conversion. That will allow you to customize how you customize some parameters.

I hope I can release the version 2.0 very soon!

I'm glad you found a way out of it. And thanks for reporting! 🐼
