### ISSUE TITLE
PostalCode Validation broken for Canada

### ISSUE THREAD

**Issue by TheOtherBrianJ** [Respect/Validation#1161]
It appears that commit [5a067fa](https://github.com/Respect/Validation/commit/5a067faec79d0cd74aa189fc535a644fa29e0c70#r31152463) may have broken PostalCode validation for Canada by inserting an errant space into the regex.

**Comment by TheOtherBrianJ** [comment]
This issue is addressed by PR #1162

**Comment by henriquemoody** [comment]
Thanks for reporting and for cooking the PR! 🐼
