### ISSUE TITLE
Optional makes it hard to extend Validator

### ISSUE THREAD

**Issue by lode** [Respect/Validation#1168]
I'm extending the `Validator`, but that is hard when using validators like `Optional`. Then the `check()` method is called twice. See this example script:

```php
<?php

use Respect\Validation\Validator;
use Respect\Validation\Exceptions\ValidationException;

class ExtendedValidator extends Validator {
	public function check($input, $extra=null) {
		echo 'Parent check ($extra: '.var_export($extra, true).')'.PHP_EOL;
		parent::check($input);
	}
}

echo 'Required'.PHP_EOL;
try {
	ExtendedValidator::length(5)->check($input='foo', $extra='bar');
}
catch (ValidationException $e) {
	echo $e->getMessage().PHP_EOL;
}

echo PHP_EOL;
echo 'Optional'.PHP_EOL;
try {
	ExtendedValidator::optional(ExtendedValidator::length(5))->check($input='foo', $extra='bar');
}
catch (ValidationException $e) {
	echo $e->getMessage().PHP_EOL;
}
```

Giving this output:

```
Required
Parent check ($extra: 'bar')
"foo" must have a length greater than 5

Optional
Parent check ($extra: 'bar')
Parent check ($extra: NULL)
"foo" must have a length greater than 5
```

I guess this is because both the inner (`Length`) and outer (`Optional`) validators are checked.

However, this doesn't allow for much flexibility in the parent; I can't add arguments to the parent method as the second call won't have them.

Is there a way around this?

**Comment by lode** [comment]
I noticed this is also the case for the original `Validator::check()`, so it is not so much an issue of extending.

**Comment by alganet** [comment]
The `Validator` class is kind of a dead end, hard to be extended. There is a [way of creating custom rules](https://gist.github.com/augustohp/d9275aca4cf6d833888e) which is way easier.

If that doesn't work for you, might I ask what you were trying to do?

**Comment by lode** [comment]
Yeah, I know about custom rules, and use them extensively.

What I wanted to achieve is convert validation exceptions into an API output. I add extra arguments to make that possible, e.g. the name of the POST key, and a message to be shown to end-users. A simplified example:

```php
class ExtendedValidator extends Validator {
	public function check($input, $postKey=null, $humanMessage=null) {
		try {
			parent::check($input);
		}
		catch (ValidationException $e) {
			if ($postKey !== null) {
				echo json_encode(['errorFields' => [$postKey => $humanMessage]]);
			}
			else {
				echo json_encode(['errorGeneric' => ['Something went wrong']]);
			}
		}
	}
}

ExtendedValidator::length(null, 100)->check($_POST['title'], 'title', 'Please use a short descritive title');
// {"errorFields":{"title":"Please use a short descritive title"}}

ExtendedValidator::optional(ExtendedValidator::length(null, 100))->check($_POST['title'], 'title', 'Please use a short descritive title');
// {"errorGeneric":["Something went wrong"]}
```

**Comment by henriquemoody** [comment]
With so many open issues, it's become hard to really know what's really important and what I have fixed already.

I'm closing issues that are too old, and I'm not really looking at them all. If this is still relevant, please comment here and I will reopen this issue.

Thanks for reporting! 🐼
