### ISSUE TITLE
problem with when validation

### ISSUE THREAD

**Issue by Alex1401LE** [Respect/Validation#1174]
hello

i have a problem with using "when"
i use this validation:

```php
require "vendor/autoload.php";
use Respect\Validation\Validator as v;
use Respect\Validation\Exceptions\NestedValidationException;

$rules = v::keySet(
    v::key('f1', v::stringType()->notEmpty()),
    v::key('f2', v::oneOf(v::equals('add'), v::equals('edit'), v::equals('delete'))),
    v::key(
      'f3',
      v::when(
        v::key('f2', v::oneOf(v::equals('edit'), v::equals('delete'))),
        v::notEmpty()
      ),
      false
    ),
    v::key(
      'f4',
      v::when(
        v::key('f2', v::oneOf(v::equals('edit'), v::equals('delete'))),
        v::equals('test')
      ),
      false
    )
  );

```
and then check with

```php
try {
  $rules->assert(...);
} catch(NestedValidationException $exception) {
  $validation_errors = $exception->getFullMessage();
}
```

```$test_1 = ["f1" => "blabla", "f2" => "add"];```
=> is valid => is correct
```$test_2 = ["f1" => "blabla", "f2" => "edit", "f3" => 1, "f4" => "test"];```
=> is invalid, why? it´s all correct
```$test_3 = ["f1" => "blabla", "f2" => "edits", "f3" => 1, "f4" => "test"];```
=> is invalid => is correct

i do not find the problem

thanks in advance

**Comment by henriquemoody** [comment]
Hello, @Alex1401LE!

Think about the validation below:

```php
v::key(
  'f3',
  v::when(
    v::key('f2', v::oneOf(v::equals('edit'), v::equals('delete'))),
    v::notEmpty()
  ),
  false
)
```

When you use the [Key][] rule you are validating the value of a specific key, in the case above you're first validating the `f3` key which means that this validation knows nothing about the whole array.

If your validation is _when`f2` is 'edit' or 'delete', then `f3` should not be empty_ you gotta do this:

```php
v::when(
  v::key('f2', v::oneOf(v::equals('edit'), v::equals('delete'))),
  v::key('f3', v::notEmpty())
)
```

Since you probably want to keep using `keySet` to validate the structure, you could do something like this:

```php
$rules = v::keySet(
    v::key('f1', v::stringType()->notEmpty()),
    v::key('f2', v::oneOf(v::equals('add'), v::equals('edit'), v::equals('delete'))),
    v::key('f3'),
    v::key('f4')
  )->when(
    v::key('f2', v::oneOf(v::equals('edit'), v::equals('delete'))),
    v::key('f3', v::notEmpty())
  )->when(
    v::key('f2', v::oneOf(v::equals('edit'), v::equals('delete'))),
    v::key('f3', v::equals('test'))
  );
```

Also, for your use case I do recommend you to use the [In][] rule instead of the [OneOf][] rule.

```php
$rules = v::keySet(
    v::key('f1', v::stringType()->notEmpty()),
    v::key('f2', v::in('add', 'edit', 'delete')),
    v::key('f3'),
    v::key('f4')
  )->when(
    v::key('f2', v::in('edit', 'delete')),
    v::key('f3', v::notEmpty())
  )->when(
    v::key('f2', v::in('edit', 'delete')),
    v::key('f3', v::equals('test'))
  );
```

I hope it helps, and feel free to comment if it didin't!

[Key]: https://respect-validation.readthedocs.io/en/1.1/rules/Key/
[In]: https://respect-validation.readthedocs.io/en/1.1/rules/In/
[OneOf]: https://respect-validation.readthedocs.io/en/1.1/rules/OneOf/

**Comment by Alex1401LE** [comment]
hey @henriquemoody

thanks for your answer

your example unluckily don't do what i need but this was a really great point to start "playing" :)
after playing this is my result and that is what i need

```
<?php
$rules = v::keySet(
  v::key("f1", v::stringType()->notEmpty()),
  v::key("f2", v::in("add edit delete")),
  v::key("f3", v::alwaysValid(), false),
  v::key("f4", v::alwaysValid(), false)
)
->when
  (
    v::key("f2", v::equals("add") ),
    v::when(
      v::noneOf( v::key("f3"), v::key("f4") ),
      v::alwaysValid(),
      v::alwaysInvalid()
    ),
    v::when(
      v::key( "f2", v::in("edit delete") ),
      v::allOf(
        v::key("f3", v::numeric()->positive() ),
        v::key("f4", v::equals( "test" ) )
      ),
      v::alwaysInvalid()
    )
  );
?>
```

| test_array | should | result |
| --- | --- | ---- |
| ["f1" => "blabla", "f2" => "add"]|valid|valid|
| ["f1" => "blabla", "f2" => "edit", "f3" => 1, "f4" => "test"]|valid|valid|
| ["f1" => "blabla", "f2" => "edit", "f3" => 1] | invalid | invalid |
| ["f1" => "blabla", "f2" => "edit", "f3" => ""] | invalid | invalid |
| ["f1" => "blabla", "f2" => "edit", "f3" => 1, "f4" => "test", "f5" => "test"] | invalid | invalid |
| ["f1" => "blabla", "f2" => "edit"] | invalid | invalid |
| ["f1" => "blabla", "f2" => "adds"] | invalid | invalid |
| ["f1" => "blabla", "f2" => "add", "f3" => 1, "f4" => "test"] | invalid | invalid |
| [] | invalid | invalid |
| "" | invalid | invalid |

thanks again

greetings from germany
