### ISSUE TITLE
Can a template be set for an object and it's keyNested rules?

### ISSUE THREAD

**Issue by tylerssn** [Respect/Validation#1179]
I'm validating a JSON object that contains various arrays of objects. Some of these nested objects have the same property names such as "id". If one of these ID properties fails to validate I get an error such as "Property ID required". However, I do not know which object in the JSON response that this error refers to.

Is it possible to have something similar to below so that the error outputs something like "Property Product.Ingredients.id required"?

```
Validator::objectType()->setTemplate('Product.{{name}}')
    ->keyNested('ingredients' Validator::objectType()->setTemplate('Ingredients.{{name}}')
        ->keyNested('id', Validator::intType())
```

**Comment by henriquemoody** [comment]
Unfortunately not, you can only do that recursively, but not using the dots.

To be honest, I think `KeyNested` is more confusing that it helps, I prefer to use `Key` instead.

Sorry I didn't help much...

Feel free to comment on this one, or create a new issue.  🐼
