### ISSUE TITLE
How to localize validator main error message

### ISSUE THREAD

**Issue by liaolliso2012** [Respect/Validation#119]
Now we know that we can localize all the validator messages through findMessages(), is there a way to localize the main error message from getMainMessage()?

**Comment by yudina-m** [comment]
There is a 'translator' param in \Respect\Validation\Exceptions\ValidationException::getMainMessage method and this pull request https://github.com/Respect/Validation/pull/57

**Comment by alganet** [comment]
In my experience, it is better to localize the messages outside the validator chain, when retrieving exceptions:

```php
try {
    v::string()->alnum('_')->length(1,15)->assert('alganet');
} catch (\Respect\Validation\Exceptions\NestedValidationExceptionInterface $e) { 
    $messages = $e->findMessages([
        'alnum' => myTranslator('Username must contain only letters, numbers and _.'),
        'length' => myTranslator('Username must have more than 1 and less than 15 chars.')
    ]);
}
```

You can also globally change exception message templates by rule:

```php
Respect\Validation\Exceptions\Alnum::$defaultTemplates = array(
        self::MODE_DEFAULT => array(
            self::STANDARD => '{{name}} deve conter apenas letras (a-z) e dígitos (0-9)',
            self::EXTRA => '{{name}} deve conter apenas letras (a-z), dígitos (0-9) e "{{additionalChars}}"',
        ),
        self::MODE_NEGATIVE => array(
            self::STANDARD => '{{name}} não deve conter letras (a-z) ou dígitos (0-9)',
            self::EXTRA => '{{name}} não deve conter letras (a-z), dígitos (0-9) ou "{{additionalChars}}"',
        ),
    );
```

**Comment by meglio** [comment]
Should `$defaultTemplates` be added to the documentation as well?

**Comment by henriquemoody** [comment]
I think it's too much exposure to how we work internally.

Of course anyone can hack as much as they want but that can make it hard when upgrading to a new version. I'd rather keep working on a better way to handle translations in the next version than changing the documentation for the time being
