### ISSUE TITLE
PostalCode Validator not accepting Irish (IE) Postal codes in Eircode format

### ISSUE THREAD

**Issue by DanielAlt** [Respect/Validation#1200]
Had reports from my Irish users that postal codes were not being accepted.

Ireland moved over to Eircode in 2015, [i read the wikipedia page](https://en.wikipedia.org/wiki/Postal_addresses_in_the_Republic_of_Ireland#Pre-Eircode_postal_districts), and found some sample postal codes on google maps. 

They aren't being matched by the regexp [used at line 84 of PostalCode.php](https://github.com/Respect/Validation/blob/1.1/library/Rules/PostalCode.php#L84)

Check this Rubular. 
https://rubular.com/r/T90vyL1hXOkWQu

So i'm writing a PR. Just have to read your contributing document first.

**Comment by henriquemoody** [comment]
Fixed! Thank you very much for reporting and also for cooking the pull request!

As I mentioned in the pull request, the fix is available on version [1.1.30](https://github.com/Respect/Validation/releases/tag/1.1.30)
