### ISSUE TITLE
Phone validator does not allow area codes with more than 3 digits

### ISSUE THREAD

**Issue by glewe** [Respect/Validation#1202]
I ran into a shortcoming of the phone validator. Area codes with more than 3 digits are considered false.
In Europe though there are area codes like that, e.g.
+49 (6105) 1234 5678

**Comment by mazentouati** [comment]
Currently the validator assumes that the max area code is 3 digits long. Additionally, I think that the whole validator needs a refactoring as it will fail for some specific patterns too.

**Comment by maxw3st** [comment]
start with country code. Country code specifies area code and number format.

**Comment by mbretter** [comment]
same problem here (AT)

These are not valid, though they are ;)
+43 3612 nnnnnnnn
+43 3612 nnnn nnnn
when removing the spaces they are going through:
+43 3612nnnnnnnn
+433612nnnnnnnn

**Comment by henriquemoody** [comment]
Version 2.3 was released about a week ago.

This issue should be fixed now! 🐼
