### ISSUE TITLE
Different validation rules based on key value

### ISSUE THREAD

**Issue by eko3alpha** [Respect/Validation#1216]
Is there a way to create validation rules based on the value of a previous input?  I know I can manually check the $_POST key for the value and then generate new rules.  I was hoping I could chain the new rules based on a key value.

Here is an example.  If I user selects "NY" as a state,  I need to collect other information such as email and license number. 

```
### NOT THE PROPER WAY TO DO THIS ###

$rules = [
    'state'   => v::subdivisionCode('US'),
    'email'   => v::keyVal('state', 'equals' , 'NY')->allOf(v::notOptional()->email()),    
    'license' => v::keyVal('state', 'equals' , 'NY')->allOf(v::notOptional())
];
```

**Comment by mazentouati** [comment]
Hey there, If I rightfully understood your needs, you have to use this rule `when`. Here is a working example :
```PHP
$data = [
    'state' => 'NY',
    'email' => 'xyz@example.com',
    'license' => 'MIT'
];

$result = v::key('state', v::subdivisionCode('US'))
->when(v::key('state', v::equals('NY')), v::key('email', v::notOptional()->email()), v::alwaysValid())
->when(v::key('state', v::equals('NY')), v::key('license',  v::notOptional()), v::alwaysValid())
->validate($data);
```

---
Quick reference to the rule
[When Doc](https://respect-validation.readthedocs.io/en/1.1/rules/When/)

**Comment by eko3alpha** [comment]
This is perfect! Thanks!
