### ISSUE TITLE
How to add Respect Validation on child Object which is Optional

### ISSUE THREAD

**Issue by anupmca** [Respect/Validation#1229]
In Slim3 framework's Respect Validation, I am trying to add validation on child object.

```
$childObjValidationArr = array(
  'param1' => v::regex("/^[A-Za-z0-9]{1}[A-Za-z0-9.$#-@]{1,19}$/"),
  'param2' => v::date('Y-m-d'),
  'param3' => v::intVal()->not(v::negative())
);
```
It works fine if child object is not optional.

```
$mainObjectValidators = array(
  'id' => $intPositive,
  'childObj' => $childObjValidationArr
);
``` 

But not working when child is optional (null allowed).

```
$mainObjectValidators = array(
  'id' => $intPositive,
  'childObj' => v::optional($childObjValidationArr)
);
```

Any way to add optional validation for child object with Respect?
Below is the error when attempted above

> PHP Fatal error: Uncaught TypeError: Argument 1 passed to Respect\Validation\Rules\Optional::__construct() must implement interface Respect\Validation\Validatable, null given

**Comment by mazentouati** [comment]
At a glance, I feel that you're doing something wrong here because you are passing an array `$childObjValidationArr` to the native method ` v::optional`. The array you've passed is something recognized and treated by package you've used. It's unrecognized by the `v::optional` as it expects a rule not an array.

Please provide a full code including exactly which package you've used and an example for the data to validate, So we can identify which scope this issue is related to. It may be something that should be handled and answered in that specific package repository.

**Comment by wesleyvicthor** [comment]
@anupmca you could composite validators with allOf:
```php
$childValidator = v::allOf(
    v::key('param1', v::intVal()->not(v::negative())),
    v::key('param2', v::optional(v::regex("/^[A-Za-z0-9]{1}[A-Za-z0-9.$#-@]{1,19}$/")))
);
$childValidator->validate($mainObjectValidators['childObj']);

v::allOf(
    v::key('id', v::intVal()->not(v::negative()))
    v::key('childObj', v::optional(v::regex("/^[A-Za-z0-9]{1}[A-Za-z0-9.$#-@]{1,19}$/")))
)->validate($mainObjectValidators);
```
the attribute rule with the third parameter:
```php
v::attribute('childObj', v::arrayType(), false)->validate((object) $mainObjectValidators);
```
but I guess for you case the `keySet` would fit better.
```php
v::keySet(
    v::key('id', v::intVal()->not(v::negative()))
    v::key('childObj', v::arrayType(), false) // making childObj optional
)->validate($mainObjectValidators); // false
```

**Comment by anupmca** [comment]
@wesleyvicthor  Thanks for pointers. I have tried below 
`$childObjectValidator = v::when(v::notOptional(), v::attribute('pCode', $codeRegex)->attribute('dDAte', v::date('Y-m-d'))->attribute('pId', $intPositiveZeroAllowed));`

But then **KeySet** worked for me when combined it with **when**

```
$pValidator = v::keySet(
  v::key('pCode', $codeRegex),
  v::key('pDate, v::date('Y-m-d')),
  v::key('pId', $intPositiveZeroAllowed)
);

$childObjectValidator = v::when(v::notOptional(), $pValidator, v::nullType());
```
