### ISSUE TITLE
Custom rules IDE autocompletion

### ISSUE THREAD

**Issue by StarveTheEgo** [Respect/Validation#1236]
Hello!
I digged into issues list and documentation but i did not find anything about custom rules autocompletion, except some lines in #39.

How can i achieve this using PHPStorm? Maybe there is some magic?
Taking this example from documentation:
```
namespace My\Validation\Rules;

use Respect\Validation\Rules\AbstractRule;

class MyRule extends AbstractRule
{
    public function validate($input)
    {
        // Do something here with the $input and return a boolean value
    }
}
```

Can i somehow magically make it autocompletable via 
```
$validator = new Validator();
$validator::myRule();
```

Or the only way is to use addRule and pass new MyRule() there?
_Or i can also go for some stub interface hack_

**Comment by StarveTheEgo** [comment]
Currently done via stub interface hack for me

**Comment by henriquemoody** [comment]
Yeah, I guess there is nothing else to do besides that. Do you see another way to do it?

**Comment by StarveTheEgo** [comment]
Currently - no idea yet..
I am currently exploring & analyzing all the known validation libraries for our needs
From some set of libraries i selected few and Respect Validator _currently_ looks most suitable compared to any else validation library

So, since i am digging into libraries, i did not spend a lot of time with Respect Validator yet, but i am about to choose it. Thus i would like to solve some problems

Interface hack is acceptable (until someone or me will find solution), but one thing i really do not like is static magic method declaration, while documentation suggests us to use them as non-static in chaining
I am using PHPStorm and it does not like the fact i have to use static methods as non-static (related issue is #1058, but still no one answered there, sadly)

**Comment by StarveTheEgo** [comment]
Personally i would love to get rid of all the static calls in Validator class

**Comment by StarveTheEgo** [comment]
I`m not sure if i should try to rewrite things to make it more correct and make Pull Request

It will be most likely back compatibility breaking changes

**Comment by henriquemoody** [comment]
The version 1.x is closed for new features. The version 2.x (`master`) it would be fine, however it may be better to discuss a bit before spending the time on implementing the solution, IMO.

> Personally i would love to get rid of all the static methods in Validator class

I'm not sure if that would be the thing to do.

I think it's nice that validation is that it allows to create a rule while creating also a chain. Or else we would have to, for example, encourage users to always use `v::create()->ruleName()` as opposed to `v::ruleName()`. I'm just not sure about it... 

It would be great to have both static and non-static methods suggested, but I don't think that's even possible.

How are you consuming the Validation's API?

**Comment by henriquemoody** [comment]
An alternative would be that `Validator` would be a builder that only has a __callStatic. That _callStatic would create an object that would have a __call method.

There would be duplication, tho.

**Comment by StarveTheEgo** [comment]
> How are you consuming the Validation's API?
To be honest, we decided to use `$validator->addRule` approach with creating every rule's object
Internal DSL is fancy and awesome, but there is no simple way to specify _validation contexts_ (update db entry, create db entry, any else context...) for each rule, while creating rules manually provides us more freedom. Nothing personal to Internal DSL, it just did not fit our needs a bit

> An alternative would be that Validator would be a builder that only has a __callStatic. That _callStatic would create an object that would have a __call method.
> 
> There would be duplication, tho.
Yea, duplication is not fun, but having fake static method PHPDoc (while they also can be non-static) is not fun too
This is maybe dirty, but cleaner than incorrect PHPDoc comments
This is always hard when you want to make something user-friendly and at same time make it correct..
I will think about it on weekend, not sure if i will get any suitable idea tho

Can i know some approximate estimated time of 2.0 release, if possible? Just to plan integration time in our workflow

**Comment by Mishanki** [comment]
Hello!

1. **v::create()->addRuleByName(MyRule::class)** - best way for autocomplete without pre factory init.
2. Can I use custom rule with many params? Like this addRuleByName(MyRule::class)**->addArgument($userId)->addArgument($someFilterParam)**.

Thank you!

**Comment by henriquemoody** [comment]
Version 2.0 has been released long ago.

Let me know if there's anything else to be done in this ticket! 🐼
