### ISSUE TITLE
Rename Min and Max rules

### ISSUE THREAD

**Issue by StarveTheEgo** [Respect/Validation#1239]
Helloes

I believe `Min` and `Max` rules got a bit messy names
Let`s look at this example code:
```
use Respect\Validation\Validator as v;
$data = [
	'min_level' => 5,
	'max_level' => 2
];
$validator = v::key('min_level', v::intVal())
		->key('max_level', v::intVal())
		->keyValue('min_level', 'max', 'max_level');

$validator->validate($data); // false
```
So this validator checks values to be any integers, and `min_level` to be lesser than `max_level`

This line
```->keyValue('min_level', 'max', 'max_level');```
does not really look intuitively understandable

But if it would be like, for example, _lesserThan_, it would be more readable:
```->keyValue('min_level', 'lesserThan', 'max_level');```

So, my suggestion is to:
- Rename `Min` to `GreaterThan`
- Rename `Max` to `LesserThan`

_sorry if format of my issue is not correct, i am quite new to this_

**Comment by henriquemoody** [comment]
In version 1.1, Min and Max are `inclusive` by default and they can also be exclusive.

In version 2.0, They're only inclusive, and I created [GreaterThan](https://github.com/Respect/Validation/blob/master/docs/rules/GreaterThan.md) and [LessThan](https://github.com/Respect/Validation/blob/master/docs/rules/LessThan.md).

Following your logic what should happen is:
- Rename Min to GreaterThanOrEquals
- Rename Max to LessThanOrEquals

However, even though they're more explicit, they are quite verbose and they seem like a combination of two rules, like: `v::anyOf(v::greaterThan(), v::equals())`

**Comment by StarveTheEgo** [comment]
Following my logic, `lesserThan` and `greaterThan` would extend AbstractInterval, which has constructor:
```public function __construct($interval, $inclusive = true)```

And i believe it would be enough for all use cases

_I was not aware of version 2.0 by the way_

**Comment by henriquemoody** [comment]
I don't think `GreaterThan` or `LessThan` would make sense with an `$inclusive` argument. In fact, I create them to have a more clear intent. 

If I have a GreaterThan that may be inclusive, then it's not _greater than_ but _greater than or equals to_, same goes for LessThan.

And, BTW, `AbstractInterval` will no longer exist.

I hope I can release version 2.0 very soon. There are just a few things that I wanna do before, but it should be close

**Comment by StarveTheEgo** [comment]
Okay
Thank you guys for this project anyway :)
I am integrating it anyway, because other libraries suck
