### ISSUE TITLE
Empty input partially invalid

### ISSUE THREAD

**Issue by mf** [Respect/Validation#124]
Guys,

I am probably losing my mind, but according to all my tests ->validate() WILL fail on all empty input (all rules), but assert passes fine. (Obviously not using notEmpty)

Am I missing something? For example tests for phone validator pass for empty input (refer to tests)
Unless of course the validation rules automatically disallow empty input since they validate certain criteria like length, in which case I think we should update the docs since they state that empty input should be passed through **unless** a NotEmpty validator is applied.

Here are some details:

Validators:

        $nameValidator      = Validation\Validator::create()->string()->length(5,100);
        $phoneValidator     = Validation\Validator::create()->string()->phone();
        $voteValidator      = Validation\Validator::create()->numeric()->between(1,20,true);
        $ageValidator       = Validation\Validator::create()->numeric()->between(1,120, true);
        $genderValidator    = Validation\Validator::create()->numeric()->between(1,2, true);
        $countryValidator   = Validation\Validator::create()->numeric()->between(1,200, true);

$age = ''; // All other inputs are empty as well
$phone = ''; // etc...

Trying assert **does not** generate an exception

        try {
            $phoneValidator->assert($phone);
        } catch (Exception $e) {
             echo $e->getFullMessages();
        }

Trying to validate **fails**

    if (!$phoneValidator->validate($phone)) {
        echo 'error';
    }

Adding *var_dump($v);* on line 38 in AllOf.php rule generates:
As you can see for some reason NotEmpty is being applied?

object(Respect\Validation\Rules\NotEmpty)#14 (2) {
  ["name":protected]=>
  NULL
  ["template":protected]=>
  NULL
}
object(Respect\Validation\Rules\NotEmpty)#22 (2) {
  ["name":protected]=>
  NULL
  ["template":protected]=>
  NULL
}
object(Respect\Validation\Rules\Numeric)#30 (2) {
  ["name":protected]=>
  NULL
  ["template":protected]=>
  NULL
}
object(Respect\Validation\Rules\Numeric)#35 (2) {
  ["name":protected]=>
  NULL
  ["template":protected]=>
  NULL
}
object(Respect\Validation\Rules\Numeric)#40 (2) {
  ["name":protected]=>
  NULL
  ["template":protected]=>
  NULL
}

**Comment by henriquemoody** [comment]
Will be fixed on version 1.0, see [changelog](https://github.com/Respect/Validation/blob/311891b/CHANGELOG.md#100---2015-10-24) for more info about the version.

To fix this issue now all rules are mandatory, but you can use [optional()](https://github.com/Respect/Validation/blob/311891b/docs/Optional.md) rule to handle optional values, which now is `null` and an empty string by default.
