### ISSUE TITLE
Respect\Validation\Exceptions\ComponentException: "with" is not a valid rule name

### ISSUE THREAD

**Issue by akorz** [Respect/Validation#1240]
Hello, 

Today I updated Respect/Validation up to master version and got error:

Respect\Validation\Exceptions\ComponentException: "with" is not a valid rule name

/app/backend/vendor/respect/validation/library/Factory.php:144
/app/backend/vendor/respect/validation/library/Validator.php:220
/app/backend/vendor/respect/validation/library/Validator.php:208
/app/backend/src/Domain/Genus/DTO/UpsertGenusCommandDTO.php:35

My code is below. Can you suggest me how to rewrite my code. I'm asking because in docs I can still find example with v:with.

Thanks.

```class UpsertCountryCommandDTO extends DTO
{
    /**
     * @var string
     */
    public $id;

    /**
     * @var array
     */
    public $name;

    /**
     * @var string
     */
    public $isoCode;

    /**
     * @var string
     */
    public $phoneCode;

    /**
     * @var string
     */
    public $timezone;

    /**
     * @var string
     */
    public $controlKey;

    /**
     * @return array
     */
    public function rules(): array
    {
        v::with('App\\Domain\\Country\\Validator\\CountryName');
        v::with('App\\Domain\\Country\\Validator\\CountryTimezone');
        v::with('App\\Domain\\Country\\Validator\\CountryIsoCode');
        v::with('App\\Domain\\Country\\Validator\\CountryPhoneCode');

        return [
            'name.en' => v::CountryName($this->container, 'en', $this->id)->setName('name'),
            'name.es' => v::optional(v::CountryName($this->container, 'es', $this->id))->setName('name'),
            'name.ru' => v::optional(v::CountryName($this->container, 'ru', $this->id))->setName('name'),
            'isoCode' => v::CountryIsoCode($this->container, $this->id)->setName('isoCode'),
            'phoneCode' => v::CountryPhoneCode($this->container, $this->id)->setName('phoneCode'),
            'timezone' => v::optional(v::CountryTimezone($this->container, $this->isoCode))->setName('timezone'),
        ];
    }
}
```

**Comment by henriquemoody** [comment]
Hey, @akorz! 

I would suggest you to not use the master version for now because the API will still change. At this  very moment you could do the same following this: https://github.com/Respect/Validation/blob/master/docs/feature-guide.md#custom-rules

In your case it would be:

```php
Factory::setDefaultInstance(
    (new Factory())->withRuleNamespace('App\\Domain\\Country\\Validator')
);
```

**Comment by akorz** [comment]
Thank you. I'll try :)

**Comment by henriquemoody** [comment]
Feel free to comment here if needed

**Comment by akorz** [comment]
@henriquemoody Previously there was 

`v::with('App\\Domain\\Shared\\Validator\\Email', true);`

how to do the same now for
`v::Email($this->container)->setName('email') ?

**Comment by akorz** [comment]
One more strange thing:

I have 
```
class UserPassword extends OneOf
{
    /**
     * UserPassword constructor.
     *
     * @param ContainerInterface $container
     * @param string|null        $id
     */
    public function __construct(ContainerInterface $container, string $id = null)
    {
        parent::__construct(
            $container,
            new UserPasswordField($container),
            new UserIdExists($container, $id)
        );
    }
}

```
I guess I have register my custom validation again there?

And I get error: 
Fatal error: Class App\Domain\Shared\Validator\OneOf contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (Respect\Validation\Validatable::getName, Respect\Validation\Validatable::reportError, Respect\Validation\Validatable::setTemplate

What code have I write there then?

```
class OneOf implements Validatable
{
    use Translator;

    const NAME_REGEX = '/[А-Яа-яa-zA-ZáéíñóúüÁÉÍÑÓÚÜ\s]/';

    protected $oneOf;

    public function __construct()
    {
        $this->oneOf = new \Respect\Validation\Rules\OneOf();

        $args = func_get_args();

        if (isset($args[0]) && $args[0] instanceof ContainerInterface) {
            $this->container = $args[0];
            array_shift($args);
        }

        parent::__construct(...$args);
    }

    public function assert($input): void
    {
        $this->oneOf->assert($input);
    }

    public function validate($input): bool
    {
        return $this->oneOf->validate($input);
    }

    public function check($input): void
    {
        $this->oneOf->check($input);
    }
}
```

**Comment by henriquemoody** [comment]
> How to do the same now for `v::Email($this->container)->setName('email')` ?

In `master` you cannot overwrite rules from Validation, that's because it causes confusion on the behaviour of the rules, so you have to call them a different name.


As for your code, it could be:

```php
class UserPassword extends extends AbstractEnvelope
{
    public function __construct(ContainerInterface $container, ?string $id = null)
    {
        parent::__construct(
            new AnyOf(
                $container,
                new UserPasswordField($container),
                new UserIdExists($container, $id)
            )
        );
    }
}
```

Also, check this out:

- https://github.com/Respect/Validation/blob/master/docs/rules/OneOf.md#changelog
- https://github.com/Respect/Validation/blob/master/docs/rules/AnyOf.md

**Comment by akorz** [comment]
@henriquemoody ok. thank you. I'll try again :)

**Comment by akorz** [comment]
@henriquemoody 

the same :(

TypeError: Argument 1 passed to Respect\Validation\Rules\AbstractWrapper::__construct() must implement interface Respect\Validation\Validatable

**Comment by henriquemoody** [comment]
Ops:

```
class UserPassword extends extends AbstractWrapper
{
    public function __construct(ContainerInterface $container, ?string $id = null)
    {
        parent::__construct(
            new AnyOf(
                new UserPasswordField($container),
                new UserIdExists($container, $id)
            )
        );
    }
}
```

**Comment by akorz** [comment]
@henriquemoody  there will be the same error

**Comment by akorz** [comment]
@henriquemoody so, I guess its impossible to do now?

**Comment by henriquemoody** [comment]
Hey, @akorz! I'm sorry for my late reply.

It's hard to understand what's going on with your code because it I just know a bit of it, so it's hard to understand what's going on.

The constructor of `AbstractWrapper` accepts only one instance of a `Validatable`. And `AnyOf` accepts multiple instances of `Validatable`. Somehow you're passing a `TestContainer` to the constructor of `AbstractWrapper`.

Are you sure you're using `Respect\Validation\Rules\AnyOf`?

**Comment by akorz** [comment]
@henriquemoody  Well, UserPassword was a custom validation rule, where as you can see the chain of rules were included. Now I simple can not use it, because BC is broken. If I use AstractWrapper, I can not use my constructor  public function __construct(ContainerInterface $container, ?string $id = null)

I have more then 200 custom validators in my code and I have not idea how to migrate later on next version of Respect/Validation

**Comment by henriquemoody** [comment]
I still cannot understand the problem.

Your error message says that you're passing `Symfony\Bundle\FrameworkBundle\Test\TestContainer` to `AstractWrapper` and that really doesn't make sense as this library doesn't do anything with `TestContainer`.

See some examples of rules that do something similar:

* https://github.com/Respect/Validation/blob/master/library/Rules/Between.php
* https://github.com/Respect/Validation/blob/master/library/Rules/KeySet.php
* https://github.com/Respect/Validation/blob/master/library/Rules/FilterVar.php


Could you confirm if `UserPassword` is exactly like that?


```php
class UserPassword extends extends AbstractWrapper
{
    public function __construct(ContainerInterface $container, ?string $id = null)
    {
        parent::__construct(
            new AnyOf(
                new UserPasswordField($container),
                new UserIdExists($container, $id)
            )
        );
    }
}
```

And could you confirm that `AnyOf` is `Respect\Validation\Rules\AnyOf`?

**Comment by akorz** [comment]
@henriquemoody thank for reply

> Could you confirm if `UserPassword` is exactly like that?

No, because constructor of UserPassword is not compatible with constructor of AbstractWrapper.

I found something similar in your code just for https://github.com/Respect/Validation/blob/master/library/Rules/FilterVar.php with AbstractEnvelope, but I have test it :)

**Comment by henriquemoody** [comment]
If you could sent the code from `UserPassword` perhaps I could help you a bit better. `AbstractEnvelope` and `AbstractWrapper` are pretty much the same, it would be a surprise if it would work because you changed only that.

**Comment by akorz** [comment]
@henriquemoody  All right, I'll send some code on your email
