### ISSUE TITLE
 how to accurately verify in different countries？

### ISSUE THREAD

**Issue by titlebaby** [Respect/Validation#1242]
I have doubts. Please help me.
How to use it accurately in different countries? For example, how to accurately verify the mobile phone number in China? v::phone() or v::phone()->regex($match)？

**Comment by mazentouati** [comment]
The `phone` rule has no way to select the country. It verifies if the provided input is a valid phone number regardless of the country. The `regex` rule in the other hand lets you use a regex pattern to test against, which is more suitable in your case by adding the pattern that limit which countries you would like to support.
For example :
```PHP
// This will ensure that the number is belonging to my country as it's the most pattern I'm sure about
v::phone()->regex('/(\+216)?(2|9|3|4|5)[0-9]{7}/')->validate(input);
// you may need to stripe the special characters ( like spaces or dashed ) before validating it to simplify the RegEx pattern
```
The pattern is pretty challenging though, as for many countries there's a more complicated rules on how a number is formatted.

I would like to mention that using the `AllOf` rule is more convenient as it will unify the error and make it easier to craft the error's message.
```PHP
v::allOf(
    v::phone(),
    v::regex()
)->validate(input);
```

**Comment by henriquemoody** [comment]
I'm closing this one because version 2.3 has been released, and we hope that has fixed the issue. Let us know if that's not the case so we can reopen the issue.
