### ISSUE TITLE
Security scanner found 18 suspicious code warnings

### ISSUE THREAD

**Issue by joshtillman** [Respect/Validation#1263]
My security scanner is giving me 18 suspicious code warnings from your code:

1. File Location: /wp-content/plugins/tainacan/vendor/respect/validation/library/Rules/AbstractComposite.php

Found 1 issues.

The function eval called at line 116 column 24, which should be avoided whenever possible.

2. File Location: /wp-content/plugins/tainacan/vendor/respect/validation/library/Rules/AbstractRelated.php

Found 1 issues.

The function eval called at line 57 column 21, which should be avoided whenever possible.

3. File Location: /wp-content/plugins/tainacan/vendor/respect/validation/library/Rules/AbstractRule.php

Found 2 issues.

The function eval called at line 27 column 21, which should be avoided whenever possible.

The function eval called at line 37 column 23, which should be avoided whenever possible.

4. File Location: /wp-content/plugins/tainacan/vendor/respect/validation/library/Rules/AbstractWrapper.php

Found 2 issues.

The function eval called at line 30 column 21, which should be avoided whenever possible.

The function eval called at line 32 column 41, which should be avoided whenever possible.

5. File Location: /wp-content/plugins/tainacan/vendor/respect/validation/library/Rules/AllOf.php

Found 1 issues.

The function eval called at line 16 column 21, which should be avoided whenever possible.

6. File Location: /wp-content/plugins/tainacan/vendor/respect/validation/library/Rules/Domain.php

Found 2 issues.

The function eval called at line 80 column 21, which should be avoided whenever possible.

The function eval called at line 105 column 25, which should be avoided whenever possible.

7. File Location: /wp-content/plugins/tainacan/vendor/respect/validation/library/Rules/Each.php

Found 3 issues.

The function eval called at line 28 column 21, which should be avoided whenever possible.

The function eval called at line 39 column 43, which should be avoided whenever possible.

The function eval called at line 47 column 42, which should be avoided whenever possible.

8. File Location: /wp-content/plugins/tainacan/vendor/respect/validation/library/Rules/Iterable.php

Found 1 issues.

The function eval called at line 13 column 5, which should be avoided whenever possible.

9. File Location: /wp-content/plugins/tainacan/vendor/respect/validation/library/Rules/KeySet.php

Found 2 issues.

The function eval called at line 121 column 21, which should be avoided whenever possible.

The function eval called at line 125 column 24, which should be avoided whenever possible.

10. File Location: /wp-content/plugins/tainacan/vendor/respect/validation/library/Rules/KeyValue.php

Found 2 issues.

The function eval called at line 67 column 21, which should be avoided whenever possible.

The function eval called at line 72 column 20, which should be avoided whenever possible.

11. File Location: /wp-content/plugins/tainacan/vendor/respect/validation/library/Rules/NoneOf.php

Found 1 issues.

The function eval called at line 16 column 21, which should be avoided whenever possible.

12. File Location: /wp-content/plugins/tainacan/vendor/respect/validation/library/Rules/Not.php

Found 1 issues.

The function eval called at line 38 column 21, which should be avoided whenever possible.

13. File Location: /wp-content/plugins/tainacan/vendor/respect/validation/library/Rules/OneOf.php

Found 1 issues.

The function eval called at line 18 column 21, which should be avoided whenever possible.

14. File Location: /wp-content/plugins/tainacan/vendor/respect/validation/library/Rules/Optional.php

Found 2 issues.

The function eval called at line 28 column 21, which should be avoided whenever possible.

The function eval called at line 34 column 24, which should be avoided whenever possible.

15. File Location: /wp-content/plugins/tainacan/vendor/respect/validation/library/Rules/Sf.php

Found 1 issues.

The function eval called at line 56 column 21, which should be avoided whenever possible.

16. File Location: /wp-content/plugins/tainacan/vendor/respect/validation/library/Rules/When.php

Found 3 issues.

The function eval called at line 44 column 21, which should be avoided whenever possible.

The function eval called at line 47 column 33, which should be avoided whenever possible.

The function eval called at line 50 column 29, which should be avoided whenever possible.

17. File Location: /wp-content/plugins/tainacan/vendor/respect/validation/library/Rules/Zend.php

Found 1 issues.

The function eval called at line 47 column 21, which should be avoided whenever possible.

18. File Location: /wp-content/plugins/tainacan/vendor/respect/validation/library/Validatable.php

Found 1 issues.

The function eval called at line 17 column 21, which should be avoided whenever possible.

**Comment by CameronHall** [comment]
Hey @joshtillman,

I recommend you upgrade the plugin to have the latest revision of Respect/Validation if you haven't already. If you look at the files you've listed and compare them with the repository under version 1.1.31 you'll find no mention of `eval()`. In fact, this project doesn't contain a single `eval()` at all.

Should you update the `tainacan` plugin and still have issues I recommend you double check the files on your filesystem, should those files look okay and your "security scanner" is still playing up it's time to consider an alternative.

**Comment by alystair** [comment]
@henriquemoody +1 to close, seems like a 'PEBKAC' error to me :)

**Comment by henriquemoody** [comment]
Yeah, as @CameronHall stated, there is not a single `eval()` in the codebase.

Let us know if there is something we're missing here, @joshtillman!
