### ISSUE TITLE
The Date Validator Allows some invalid dates.

### ISSUE THREAD

**Issue by DanielAlt** [Respect/Validation#1267]
**Summary**
the Date validator appears to allow invalid dates where 0 appears as the month number or day number. eg. "1994-01-00", "1994-0-0"

**Steps to Reproduce** 
![image](https://user-images.githubusercontent.com/4618791/70752630-02f4ec80-1d01-11ea-8724-d4a348e9e10f.png)

**Result**
The script returns True 

**Expected Result** 
The script returns False. 

**Notes:**
I'll begin working on a PR. I'll reread  your contribution documentation and get back to you. Probably try and submit something before the end of this weekend.

**Comment by DanielAlt** [comment]
After some review. 

\respect\validation\library\Rules\Date.php

```  php
if (is_null($this->format)) {
    return false !== strtotime($inputString);
}
```
date() is essentially wrapping strtotime when no format is provided. So date() validator accepts a huge range of inputs (https://www.php.net/manual/en/function.strtotime.php)

Eg.  [This also Returns True] 

```
use Respect\Validation\Validator;
$validator = Validator::date()->setName("Date");
var_dump($validator->validate("next Thursday"));
```

According to the documentation this is not expected behaviour. 
https://github.com/Respect/Validation/blob/master/docs/rules/Date.md It says it defaults to "Y-m-d"

I don't know what should be updated, the code, or the docs. 

Please advise.

**Comment by alganet** [comment]
I'm assuming you're using version `1.1`. If so, it still supports `strtotime()` input:

https://github.com/Respect/Validation/blob/1.1/docs/rules/Date.md

The document you linked points to master, which is unreleased and unstable.

I strongly recommend using a format always. Results on 1.1:

```php
php > var_dump(\Respect\Validation\Validator::date('Y-m-d')->validate('1994-00-0'));
bool(false)
php > var_dump(\Respect\Validation\Validator::date('Y-m-d')->validate('1994-00-00'));
bool(false)
```

I like the idea of making the docs more explicit. At the same time, defaulting to the strtotime behavior seems dangerous. Maybe it should be a completely separate `RelativeDateString` or something like that.

Thanks for the time investigating and reporting! 🐼 Do you have any additional suggestions on how we could improve this?

**Comment by DanielAlt** [comment]
Sorry for the Version Mismatches.

You're right, documentation in 1.1 describes the strtotime behaviour. And the behaviour is removed for the Master branch, and the documentation is updated. So this issue is invalid; or already taken care of in an unreleased version. 

>  defaulting to the strtotime behavior seems dangerous.

Aggreed. strtotime does not actually validate that a given input is a date. ```strtotime("Next Thursday")``` **returns** a valid date -- But the string "Next Thursday" is not itself a valid date. 

I would not modify that behaviour: the documentation for that release describes exactly that .

so **Looks like you guys have it covered ! :)** 

Thanks for your quick response.  
I'll go add the format string to my date validators :)
