### ISSUE TITLE
Less strenuous install procedure?

### ISSUE THREAD

**Issue by Flyarbonkers** [Respect/Validation#127]
I would love to use Respect/Validation. All the usage examples make it look spectacular and very intuitive.

But the install seems DESIGNED to exclude adoption. I'm hoping that's just my ignorance; I have to support LOTS of stuff in our little operation, and PHP is just one of the things I have to cope with in a "I know just enough to squeak by" basis. So some of the latest sophisticated PHP refinements are still on my TODO list to learn.

Am I right in understanding the following with respect to Respect/Validation:
1. You can't just unzip and copy the package to your server. You HAVE to use PEAR or Composer whether you like it or not.
2. Given the fact that we use shared hosting on GoDaddy, not wanting to devote our lives to the care and feeding of a web server of our very own, using Composer or PEAR pretty much REQUIRES permissions and PHP command liine access that MANY providers won't give people like us, ensuring we CAN'T use the install mechanisms Respect/Validation REQUIRES us to use.
3. One has to understand, gen up and use a roll-your-own autoloader or understand THAT whole thing well enough to borrow someone else's.

So, while the use of Respect/Validation is gorgeous, elegant and stunningly powerful, it requires a life-style commitment to the PHP priesthood to just GET IT INSTALLED? There will be NO "just stick it in a directory, require_once and go"?

I'd be grateful for a slap-down here, to find out I've misunderstood  the whole thing, and a direction to nice set of simple "unzip and copy" instructions such as normal, fallible humans who don't have the time or resources to re-architect their world for the sake of one PHP library and it's view of how installs SHOULD be done, as peachy as that library may be.

For the time being, in hopeful anticipation of that glorious come-uppance, I'm stuck with GUMP.

I await my beating in happy anticipation. Predicated on the notion that I actually get the answer I need to move forward and not a lot of religious philosophy about what I SHOULD be doing.

**Comment by mscreenie** [comment]
2 Years on I must agree. 

@Flyarbonkers 
'
Lastly, as a final opinion, the TYPE of library that Respect\Validation IS is VERY important. The Internet is a cesspool, and something is always trying to crawl out of it and get into my server: hackers. Input validation is one of perhaps the 3 most important pillars of defense against them. The more stringent and careful the validation, the better. NOT having access to YOUR library I consider a big loss for me. While it's a little late at THIS point, I would, in general, encourage you to architect your libraries designed for the public good biased toward MAXIMAL adoption, if you can. Which means if you structure them such that even dummies and fossils (like me) have easy access to them, more people will be able to use them.
'

Working with many clients, most (I'd say 80%) cannot upgrade PHP until software developers finish migrating code to work from old to new. 

Namespaces are an excellent addition but not usable by many. This project needs to offer a few other examples of ways to integrate it in peoples projects.

**Comment by Poolaidman** [comment]
I couldnt get this way to work but tried composer on my local and then just uploaded the files to my server DIR and it worked. Thanks for the validation package!

**Comment by esaulfarfan** [comment]
I'm for sure late to this party but want to comment Augustohp's [code snippet](https://github.com/Respect/Validation/issues/127#issuecomment-23510151) was so helpful to load this library without Composer (for those don't like it as me). So I just placed the contents of "library/" from the repo into a simple folder structure I created named "Respect/Validation/", then autoloaded all of its contents and after this I was able to instantiate and use the validator as per the documentation:

`use Respect\Validation\Validator as v;

$number = 123;
$valid = v::numeric()->validate($number); // true

var_dump($valid); //prints bool(true)`

This is for far the best PHP validation library I've found :)

**Comment by augustohp** [comment]
> This is for far the best PHP validation library I've found :)

Thanks for your kind words and taking the time to leave a feedback @esaulfarfan ! Your words are very valuable and much appreciated ❤️
