### ISSUE TITLE
Postal Code Validation Fails for Current Armenian Postal Codes

### ISSUE THREAD

**Issue by DanielAlt** [Respect/Validation#1270]
Hello again,

I have 1 Armenian user reporting that Postal Code validation fails for Armenian Postal Codes. 
The Postal Code Validator in ```library\Rules\PostalCode.php at line 16``` specifies that Armenian Postal codes must be 6 digits, the validator should enforce 4 digits instead. 

https://en.wikipedia.org/wiki/Postal_codes_in_Armenia

PR incoming.

**Comment by henriquemoody** [comment]
Fixed by 6e2b3e599e2d671d6e5213363bf1117d614c790c

Thanks for reporting and for sending a pull request as well! 🐼
