### ISSUE TITLE
Missing/expected argument errors caught by code analysis

### ISSUE THREAD

**Issue by alystair** [Respect/Validation#1276]
- Missing argument for ___ (PHP0423)
  Triggered by `alnum`, `alpha`, `digit`, maybe others?

  Examples:
  `v::alnum()`
  `v::length(6,6)->digit()`

- Argument passed is expected to be of type `Validatable`, `Respect\Validation\Validator` given
  Triggered by `anyOf`, `each`, `optional`, and `not`.

  Examples:
  `v::arrayType()->each(v::uuid())`
  `v::url()->anyOf(v::startsWith('http://'),v::startsWith('https://'))`

**Comment by henriquemoody** [comment]
Thanks for reporting, @alystair.

Could you tell me which version of PHP and Validation you're using?

**Comment by alystair** [comment]
Hi Henrique - good news! I got a response from the [code analysis provider](https://www.devsense.com/) and it seems the missing argument 423 error was [definitely on their end](https://community.devsense.com/d/190-help-with-0406-0423-codes) due to improper processing.

I think the other error is also on their end but they haven't responded yet. Less things for you to worry about I guess.
