### ISSUE TITLE
Postal Code Validation Fails for valid Ecuador (EC) postal codes

### ISSUE THREAD

**Issue by DanielAlt** [Respect/Validation#1285]
**Summary**

The Postal Code Validation fails for valid Ecuadorian postal codes. These have a 6 digit format. The specified REGEX in  PostalCode.php expects something different. 

https://github.com/Respect/Validation/blob/master/library/Rules/PostalCode.php#L67

**Comment by henriquemoody** [comment]
Fixed on version 2.0.3

Thanks for reporting! 🐼
