### ISSUE TITLE
Validating multiple variables with variable rules effectively

### ISSUE THREAD

**Issue by chrissound** [Respect/Validation#129]
How can I possibly get an array of all the failed validation rules?

Example: 
```
135     try {
136
137         $validationRules = [
138             'comment' => Validator::string()->notEmpty()->alnum()->length(1,1000)->setName('comment')->assert($post['comment']),
139             'captcha' => Validator::string()->notEmpty()->alnum()->assert($post['captcha']),
140         ];  
141     } catch(\InvalidArgumentException $e) {                                                                                                      
142         $errors = ($e->findMessages(array('notEmpty', 'alnum', 'length')));
143     }
```
When $post['comment'] and $post['captcha'] are both empty, $errors gets set to the following:

```
array (size=3)
  'notEmpty' => string '"" must not be empty' (length=20)
  'alnum' => string '' (length=0)
  'length' => string '"" must have a length between 1 and 1000' (length=40)
```

1. Do I need to specify all the rules to 'check' in the findMessages method? This involves unnecessary work for me to check what rules I used, and having to retype them... 
2. This does not seem to work with 'multiple' variables.
3. Am I using setName() incorrectly? Why are the error messages referencing a '' field?

**Comment by marcosdimitrio** [comment]
@chrissound, I'm late to this, but I think you want something like the code below, which is based on @wesleyvicthor's example:
```php
use Respect\Validation\Validator as v;
try {
	v::arr()
		->key('captcha', v::allOf(
			v::string()->notEmpty()->setName('captchaNotEmpty'),
			v::string()->alnum()->setName('captchaAlnum')
		))
		->key('comment', v::allOf(
			v::string()->notEmpty()->setName('commentNotEmpty'),
			v::string()->alnum()->setName('commentAlnum'),
			v::string()->length(1, 1000)->setName('commentLength')
		))
		->assert($post);
} catch(\InvalidArgumentException $e) {
	$messages = $e->findMessages([
		'captchaNotEmpty' => 'Captcha must not be empty.',
		'captchaAlnum'    => 'Captcha must be alphanumeric.',
		'commentNotEmpty' => 'Comment must not be empty.',
		'commentAlnum'    => 'Comment must be alphanumeric.',
		'commentLength'   => 'Comment must have a length between 1 and 1000.'
	]);
	$messages = array_filter($messages);
	print_r($messages);
}
```
You could just repeat the keys if you want:
```php
	v::arr()
		->key('captcha', v::string()->notEmpty()->setName('captchaNotEmpty'))
		->key('captcha', v::string()->alnum()->setName('captchaAlnum'))
		->key('comment', v::string()->notEmpty()->setName('commentNotEmpty'))
		->key('comment', v::string()->alnum()->setName('commentAlnum'))
		->key('comment', v::string()->length(1, 1000)->setName('commentLength'))
		->assert($post);
```
In both cases, you will get:
```
Array
(
    [captchaNotEmpty] => Captcha must not be empty.
    [commentNotEmpty] => Comment must not be empty.
)
```

**Comment by wesleyvicthor** [comment]
@chrissound considering you might be using other lib and the answers for your question sounds plausible, is it ok to close this issue ?
one day left.

**Comment by chrissound** [comment]
With all due respect this is such a small issue I don't have the time to invest to look into this again. It's been more then a year!

So I honestly don't mind if you close this or leave it open.

**Comment by Jossnaz** [comment]
Is there a proper example to test various input fields at the same time and return custom error messages for each? because that is what you do when you do validation professionally. I don't understand why this is hidden so deeply. I'm surprised.

**Comment by titlebaby** [comment]
use Respect\Validation\Validator as v;
use Respect\Validation\Exceptions\NestedValidationException;
try {
$match = '/^(13[0-9]|14[579]|15[0-3,5-9]|16[6]|17[0135678]|18[0-9]|19[89])\d{8}$/';
    v::arrayType()
        ->key('name', v::stringType()->notEmpty())
         ->>key('phone', v::phone()->regex($match))
        ->assert($_POST);
} catch(NestedValidationException$e) {
    $messages = $e->findMessages([
        'name' => '{{name}} is required',
        'phone'    => '{{name}} must be a valid phone'
    ]);
    $messages = array_filter($messages);
    print_r($messages);
}

**Comment by titlebaby** [comment]
```
use Respect\Validation\Validator as v;
use Respect\Validation\Exceptions\NestedValidationException;
try {
    $match = '/^(13[0-9]|14[579]|15[0-3,5-9]|16[6]|17[0135678]|18[0-9]|19[89])\d{8}$/';
     v::arrayType()
       ->key('name', v::stringType()->notEmpty())
       ->key('phone', v::phone()->regex($match))
       ->assert($_POST);
} catch(NestedValidationException$e) {
   $messages = $e->findMessages([
        'name' => '{{name}} is required',
        'phone' => '{{name}} must be a valid phone'
   ]);
    $messages = array_filter($messages);
    print_r($messages);
}
```
