### ISSUE TITLE
Possible problem with the Date rule

### ISSUE THREAD

**Issue by danilocorrea87** [Respect/Validation#1291]
In the date rule there is a validation in the `isDateTime` method, which is located in the `traits` `CanValidateDateTime` that checks two types of unique format, `c` and` r`, however in the date rule constructor there is a regular expression condition that it will always invalidate the use of these two types.

If this is a bug, I'm happy to send a PR =)

**Comment by henriquemoody** [comment]
That's the expected behavior. 

As described in the [release page](https://github.com/Respect/Validation/releases/tag/2.0.0) the `Date` rule supports only dates (Year, Month, and Day). Both `c` and `r` are formats for date and time.

You should use the `DateTime` rule instead.
