### ISSUE TITLE
Question: exception messages

### ISSUE THREAD

**Issue by danielspk** [Respect/Validation#1295]
Hello, how can I customize the message of an exception according to the parameters of a custom validation rule?

Example:

```php
final class Demo extends AbstractRule
{
    private $additionalChars;

    public function __construct($additionalChars = '')
    {
        $this->additionalChars = $additionalChars;
    }

    public function validate($input): bool
    {
        return true;
    }
}

final class DemoException extends ValidationException
{
    protected $defaultTemplates = [
        self::MODE_DEFAULT => [
            self::STANDARD => '{{name}} xxxxxxx',
            // if additional chars is not empty => '{{name}} xxxxxxx and {{additionalChars}} xxxxxxx'
        ],
    ];
}
```

Thanks

**Comment by alganet** [comment]
You'll probably need to override some `ValidationException` methods to do that.

Some default rules already have custom logic for the templates, such as the `Age` rule:

https://github.com/Respect/Validation/blob/1.1/library/Exceptions/AgeException.php

I believe this one have all the bits and pieces you'll need to declare new $defaultTemplates and implement a new `chooseTemplate()` based on some `getParam()` values!

Let me know if you need further help!

**Comment by danielspk** [comment]
Thanks!
