### ISSUE TITLE
Feature Request method validation

### ISSUE THREAD

**Issue by guiducs** [Respect/Validation#1296]
I was trying to validate a PSR-7 UploadedFile object like this:

v::key('curriculum', v::objectType()->attribute('file', v::extension('pdf') )->setName('Curriculum'))

But I can't because the attribute is not a SplInfo or has the extension on the string and the other properties are protect, so I as wondering if something like this would be possibel:

v::key('curriculum', v::objectType()->**method**('getExtension', v::extension('pdf') )->setName('Curriculum'))

**Comment by henriquemoody** [comment]
Hi, @guiducs.

You can achieve that already by using the [Call](https://respect-validation.readthedocs.io/en/2.0/rules/Call/) rule:

```php
v::key(
    'curriculum',
    v::call(fn($uploadedFile) => $uploadedFile->getExtension(), v::extension('pdf'))
);
```

As for the feature request, perhaps it would be better to just support PSR-7 on all of the file file-related rules.

**Comment by guiducs** [comment]
Thank You. Really clean.
