### ISSUE TITLE
Missing "with" method

### ISSUE THREAD

**Issue by applibs** [Respect/Validation#1298]
I have this code:
`\Respect\Validation\Validator::with('\\Api\\Validation\\Rules')`
and after ungrade via composer I got notification of my IDE that this method not exists.
How to solve it please?

**Comment by danilocorrea87** [comment]
Hi @applibs 

Which version are you using?

If you are using version 1.1 your code should work
https://respect-validation.readthedocs.io/en/1.1/feature-guide/#custom-rules

If you are using version 2.0 see this link, as it has changed a little
https://respect-validation.readthedocs.io/en/2.0/custom-rules/
