### ISSUE TITLE
Serbian Postal Codes Use 6 Digit Regex Validation when should use 5

### ISSUE THREAD

**Issue by DanielAlt** [Respect/Validation#1304]
Hey, Me again, your postal code friend. 

My Serbians are reporting issues with our Postal Code Validator. According to them, (and this wiki https://en.wikipedia.org/wiki/Postal_codes_in_Serbia), their postal code should consist of 5 Digits. We validate against 6. 

PR incoming.

**Comment by DanielAlt** [comment]
PR submitted to earliest stable release 0.9. 
https://github.com/Respect/Validation/pull/1305

**Comment by omega3000** [comment]
Excellent, thanks a lot!

**Comment by henriquemoody** [comment]
Version 2.3 is available! If that doesn't work as expected, let us know! Thank you for reporting! 🐼
