### ISSUE TITLE
Error Remove "?" in 

### ISSUE THREAD

**Issue by Manishfoodtechs** [Respect/Validation#1314]
My set up is as under:
Installed by composer require respect/validation
```
require('../common/vendor/autoload.php');
use Respect\Validation\Validator as v;
use Respect\Validation\Rules;

$first_name = $_POST['first_name'];
$nameValidator = new Rules\AllOf(
    new Rules\Alnum(),
    new Rules\Length(5, 40)
);
$first_name_validate = $nameValidator->validate($first_name);
if ($first_name_validate) {
    echo "Validation passed";
} else {
    echo "Validation failed";
}		

```
I am getting following errors:

(1) Parse error: syntax error, unexpected '?' in ...\vendor\respect\validation\library\Rules\AbstractComposite.php on line 100

function (Validatable $rule) use ($input): ?ValidationException {
I corrected it to :
function (Validatable $rule) use ($input):  ValidationException {

(2) Parse error: syntax error, unexpected '?' in C:\wamp64\www\generator\htdocs111\final\common\vendor\respect\validation\library\Rules\AbstractRule.php on line 69

 public function getName(): ?string
I corrected it to :
 public function getName(): string

Parse error: syntax error, unexpected '?' in C:\wamp64\www\generator\htdocs111\final\common\vendor\respect\validation\library\Validatable.php on line 35

public function getName(): ?string;
I corrected it to :
public function getName(): string;
Finally I got this....

![Untitledval](https://user-images.githubusercontent.com/29369645/91669758-25e85a80-eb35-11ea-898b-bcf83e8305aa.png)

**Comment by henriquemoody** [comment]
Hi, @Manishfoodtechs!

All those errors are happening because your PHP version is not compatible with this library. To use version 2.0 of Respect\Validation you need at least the version 7.2 of PHP.

Hope that helps! 🐼
