### ISSUE TITLE
Equivalent rules of Laravel 'same' rules

### ISSUE THREAD

**Issue by iRaziul** [Respect/Validation#1327]
I like respect validation for its chaining method system and mostly all of my needed rules are available but I am unable to find any method/rule that is equivalent to Laravel's 'same' rule.
This rule is important in cases like confirm password in form.

Here is my code snippet:
```php
function validate(array $rules = []) {
	$errorMessages = [];
	foreach ($rules as $field => rule) {
		try {
			$rule->setName($field)->assert($_POST($field));
		} catch (NestedValidationException $e) {
			$errorMessages[$field] = $e->getMessages();
		}
	}
}
```

Usage:
```php
$v = validate([
	'email' => v::noWhitespace()->email(),
	'password' => v::noWhitespace()->min(6),
	'confirm_password' => v::noWhitespace()->sameAs('password),
]);
```
Although I found `equals` rule but I don't think that it works as I want it to work.
Thankyou

**Comment by henriquemoody** [comment]
Hi, @iRaziul!

You can take a look at the `KeyValue` rule. There is even an example of the exact same thing you want to do there: https://respect-validation.readthedocs.io/en/latest/rules/KeyValue/#keyvalue

Hope that helps, let me know if that doesn't meet your expectations.

🐼

**Comment by iRaziul** [comment]
Thanks buddy, I don't know how I missed this rule -_-

**Comment by iRaziul** [comment]
I have tried to use `keyValue` with assert but It doesn't work as I expected.

This is the code
```PHP
$data = $_POST;
$rule = v::keyValue('confirm_password', 'equals', 'password');
try {
	$rule->assert($data);
} catch (\Exception $e) {
	var_dump($e->getMessage());
}
```

The exception message I get is:

```
All of the required rules must pass for `{ "password": "something", "confirm_password": "somethsing" }`
```
