### ISSUE TITLE
Lacking of Form Validation

### ISSUE THREAD

**Issue by iRaziul** [Respect/Validation#1345]
Undoubtedly this is one of the best validation library I have ever used, but whenever I tried to use it for validating form then it disappoints me :(

I was hoping for something like this for validating a form.
```PHP
// ['email' => 'something@mail.com', 'password' => 'my-password', 'confirm_password' => 'my-password']
$data = $_POST;

// rules for validation
$rules = [
	'email' => v::notEmpty()->email(),
	'password' => v::notEmpty()->length(6, 20),
	'confirm_password' => v::sameAs('password')			// need it badly
];

// validate
v::formRules($rules)->validate($data); // true/false

// another way for error messages
try {
	v::formRules($rules)->assert($data);
} catch (NestedValidationException $e) {
	$errors = $e->getMessages();
}
```

I was trying to figure out any way of doing it by creating a custom rule but no success :(

Can anyone help me?

**Comment by TCB13** [comment]
I don't get the issue, what you're looking for is probably something like this:

````
$iv = new v();
$iv->keyNested("email", v::stringType()->length($settings->security->passwordLength, null));
$iv->keyNested("password", v::stringType()->length(10, null));
$iv->keyNested("confirm_password", v::stringType()->equals($data["confirm_password"]));
$iv->assert($data);
````

https://respect-validation.readthedocs.io/en/latest/rules/KeyNested/
https://respect-validation.readthedocs.io/en/latest/rules/Equals/

**Comment by nickl-** [comment]
Closed: asked and answered
