### ISSUE TITLE
FilterVar casting result to bool

### ISSUE THREAD

**Issue by tlangens** [Respect/Validation#1346]
PHP's [filter_var](https://www.php.net/manual/en/function.filter-var.php) returns filtered data or false if the filter fails. Respect\Validation's FilterVar uses Callback to call filter_var, which in turn casts the result to bool. The result of this is that if valid data from filter_var casts to false, the validator rejects the input even though it passed validation by filter_var.
For example:
```
filter_var('0', FILTER_VALIDATE_INT); // Valid input, returns 0, a valid integer.
(new FilterVar(FILTER_VALIDATE_INT))->validate('0'); // Valid input, returns false.
```

**Comment by dcorrea777** [comment]
@alganet I went to get this issue, but it looks like it's already been fixed, right ?

**Comment by henriquemoody** [comment]
Version 2.3 was released about a week ago.

I'm closing this now 🐼
