### ISSUE TITLE
CountryCode validation for Montenegro

### ISSUE THREAD

**Issue by nboudreau-seedbox** [Respect/Validation#1390]
Montenegro (ME) fails validation ans is ISO-3166 compliant.
https://www.iso.org/obp/ui/#iso:code:3166:ME

**Comment by nickl-** [comment]
@nboudreau-seedbox do you have time to roll a patch for this? I know, I know, it may still be a while before anyone has time to review pull requests but at least it may help someone else with the same need and will definitely go a long way to help resolving this issue.

Thank you for your patience and efforts.

**Comment by nboudreau-seedbox** [comment]
Tried to recreate on my side as I totally had forgotten about this and couldn't reproduce.
