### ISSUE TITLE
[documentaiton] Validation for a full array of data

### ISSUE THREAD

**Issue by prionkor** [Respect/Validation#1425]
so I have looked around in the doc and probably I have missed it because this is obvious. I can validate individual piece of data. but How do I validate an array ($_GET, $_POST) of data? I want to write a full validator then pass it which gives me array of errors if exists.

**Comment by mohammadhzp** [comment]
See [Validating array keys and values](https://github.com/Respect/Validation/blob/master/docs/feature-guide.md#validating-array-keys-and-values) and [Getting all messages as an array](https://github.com/Respect/Validation/blob/master/docs/feature-guide.md#getting-all-messages-as-an-array)  sections on the page.

**Comment by henriquemoody** [comment]
Since this has been opened for a while, I'm closing this one.
