### ISSUE TITLE
How to compare two field

### ISSUE THREAD

**Issue by ghabriel25** [Respect/Validation#1438]
I want to compare two field but with error message using field name for example

Start Year must be less than End Year

The error message that I get is 

Start Year must be less than 2015 << End Year value

**Comment by russelomua** [comment]
Hello!
You can use [keyValue](https://respect-validation.readthedocs.io/en/latest/rules/KeyValue/) validator and add your [Custom message](https://respect-validation.readthedocs.io/en/latest/feature-guide/#custom-messages) on `NestedValidationException` handling.

```php
$data = [
   'start_year' => 2020,
   'end_year' => 2019,
];

$validator = v::keyValue('start_year', 'greaterThan', 'end_year');

try {
    $validator->assert();
} catch (NestedValidationException $e) {
    $errors = $exception->getMessages([
        'start_year' => 'Start Year must be less than '. $data['end_year'],
    ]);

    echo json_encode($errors);
}
```
