### ISSUE TITLE
phone() validation incorrectly invalidates valid UK phone numbers

### ISSUE THREAD

**Issue by reformed** [Respect/Validation#1440]
UK phone numbers can include a 0 (often with brackets or parentheses) depending on if the person calling into the UK is foreign or domestic.

So if a phone number begins with `+44 (0) ...` this will fail, even though it is a valid UK number.

**Comment by henriquemoody** [comment]
Hi, @reformed! Thank you for reporting 🐼 

Which version are you using? Version 2.3 should fix this issue.

**Comment by henriquemoody** [comment]
Based on the previous releases, I assume this issue has been fixed already in version 2.3.

I'm closing the issue to keep the repository clean.

Thank you for reporting this 🐼
