### ISSUE TITLE
phone() in 2.3 dont work correctly

### ISSUE THREAD

**Issue by axessweb** [Respect/Validation#1441]
Hello all!

After updating I got a 500 error because the package `giggsey/libphonenumber-for-php` was missing. (why not put it in the require?)

I installed it, but the parameterless `phone()` validator no longer works.

It's a shame, because it was a useful addition!

Thanks

**Comment by henriquemoody** [comment]
Yes, you're correct, we should have added it to `require`. 

I can imagine we didn't do that because since not everyone would use the Phone rule, that could be an optional improvement. Nonetheless, we should have kept backward compatibility. I will write a patch for it. 

Thank you for reporting! 🐼

**Comment by henriquemoody** [comment]
Could you give me an example of a phone with parenthesis that doesn't work? I've tried `+44 (0)207 123 4567` and it worked fine.

**Comment by henriquemoody** [comment]
My apologies for my delay! And no worries about your English, I didn't see anything wrong with it! -- and I'm not a native English speaker either.

We changed the Phone rule because it was inconsistent. It recognised patterns, but it was hard to ensure the number was correct -- phone numbers are complicated.

If you want to validate the format, you might consider using the `Regex` rule. Have you tried to use that instead?

**Comment by libib** [comment]
This is definitely a breaking change.
Things that used to validate now dont.

555-433-5234 doesn't validate, it used to.
523-2343 doesn't validate, it used to.

4234325 doesn't validate, it used to.

This validator is way to restrictive. 

That's fine, if you can provide the REGEX validation that we can use instead that matches the former validator...

**Comment by henriquemoody** [comment]
Looking closely, that is a breaking change. I could work around that, but that will be a breaking change for people using version 2.3. I'm a bit torn about that. Any suggestions?

**Comment by libib** [comment]
Maybe offer up both validators, at least until version 3 where breaking changes might be more acceptable?

Or if you don't want to do that, in the docs, just show us how to use the REGEX validator to simulate the legacy phone validation. That would work well as a quick workaround.

**Comment by libib** [comment]
@henriquemoody solution would work for us as well.

**Comment by henriquemoody** [comment]
Excellent suggestion, @libib!

I've just created a fix, which is already available on version 2.3.4!

Thank you for reporting this, @axessweb! 🐼

**Comment by axessweb** [comment]
@libib we suggested the same thing at the same time. 😉
Thank you for your intervention and your English better than me.

Thanks @henriquemoody for future fixes 👍

**Comment by henriquemoody** [comment]
No @axessweb, it was me who got confused!

Thank _you_ for the excellent suggestion! In the end, I did what you suggested. And really, don't worry about your English, your English is fine!
