### ISSUE TITLE
Why is it mandatory to require the PHP version to be so new?

### ISSUE THREAD

**Issue by woann** [Respect/Validation#1459]
I used php7.4, when i want update Validation,discover php version must be 8+

**Comment by russelomua** [comment]
Maybe you need to update your php version, because 7.4 is outdated see [Supported versions](https://www.php.net/supported-versions.php). Current active supported version 8.2. 
But you still can use 7.4 compatible versions of this package.

**Comment by henriquemoody** [comment]
Hi there!

Indeed, we don't give active support to PHP 7.4. Regardless of the support of this library, it's recommended that you keep your PHP version up-to-date. Basically, what @russelomua said (thanks, BTW)!

I'm closing this issue because there isn't anything else I could do here.
