### ISSUE TITLE
DateDiff rule

### ISSUE THREAD

**Issue by gvieiragoulart** [Respect/Validation#1462]
Hey guys, I'm new in this project and I want to contribute by doing the DateDiff rule. But I noticed that we don't have any of differentiation rule.

What do you guys think about creating a new Core rule to help these differentiation rules?

**Comment by henriquemoody** [comment]
Hi there!

I've started working on that rule, but due to a succession of major life events, I couldn't complete it for version 3.0. 

https://github.com/henriquemoody/Validation/commit/9e631a8ba18329ecae419fe4f165b656bfb5d406

Is that what you were looking for, @gvieiragoulart? I'd be happy if anyone picks this up.

**Comment by gvieiragoulart** [comment]
Hey @henriquemoody @alganet !

If I could pick this task I would be really happy to try complete but it seems to me that you have done almost the entire work. What do you see that we have to improve?

**Comment by henriquemoody** [comment]
@gvieiragoulart, I don't really know what needs to improve. I know the tests are not passing, though. I won't be working on it any time soon, so if you want to pick it up, I'd be very happy with it!

**Comment by gvieiragoulart** [comment]
@alganet 

I didn't find any Age validator on the code to reuse :( i think i missed something.

**Comment by gvieiragoulart** [comment]
Hey guys, I believe that I completed the feature. 

@alganet  I didn't use those validators because the _type_ is specific to the DateInterval types, so I created another validation.

PR here https://github.com/Respect/Validation/pull/1463

**Comment by henriquemoody** [comment]
Closed by cf03f8ad5f25e6f887ad45ae726d1ba623987e63

Thank y'all for the comments!
