### ISSUE TITLE
Validation with v::when not working

### ISSUE THREAD

**Issue by slashforward-nl** [Respect/Validation#1470]
I have the following code:

```
try {
  $result = v::key(
    'textblok1', 
    v::when(
      v::key('radiobutton', v::equals('textblok1')),
      v::notEmpty()
    )
  )->assert($this->postData);
} catch (NestedValidationException $e) {
  print_r($e->getMessages());
}
```

$this->postData contains the following array:
```
Array
(
    [radiobutton] => textblok2
    [textblok1] => test
    [textblok2] => 
)
```

But i get the following error:
Array ( [textblok1] => "test" is not valid ) 

What am i doing wrong?

Thanks in advance!

Wouter

**Comment by andus4n** [comment]
when using nested conditions you're basically passing the main value to the nested rules.
so, in your example, the engine is checking if "textblok1" is an array with the key "radiobutton" that should equal "textblok1", therefore it fails.
i'm guessin' you want somethin' like this:
```
v::when
(
	v::key('radiobutton', v::equals('textblok1')),
	v::key('textblok1', v::notEmpty()),
	v::alwaysValid()
)
```

**Comment by slashforward-nl** [comment]
Thank you for your suggestion, too bad i get the same with this:

```
$result = v::key(
  'textblok1', 
  v::when(
    v::key('radiobutton', v::equals('textblok1')),
    v::key('textblok1', v::notEmpty())
  )
)->assert($this->postData);

Array
(
    [radiobutton] => textblok1
    [textblok1] => testtest
    [textblok2] => 
)

Array ( [textblok1] => "testtest" is not valid ) 
```

In this case radiobutton equals textblok1, so textblok1 field should not be empty. And its not in our case.
Any suggestions?

**Comment by andus4n** [comment]
Please read my comment thoroughly.
The proper validation rule for your scenario is:

v::when
(
   v::key('radiobutton', v::equals('textblok1')),
   v::key('textblok1', v::notEmpty()),
   v::alwaysValid() // assuming all other scenarios are acceptable
)
->assert($this->postData);

Of course, you should add extra rules like first validating that "postData" is an array etc etc

**Comment by slashforward-nl** [comment]
Ah i thought i could do the v::when in a v::key so i could add rules based on the v::when. 

Textbox rule (if radiobutton = textblok1) then notEmpty else alwaysValid. 
Textbox2 rule (if radiobutton = textblok2) then notEmpty else alwaysValid. 

I will check ik out, thanks for your help

**Comment by andus4n** [comment]
![c0](https://github.com/user-attachments/assets/ab5d94b6-b742-4d13-aae8-7c2754a91d4e)

**Comment by henriquemoody** [comment]
I assume this has been solved. I'm closing this, but feel free to re-open if that's not the case!
