### ISSUE TITLE
Add comments in the classes

### ISSUE THREAD

**Issue by DavidePastore** [Respect/Validation#153]
Do you believe it is possible to insert comments into classes so you know what each validator does?

**Comment by henriquemoody** [comment]
Actually it can be done in the ~~megazord~~ docblock on Validator class, like:

```php
/**
 * @method static Validator allOf() Will validate if all inner validators validates
```

**Comment by batusa** [comment]
PhpStorm:

![validation autocomplete](https://cloud.githubusercontent.com/assets/5388003/14818703/e5dfbc0a-0b94-11e6-87a3-8c4554bba774.png)

**Comment by mazentouati** [comment]
All classes have docblocks now,  https://github.com/Respect/Validation/issues/225#issuecomment-480434951_

**Comment by henriquemoody** [comment]
Thanks for catching this one up, @mazentouati!
