### ISSUE TITLE
How to validate notEmpty bit value 0/1

### ISSUE THREAD

**Issue by NeedToMeet** [Respect/Validation#154]
I noticed that the NotEmpty rule uses PHP's empty(), which always evaluates the value of numeric 0 as false. Values of non-nullable 0 or 1 are common in bit-type fields where an on/off value is set. Any suggestions on how to validate this as non-empty?

**Comment by dereuromark** [comment]
You could have a method boolNotEmpty() which would allow 0 and 1 to pass as not empty, whereas "null" or empty string would be empty then. Just an idea.

**Comment by henriquemoody** [comment]
Will be fixed on version 1.0, see [changelog](https://github.com/Respect/Validation/blob/311891b/CHANGELOG.md#100---2015-10-24) for more info about the version.

To fix this issue now all rules are mandatory, but you can use [optional()](https://github.com/Respect/Validation/blob/311891b/docs/Optional.md) rule to handle optional values, which now is `null` and an empty string by default.
