### ISSUE TITLE
installing from pear

### ISSUE THREAD

**Issue by crevillo** [Respect/Validation#159]
hello. i'm trying to install from pear but i get an error...
```
No releases available for package "respect.li/pear/Validation"
```

am i doing something wrong? thanks!.

**Comment by alganet** [comment]
I'm sorry @crevillo. We did had a PEAR channel, but we haven't upgraded in a while. We deprecated in the last version. 

Our PEAR build was fully automated, if your workflow depends on it, you can run the automated packager by yourself. Let me know if you need it and I'll be glad to help.
