### ISSUE TITLE
Max Date validation.

### ISSUE THREAD

**Issue by thatsasif** [Respect/Validation#161]
I am trying to validate date where it should lesser than current day. It works proper with current year but with previous year its throwing Exception. Below is the code
$value = "20/08/2011" // comes from input post
<code>
try {
                v::date('d/m/Y')->max(date("d/m/Y"))->check($value);
            } catch(\InvalidArgumentException $e) {
                return $e->setName('DOB ')->getMainMessage();
            }
</code>
Exception is raised with a message that the date should be lower even though the date is lower.

tried with v::date('d/m/Y')->max('now')->check($value); which does not validate at all.

**Comment by henriquemoody** [comment]
Now it's possible work with dates on Min, Max and Between rules but it will follow the date format of your locale settings.

I will close this issue but feel free to open it any time if you think it's necessary.
