### ISSUE TITLE
Different exceptions for the same validator

### ISSUE THREAD

**Issue by DavidePastore** [Respect/Validation#164]
I'm working on a new validator and I wish to know if it's possible to create multiple error messages.

This is an example:
```php
v::pdo()
 ->notEmpty()
 ->validate('mysql:host=10.0.0.1;dbname=my_database', 'username', 'password');
```

It can tells me that the connection doesn't work, or the database doesn't exists or the login is incorrect. How can I handle these messages?

**Comment by alganet** [comment]
You can have a single exception that reports different messages. Every `ValidationException` uses a `chooseTemplate` method for this. 

Check [MinException](https://github.com/Respect/Validation/blob/0b3012b65cf705362e4cf803c74009af55e3e680/library/Exceptions/MinException.php) for a sample. It decides the message based on `getParam`. The `getParam()` method is able to retrieve properties as parameters from the validator.

The other way is to have a composite validator (several small nested validators), like [Domain](https://github.com/Respect/Validation/blob/0b3012b65cf705362e4cf803c74009af55e3e680/library/Rules/Domain.php) and modularize the messages.

**Comment by wesleyvicthor** [comment]
@DavidePastore have you tested the answer above ?

**Comment by DavidePastore** [comment]
@wesleyvicthor Yes, it's a nice answer. Thanks @alganet . I think that some information should be in the documentation, so users could easily write plugins.
