### ISSUE TITLE
Duplicated class WritableException

### ISSUE THREAD

**Issue by blitux** [Respect/Validation#169]
Hello there,

When I do "composer dump-autoload -o" I get this message:

```
Warning: Ambiguous class resolution, 
"Respect\Validation\Exceptions\WritableException" was found in both
"Respect/Validation/Exceptions/UploadedException.php" and 
"Respect/Validation/Exceptions/WritableException.php", the first will be used.
```

Shouldn't be it "UploadedException" instead of "WritableException" on Respect/Validation/Exceptions/UploadedException.php?

Thanks!

**Comment by henriquemoody** [comment]
This is already fixed, thanks for reporting and I'm sorry by our late.
