### ISSUE TITLE
Support for logging error messages (on single line)

### ISSUE THREAD

**Issue by flip111** [Respect/Validation#171]
Sometimes the validation message should be send to a log file. The `getFullMessage` message is not really suitable for a good format for a single line. Using the `getIterator` method with `ITERATE_ALL` improves the output for a single line. But is still problematic, because tree information is lost. I like to request a feature to encode the error message tree as json.

**Comment by henriquemoody** [comment]
Now there is `getMessages()` method for nested exceptions that you can use to save as any format you want.
