### ISSUE TITLE
Feature request: not() on individual validator

### ISSUE THREAD

**Issue by flip111** [Respect/Validation#174]
If you want to validate something is not `""` (an empty striing) and is an integer then you have to write:

```
try {
	v::not(v::equals(''))->setName('test')->assert('0');
	v::int()->setName('test')->assert('0');
} catch (\InvalidArgumentException $e) {
	echo $e->getFullMessage();
}
```
Note: `int()` doesn't check for empty string values

Because the `not()` affects the entire chain. If it were possible to put `not()` on a single validator one could write:

```
try {
	v::not(v::equals(''))->int()->setName('test')->assert('0');
} catch (\InvalidArgumentException $e) {
	echo $e->getFullMessage();
}
```

But this throw the following error: `Fatal error: Call to undefined method Respect\Validation\Rules\Not::int()`

**Comment by wesleyvicthor** [comment]
@flip111 you still can assign a validator to a variable and negate it then keep the chain.
Or you can add more examples for what you need, that should help.

one day left to close.

**Comment by henriquemoody** [comment]
This is happening because the `not()` shortcut which was [described](https://github.com/Respect/Validation/blob/master/library/Validator.php#L152-L154) by @alganet in #241

**Comment by henriquemoody** [comment]
@flip111 0.7.3 version is now available with the expected behavior.

**Comment by flip111** [comment]
Great @henriquemoody let's close this then.
