### ISSUE TITLE
Inconsistent DateTime handling

### ISSUE THREAD

**Issue by flip111** [Respect/Validation#178]
Consider the following code:
```php
// Comparison by strings
$datetime1 = '13-05-2014 03:16';
$datetime2 = '20-05-2014 03:16';
v::date()->setName('interval')->min($datetime1)->assert($datetime2);

// Comparison by DateTime objects
$datetime1 = new \DateTime('13-05-2014 03:16');
$datetime2 = new \DateTime('20-05-2014 03:16');
v::date()->setName('interval')->min($datetime1)->assert($datetime2);

// Mixed comparison: string & DateTime object
$datetime1 = '13-05-2014 03:16';
$datetime2 = new \DateTime('20-05-2014 03:16');
v::date()->setName('interval')->min($datetime1)->assert($datetime2);
```

Is all valid, no exception is thrown. Now consider:
```php
// Mixed comparison: DateTime object & string
$datetime1 = new \DateTime('13-05-2014 03:16');
$datetime2 = '20-05-2014 03:16';
v::date()->setName('interval')->min($datetime1)->assert($datetime2);
```
Does not validate, with message:
```
\-These rules must pass for interval
  \-"20-05-2014 03:16" must be greater than 2014-05-13 03:16:00
```
Note that i specificed the date in day-month-year, whilst the DateTime object is formatted as year-month-day in the message. Specifying datetime format on validation does not help.
```php
// Mixed comparison: DateTime object & string
$datetime1 = new \DateTime('13-05-2014 03:16');
$datetime2 = '20-05-2014 03:16';
// with format specified:
v::date('d-m-Y H:i')->setName('interval')->min($datetime1)->assert($datetime2);
```

**Comment by henriquemoody** [comment]
To do that on `min()` rule we need to do the same checking in many other rules, like `max()`, `equals()`, `between()`, etc... IMO, it's doesn't worth.

I see no point on change a behavior which is supported by PHP in itself, if you want to compare dates I strongly recommend you to use `DateTime` objects for both values (comparable and compared).

**Comment by henriquemoody** [comment]
@flip111, this change is going to be available on 0.8 version.

**Comment by flip111** [comment]
@henriquemoody nice job improving the quality of the library!

**Comment by henriquemoody** [comment]
You're welcome, @flip111! Thanks for reporting this.
