### ISSUE TITLE
Allow null values to pass optional validation rules

### ISSUE THREAD

**Issue by zanderbaldwin** [Respect/Validation#205]
Currently `null` values do not pass optional validation rules (by not adding `notEmpty()`), for example:

```php
<?php

    $rule = v::string()->length(28,28);

    // Passes validation:
    $rule->validate('');

    // Does not pass validation:
    $rule->validate(null);
```

I'm using this validation library for an API library, not form submission, so accepting `null` values is important. It would be nice if this could be worked into a future version.

**Comment by henriquemoody** [comment]
Will be fixed on version 1.0, see [changelog](https://github.com/Respect/Validation/blob/311891b/CHANGELOG.md#100---2015-10-24) for more info about the version.

To fix this issue now all rules are mandatory, but you can use [optional()](https://github.com/Respect/Validation/blob/311891b/docs/Optional.md) rule to handle optional values, which now is `null` and an empty string by default.
