### ISSUE TITLE
AbstractRule getName() method bug

### ISSUE THREAD

**Issue by blumfontein** [Respect/Validation#208]
Hello!

Thanx for great library! Recently I wanted to use Respect/Validation in my project and noticed a bug. The $rule->getName() returns nothing. Lets see in the code.

``` php
// Respect/Validation/Rules/AbstractRule.php
public function getName()
{
    if (empty($this->name))
        preg_replace('/.*\\\/', '', get_class($this));
    return $this->name;
}
```

Does line 2 of the method miss some returning or assignment statement? I guess it should be something like this.

```php
public function getName()
{
    if (empty($this->name))
        $this->name = lcfirst(preg_replace('/.*\\\/', '', get_class($this)));
    return $this->name;
}
```

Thanx

**Comment by henriquemoody** [comment]
Seems you have found dead code! :tada:

Whatever, a rule without a defined name must return `NULL` any way, take a look on #213
