### ISSUE TITLE
Hi, Where is the LeapYearException file?

### ISSUE THREAD

**Issue by rhossis** [Respect/Validation#216]
Performing a validation against a year that isn't a leap year produces this Fatal Error:
Platform: Ubuntu 14.04
Php Version: 5.5.19

Warning: require(/var/www/html/cymapgt/Vendor/Respect/Validation/Exceptions/LeapYearException.php): failed to open stream: No such file or directory in /home/rhossis/NetBeansProjects/cymapgt/autoload/SplClassLoader.php on line 133

Fatal error: require(): Failed opening required '/var/www/html/cymapgt/Vendor/Respect/Validation/Exceptions/LeapYearException.php' (include_path='.:/usr/share/php:/usr/share/pear') in /home/rhossis/NetBeansProjects/cymapgt/autoload/SplClassLoader.php on line 133

**Comment by henriquemoody** [comment]
Thanks for report this.
