### ISSUE TITLE
Need Regular Releases

### ISSUE THREAD

**Issue by joefallon** [Respect/Validation#219]
Please make regular releases if there have been fixes and features added. I don't want to add dev-master to my Composer file.

**Comment by henriquemoody** [comment]
You're totally right @joefallon, `0.7.0` is coming with lots of new features and bug fixes. This late is because we don't have a defined Release Cycle process (Respect/project-info#2).

BTW, you don't need to use `dev-master`, you may use something like that:

```json
        "respect/validation": "dev-master#019446c55876d317600bf88066ebb1aecee89821 as 0.6.1", 
```

**Comment by henriquemoody** [comment]
[0.7.0](https://github.com/Respect/Validation/releases/tag/0.7.0) is now available.
