### ISSUE TITLE
Idiotmatic way to validate numeric >= 0?

### ISSUE THREAD

**Issue by jvalentini** [Respect/Validation#233]
I'm looking for the best way to validate that the input is a number (float or int) greater than or equal to 0.

Here's what I have:
```php
v::numeric()->min(0, true)->assert($from);
```

I don't think I can use `positive()` because that's not inclusive of 0. I also tried using some combination of `not()` and `negative()` but I was having some trouble getting that to work.

Is this good or is there a better way?

**Comment by henriquemoody** [comment]
Also, you can do this:

```php
v::numeric()->oneOf(v::min(0), v::equals(0))->validate($input)
```

**Comment by alganet** [comment]
Please note that different approaches may lead to different messages when calling `->assert()`. The inclusive `min` will emit a single message. @henriquemoody approach can be used to separate messages for the "0" case and the negative case.

I haven't run, but I would write the chain using not+negative this way: `v::numeric()->not(v::negative())`. Let me know if that doesn't work! It may be a bug.

**Comment by jvalentini** [comment]
Thanks for the help guys.

@alganet, the chain you listed also works and is what I ended up using as I found it to express the intent more clearly. Thanks!
