### ISSUE TITLE
Conditional rules

### ISSUE THREAD

**Issue by micrarior** [Respect/Validation#237]
Is there beautiful solution for conditional validation like in [laravel](http://laravel.com/docs/4.2/validation#conditionally-adding-rules)?

For example, I need validate field if it is not empty or another field is empty.
Some code
```php
use Respect\Validation\Validator as v;

$input = array(
   'foo' => '0',
   'bar' => '10'
);

$validator = v::create();
if (v::key('foo', v::notEmpty())->validate($input)) {
    $validator->addRule(v::key('foo', v::positive()));
    $validator->addRule(v::key('bar', v::when(v::notEmpty(), v::positive(), v::alwaysValid())));
} else {
    $validator->addRule(v::key('bar', v::notEmpty()->positive()));
}
$validator->check($input);
```

**Comment by micrarior** [comment]
It seems that your laravel's example translate is wrong.
Your "oneOf" rule will be always valid.
I think it looks like
```php
 v::oneOf( 
   v::key('games', v::int()->notEmpty()->max(100)),

   v::key('games',  v::int()->notEmpty()->min(99))    
     ->key('reason', v::notEmpty()->length(null, 2))
);
```
But here we must ignore "max" validation rule error message.

**Comment by micrarior** [comment]
For my first example Respect is missed the "[required_without](http://laravel.com/docs/4.2/validation#rule-required-without)"  rule from laravel

**Comment by alganet** [comment]
I may have written the examples in a little rush and haven't tested them :panda_face: Anyway, can I make anything else clearer about the conditionals?

Thank you!
