### ISSUE TITLE
Deprecate rule shortcuts

### ISSUE THREAD

**Issue by alganet** [Respect/Validation#241]
Our engine is built on rules, but we have two shortcuts. The first one is the base magical shortcut:

```php
v::base36()->validate('testing'); // the base number in the shortcut can vary
v::base64()->validate('testing'); 
v::base(64)->validate('testing'); // no shortcut
```
(I didn't remembered this guy!)

The second shortcut is the "chain negation" shortcut, which happens if you call `not()` empty:

```php
v::alnum()->length(1,15)->not(); // shortcut 
v::not(v::alnum()->length(1,15)); // no shortcut
```

Removing the shortcuts will make [every node on the chain faster](https://github.com/Respect/Validation/blob/30ed4537a96149b3e0802d943ddb42f039e984e5/library/Validator.php#L147). The `__call` method shouldn't have control decisions.

There are no other internal rules that depend on those, but there is a risk of breaking BC for some users. 

Shall we do it? :panda_face:

**Comment by henriquemoody** [comment]
I'm totally with you on that! TBG, I don't like `not()` shortcut because when you use it the order matters and this is not a good behavior

**Comment by henriquemoody** [comment]
About BC brakes, well, I think we must follow semver and just break API's on MAJOR versions.

**Comment by alganet** [comment]
I'm all up for semver as well. The `base` shortcut isn't documented though, perhaps we could slip it into a minor?

**Comment by henriquemoody** [comment]
Agreed! :+1:
