### ISSUE TITLE
Better place for documentations

### ISSUE THREAD

**Issue by henriquemoody** [Respect/Validation#259]
I love our documentation but it's getting hard to keep it.
There are many instructions and documented rules and in one single file ([README.md](https://github.com/Respect/Validation/blob/master/README.md)).

I'm +1 for GitHub pages on this repository.

- [x] Slit "README.md" file by topics
- [x] Put docs into `docs` directory
- [x] Create `gh-pages` branch
- [x] Use [couscous](http://couscous.io/) to render documentation page
- [ ] Implements [lunrjs](http://lunrjs.com)

**Comment by alganet** [comment]
I'm +1 for GitHub pages as well. We do have a `respect.li` set up, it should look nice.

**Comment by malukenho** [comment]
@alganet look for [couscous](http://couscous.io/)

**Comment by henriquemoody** [comment]
Nice, @malukenho, I almost forgot about it.

Sounds the best option since we can keep the docs in the same branch of the code using Markdown and still have a nice page.

My which is to have one Markdown file for each rule and link those rules into an appendix.

//CC @wesleyvicthor

**Comment by wesleyvicthor** [comment]
+1. this name!

**Comment by alganet** [comment]
+1 for cuzcuz! cuz its awesome.

**Comment by henriquemoody** [comment]
Just a test: http://respect.li/Validation/
