### ISSUE TITLE
Feature Request: Truthy Validation Rule

### ISSUE THREAD

**Issue by connerbw** [Respect/Validation#262]
Hi,

Is it possible to create a "Truthy" validator?

That is, for my purposes, the following are all OK: true, "true", "TRUE", "True", 1, "1"

The code would look like this:

```
<?php
namespace Respect\Validation\Rules;

class Truthy extends AbstractRule
{
    public function validate($input)
    {
        if (is_bool($input)) {
            return $input == true;
        }

        if (is_numeric($input)) {
            return (int)$input == 1;
        }

        if (is_string($input)) {
            $input = strtolower($input);

            return $input == 'true';
        }
        
        return false;
    }
}
```

Thank you for your consideration.

**Comment by henriquemoody** [comment]
You can use `v::in(array(true, 'true'))->validete(strtolower($input));`, since `1 == true`, `'1' == true`, `true == true`, and `'true' == 'true'`.

To be honest I don't see much usage for `Truthy` validator, can you give us more some use cases?

**Comment by alganet** [comment]
I can see the reasoning behind this. The [FILTER_VALIDATE_BOOLEAN](http://php.net/manual/en/filter.filters.validate.php) considers even "on" and "yes" as valid **booleanish**. 

Perhaps we could provide a proxy for all **FILTER_VALIDATE_** validators. That could grasp a lot of use cases.

**Comment by connerbw** [comment]
Hi @henriquemoody 

I'm building a REST API using SLIM. I need to validate `/path/to/list?is_active=true`

If I do: `v::bool()->check($app->request->get('is_active', false));`

I get: ***error: ""true" must be a boolean",***

With  `/path/to/list?is_active=0`

If I do your example: ` v::in(array(true, 'true'))->check(strtolower($app->request->get('is_active', false)));`

I get: **""0" must be in (Array)",***

And so on.

Thank you for your consideration

**Comment by connerbw** [comment]
Hi, me again. I take back my second example. This is an expected error. Thusly, your example works fine for my case and I will use it.

That being said, I agree with the points made by @alganet for an overall approach.

Cheers.

**Comment by henriquemoody** [comment]
We already have `yes()` and `no()`, I'm not good with names at all, maybe we can create `trueValue()` and `falseValue()` (we already have `nullValue()`, were the idea came from).

What you think?

**Comment by connerbw** [comment]
I like it.

 :+1:

**Comment by henriquemoody** [comment]
I will send a PR tomorrow! :smile:

**Comment by henriquemoody** [comment]
@alganet, I've created `filterVar()` rule. Take a look on #267.
