### ISSUE TITLE
Method chaining does not work

### ISSUE THREAD

**Issue by konstantinrachev** [Respect/Validation#275]
Hi guys,

I am trying to validate an object, however the method chaining does not work at all.

```php
$Validator = v::attribute('Telephone', v::phone())->attribute('Email', v::email());
```

And after that the assert of this ```php $Validator ``` returns me the following:
```
\-These rules must pass for "really messed up screen#name" |-Attribute Telephone must be present \-Attribute Email must be present
```
As I tested and ensured that one by one, both validations were successfully passed.

**Comment by henriquemoody** [comment]
Can you provide a mode complete example of what you're doing?

**Comment by konstantinrachev** [comment]
Yeah, of course. I am having a handler, let's say ```php $User ```
The post data is sent and written in this handler and after that being handed in to a ```php function Validator() {} ```.

```php
$User = new stdClass;

// Here the data is written
// echoing Name -> 'John', echoing Email -> 'mymail@somesite.com'

$Validator = v::attribute('Name', v::string())->attribute('Email', v::email());

if ($Validator->validate() == true) {  }
```

**Comment by henriquemoody** [comment]
Unfortunately, I have to say the same thing i said on #268.

The `validate()` method doesn't throw exceptions. Is that the exact code you're using?

**Comment by konstantinrachev** [comment]
The exception is thrown by the assert method.
```php
			try {
			    $Validator->assert('really messed up screen#name');
			} catch(\InvalidArgumentException $e) {
			     throw new Exception($e->getFullMessage(), 1);
			}
```

**Comment by henriquemoody** [comment]
But that's the expected behavior since you're trying to validate `'really messed up screen#name'` string.

```php
$Validator->assert('really messed up screen#name');
```

If you validate the `stdClass` you wrote:
```php
$Validator->assert($User);
```

The result will be the same, since `$User` (at least the one you wrote) doesn't have the required properties.

What you are expecting from this code?

**Comment by konstantinrachev** [comment]
The $User has the required properties, I haven't wrote them. Here is the complete code:

```php
public function Validator()
{
	$User = new stdClass;
	$User->Name = = 'John';
	$User->Email = 'mymail@somesite.com';

	$Validator = v::attribute('Name', v::string())->attribute('Email', v::email());

	if ($Validator->validate($User) == true) 
	{ 
		echo 'The validation was successfully passed.'; 
	}
	else
	{
		echo 'The validation failed.';
	}

	try {
	    $Validator->assert('really messed up screen#name');
	} catch(\InvalidArgumentException $e) {
	     throw new Exception($e->getFullMessage(), 1);
	}
}
```

**Comment by AndyWendt** [comment]
You have a syntax error here: `$User->Name = = 'John';`

It works for me with the following code:

```php
use Respect\Validation\Validator as v;

$User = new stdClass;
$User->Name = 'John';
$User->Email = 'mymail@somesite.com';

$Validator = v::attribute('Name', v::string())->attribute('Email', v::email());

if ($Validator->validate($User) == true)
{
    echo 'The validation was successfully passed.';
}
else
{
    echo 'The validation failed.';
}

try {
    $Validator->assert('really messed up screen#name');
} catch(\InvalidArgumentException $e) {
   var_dump($e->getFullMessage());
} 
```

**Comment by konstantinrachev** [comment]
I saw the error, however it does not work again.

**Comment by AndyWendt** [comment]
See edit.

**Comment by henriquemoody** [comment]
6 days and no answer, I guess it's finished. I will reopen it not.
