### ISSUE TITLE
[RFC] - Use of strcit EmailValidator

### ISSUE THREAD

**Issue by egulias** [Respect/Validation#283]
Hi guys!
Awesome library!
I just checked the email validator you use (https://github.com/Respect/Validation/blob/master/library/Rules/Email.php#L8) and it happens to be php's `filter_var`.
[In this gist](https://gist.github.com/egulias/10989413) you can see where `filter_val` fails to validate some emails.
Also `filter_var` is incapable to validate UFT8 emails, which are in fact valid (RFCs [6530](http://tools.ietf.org/html/rfc6530#section-4.6), [6531](http://tools.ietf.org/html/rfc6531), [6532](http://tools.ietf.org/html/rfc6532) that allow for SMTPUTF8 international emails, also [Gmail started accepting them](http://gmailblog.blogspot.com.es/2014/08/a-first-step-toward-more-global-email.html))

The library [EmailValidator](https://github.com/egulias/EmailValidator) covers all that and includes warnings (this needs improvement, truth to be said) and dns check if wanted.

Would you consider integrating it? I can provide the PR if you are ok with it.

Cheers!

**Comment by henriquemoody** [comment]
Thanks for open this discussion!

This sounds like something we really need to do, but I don't want to insert such dependency in validation like `v::email()` which is used very frequently.

Currently we have only 3 external dependencies ([Zend](https://github.com/zendframework/Component_ZendValidator), [Symfony](https://github.com/symfony/Validator) and [BAV](https://github.com/bav-php/bav)) but they are all optional and I don't want to make `v::email()` one of them, even I don't like the idea of repeat code.

Any way, this is just my opinion, how about you @Respect/troubleshooters?

PS.: Nice library @egulias!

**Comment by alganet** [comment]
It is a nice library indeed, congratulations @egulias!

I agree with @henriquemoody. This is an important and popular validator, we should have it within our architecture. Our currently implementation sucks though, and we need to change it.

We already have a [Domain](https://github.com/Respect/Validation/blob/master/library/Rules/Domain.php) rule that could be improved to support the missing features (international domains, IPV6, etc). Our [Tld](https://github.com/Respect/Validation/blob/master/library/Rules/Tld.php) rule also needs improvements, it was designed before custom TLDs existed.

I'm also not sure how to express the several different options that could be configured (to allow or not IPs as domains, to allow or not local addresses, etc) in a clean way. This would be a problem for the library integration as well (how to consider its warnings).

**Comment by egulias** [comment]
@henriquemoody If you look at Symfony's Validator `composer.json` https://github.com/symfony/Validator/blob/master/composer.json#L40 you'll find my library as a soft dependency (btw, it is also a hard dependency in Drupal 8).
[Here](https://github.com/symfony/Validator/blob/master/Constraints/EmailValidator.php#L62) we did the  "soft dependency control".
Maybe we can do something similar?

@alganet I've been thinking on that (configurable behaviour) too, but for v2 of the EmailValidator: how to "configure" the dns check, warnings threshold, etc. And still thinking about it.

**Comment by henriquemoody** [comment]
Use it as a soft dependency sounds good to me. Email validation is a very important thing and your library does it very well.

We are open to receive a pull request, @egulias them we can discuss more details on that.

@alganet, perhaps you will want to take a look on symfony/symfony#1581.

**Comment by henriquemoody** [comment]
Fixed by #311.
