### ISSUE TITLE
Unable to use array for contains()

### ISSUE THREAD

**Issue by rained23** [Respect/Validation#284]
I tried to use array for contains() I receive the following error

```
mb_stripos() expects parameter 2 to be string, array given
```

Currently I want to validate an input against an array

I tried the following
```
v::contains(array('data'))->validate(input); 
```

**Comment by AndyWendt** [comment]
It is throwing that error because it looks like you need to pass a string to `v::contains()`

See the tests: tests/Rules/ContainsTest.php

The source: library/Rules/Contains.php

And the docs: https://github.com/Respect/Validation#vcontainsmixed-value

**Comment by henriquemoody** [comment]
Have you take a look at [in()](https://github.com/Respect/Validation#vinmixed-haystack) rule?

**Comment by rained23** [comment]
@AndyWendt I know the issue that I need to pass string to it, but from the README

![image](https://cloud.githubusercontent.com/assets/907309/6054738/970a00f8-ad2c-11e4-96bf-38d1d95dadd7.png)

contains() also listed in Array list, isn't it misguiding ?

I am going to try
```
v::contains(input)->validate(['needle','needle']);
```

If its working thats okay for me already.

**Comment by rained23** [comment]
@henriquemoody 
I tried in() rule but I want to validate an input that contain a needles.
So basically in() will not work and I tried it.

**Comment by AndyWendt** [comment]
Is `input` a variable or a string?

If it is a string then it needs quotes: `input`

If it is a variable then it needs a dollar sign: `$input`

**Comment by rained23** [comment]
@AndyWendt 

I need to validate a string that contains any string that is listed in an array.

Currently I am iterating those array

```
foreach($needles as $needle):
 v::contains($needle)->validate($input);
endforeach;
```

But I am looking for something like in() but have contains() functionality.

**Comment by alganet** [comment]
Perhaps `v::each(v::contains($needle))->validate($arrayInput);` is what you're looking for!

**Comment by henriquemoody** [comment]
The documentation is not wrong: 

```php
v::contains(1)->validate(array(1, 2, 3));//true
v::contains(true)->validate(array(true, false));//true
```

Looks like `each()` is the one, like @alganet said.

**Comment by rained23** [comment]
Any suggestion for which validation is suitable when dealing with something like this :

User Input  = 'Mark Zurk'

If user input contains Zurk, Zerk or Zark, it will trigger true.

I cannot use each for contains somehow contains is the needle and validate is the haystack.

For my case , the haystack is the user input, while the needle is an array.

When I try to use as suggested by @alganet 
```
 v::each(v::contains('Mark Zurk'))->validate(['Zurk','Zerk,'Zark']);
```

**Comment by alganet** [comment]
Oh I think I got it! What about:

```
v::string()->oneOf(
    v::contains('Zurk'),
    v::contains('Zerk'),
    v::contains('Zark')
)->validate('Mark Zurk');
```

Not that pretty, but you can build the entire object before calling `->validate()`.

**Comment by alganet** [comment]
A tricky solution could be `v::each(v::in($input))->validate($needles)`. Haven't tested though.

**Comment by AndyWendt** [comment]
```php
    $needles = ['Zurk', 'Zerk', 'Zark'];
    $input = 'Mark Zurk';
    var_dump(
        v::each(v::in($input))->validate($needles)
    );
// boolean false
```

**Comment by rained23** [comment]
It will return false because what I can guess in() will find exact value so
the validation will fail. That's the reason contains() is the only rules
that I can use now. I will just assume this issue is settled just maybe for
Respect/validation team can improve the usage of contains() to accept array
as a needle.

**Comment by henriquemoody** [comment]
@rained23, have you tried `oneOf()` with the `contains()`?

**Comment by rained23** [comment]
@henriquemoody I haven't yet, oneOf gonna limit me to have a static contains value, while I am expecting a dynamic contains in case another Zork added to the array in the future.

**Comment by henriquemoody** [comment]
I don't like the idea of allow multiple values on `contains()` constructor. What you want is really what one of does. 

You also can do this:

```php
$rule = new OneOf();
$rule->addRules($myContainsRules);

$rule->validate('Mark Zurk');
```

**Comment by henriquemoody** [comment]
@rained23, should I close this issue?

**Comment by rained23** [comment]
HI Henrique,

Sorry for late response, yeah you can close it.

Thanks for all reply appreciate it.

**Comment by henriquemoody** [comment]
You're welcome :)
