### ISSUE TITLE
Non static use

### ISSUE THREAD

**Issue by designermonkey** [Respect/Validation#294]
I'm always uncomfortable using static classes in my code.

Is there a way to use this in a non static fashion? I may be being dumb.

**Comment by alganet** [comment]
Hi @designermonkey. Actually, there is a way! Have you read [this guide](https://gist.github.com/alganet/b66bc8281672ca3d3b42) yet?

**Comment by designermonkey** [comment]
I will have a good old read tomorrow (it's late now). Thanks very much!

**Comment by henriquemoody** [comment]
Now this also available in the official documentation: http://respect.li/Validation/docs/concrete_api.html

**Comment by designermonkey** [comment]
Fantastic! Thanks guys.
