### ISSUE TITLE
Breakup the readme.md

### ISSUE THREAD

**Issue by Tjoosten** [Respect/Validation#296]
separate the reference form the readme.md

**Comment by henriquemoody** [comment]
It was already on track, but thanks for reporting. :smile:

**Comment by Tjoosten** [comment]
Can i help u with that?

**Comment by henriquemoody** [comment]
It was made already, check it out:

- https://github.com/Respect/Validation/blob/master/docs/VALIDATORS.md
- http://respect.li/Validation/docs/validators.html

You can see the link to those files:

- https://github.com/Respect/Validation/blob/master/README.md
- http://respect.li/Validation
