### ISSUE TITLE
 Call to undefined method Respect\Validation\Rules\AllOf::not()

### ISSUE THREAD

**Issue by beckend** [Respect/Validation#300]
not() should be available for AllOf() also?
Did not check if this works in OneOf(), NoneOf() yet.

**Comment by henriquemoody** [comment]
`Not` is a validation like `AllOf()`, `OneOf()` and `NoneOf()`, you're probably using the [concrete API](respect.li/Validation/docs/concrete_api.html), so I recommend you use:

```php
$validator = new Not(new AllOf(...));
```

Note that call the validator by name, like `$v->int()->notEmpy()` is something available only when you're using the `Validator` class.

**Comment by henriquemoody** [comment]
Should I close this issue, @beckend?

**Comment by beckend** [comment]
thanks
