### ISSUE TITLE
'"validtate" is not a valid rule name'

### ISSUE THREAD

**Issue by bmanam** [Respect/Validation#303]
Seem that calling validate($input); throws:

Fatal error: Uncaught exception 'Respect\Validation\Exceptions\ComponentException' with message '"validtate" is not a valid rule name'

**Comment by henriquemoody** [comment]
It means you wrote `validtate()` instead of `validate()` in some place.

**Comment by bmanam** [comment]
@henriquemoody - Thank you so much and very sorry... it has been a loooong night's programming.

**Comment by henriquemoody** [comment]
No problem at all!
