### ISSUE TITLE
Url does not exist

### ISSUE THREAD

**Issue by peps** [Respect/Validation#309]
Hi, im getting this error.

    Message: Class Respect\Validation\Rules\Url does not exist
    File: respect\validation\library\Validator.php
    Line: 137

    v::url()->validate($url);

**Comment by henriquemoody** [comment]
When there are some new rules in Validation we create a new minor version, `url()` is available since [0.8.0](https://github.com/Respect/Validation/releases/tag/0.8.0) version. What version of Validation are you using?

**Comment by peps** [comment]
Ah, makes sense thanks. Im using 0.7.*
