### ISSUE TITLE
GB Postal code not working

### ISSUE THREAD

**Issue by ghazispeakserve** [Respect/Validation#312]
Hello,

According the official UK documentation the regex for validating "GB" postal code have some issues. I have tried validating "

The link for the RegEx is here on page 6 https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/359448/4__Bulk_Data_Transfer_-_additional_validation_valid.pdf 

A correct UK Postal code is "PR1 9LY". It can be added to unit tests. The same postal code without the median (PR19LY) space is invalid with the government RegEx but valid with Respect RegEx. It should'nt.

**Comment by henriquemoody** [comment]
This change is now available on versions `0.7.7` and `0.8.3` already available on Packagist.

**Comment by henriquemoody** [comment]
Thanks for reporting it and also for the feedback on the pull request. :smile:

**Comment by ghazispeakserve** [comment]
Thank you too. Great support :smiley:
