### ISSUE TITLE
validator object modified when notEmpty is used

### ISSUE THREAD

**Issue by Gloix** [Respect/Validation#315]
Am I doing it wrong?
```PHP
$nameValidator = v::alpha();

var_dump($nameValidator->notEmpty()->validate(''));
// false    expected:false

var_dump($nameValidator->validate(''));
// false    expected:true
```

**Comment by alganet** [comment]
The validator gets modified indeed. Maybe you could clone it:

```php
$nameValidator = v::alpha();

var_dump(clone $nameValidator->notEmpty()->validate(''));
// false    expected:false

var_dump(clone $nameValidator->validate(''));
// false    expected:true
```

**Comment by Gloix** [comment]
So is it the intended behavior?
I have a bunch of validators that I use across my app. Sometimes the inputs are required and sometimes not, so I add `->notEmpty()` after a validator when using it to validate a required field, like in the example I wrote.

I know that I can just write `alpha()` everywhere I need to validate a name, but in reality my name validator is
```
$specialChars = "äëïöüñÄËÏÖÜÑáéíóúÁÉÍÓÚàèìòùÀÈÌÒÙçÇ";
$personName = v::alpha($specialChars."'.")->length(2,50, true);
```
Repeating the same for every person name validation across every file that needs it would be against DRY. Also cloning seems unnatural to me since I should always clone every validator I use in order to avoid these kind of 'collisions'.
Maybe I'm not using the library the right way, and you could guide me to a proper usage with a sort of large project.

**Comment by henriquemoody** [comment]
Just keep in min `v::something()` returns a new chain object, if you add one more rule you will change the state of the object and another rule will be add to the chain but you will can reuse then:

```php
$nameValidator = v::alpha();
$nameRequiredValidator = v::alpha()->notEmpty();
```

Besides, If you clone the object the only object you will clone is the object you're cloning and it's very common see the [Prototype pattern](http://en.wikipedia.org/wiki/Prototype_pattern).

```php
$nameValidator = v::alpha();
$nameRequiredValidator = (clone $nameValidator)->notEmpty();
```

**Comment by Gloix** [comment]
Ok, you convinced me. Thank you for your answers!

**Comment by henriquemoody** [comment]
You're welcome!

**Comment by Gloix** [comment]
I've come across another while cloning. I have a time validator like this:
```php
$timeValidator = v::oneOf(v::date('H:i'),v::date('G:i'));
```
Then when I want to use it, I do the following:
```php
===Validators.php===
function cloneValidator($validator) {
	return clone $validator;
}

===SaveMyObject.php===
$inputValidator = v::key('start_time',cloneValidator($timeValidator)->setName('START_TIME')->setTemplate('Start time not valid'))
            ->key('end_time', cloneValidator($timeValidator)->setName('END_TIME')->setTemplate('End time not valid'));

try{
    $inputValidator->assert(array('09:00','23')) //Must reject because '23' is not an accepted time format.
} catch(Exception $e) {
    var_dump($e->findMessages(array('START_TIME','END_TIME')));
}
```
I expect in the dumped array only the ``END_TIME`` to have an error, though I find this:
```php
  'START_TIME' => string 'At least one of these rules must pass for START_TIME' (length=52)
  'END_TIME' => string 'End time not valid' (length=18)
```

I think the issue here is that ``clone`` only clones the object superficially. I'd need a deep copy here, so ideally ``__clone`` should be implemented in the library, right?

**Comment by henriquemoody** [comment]
Have you testes it without using close, like creating new chains? Just asking because looks like this problem is not related to the clone itself.
