### ISSUE TITLE
Some GB postcodes should be invalid

### ISSUE THREAD

**Issue by GhaziTriki** [Respect/Validation#316]
Hello,

After running some custom tests I have found that GB postal code regex is still not correct. A random generated invalid post codes are marked as invalid while they match the GB regex, examples are:
- GM4N6TF
- O719MQ
The strange behaviour is that those values most of the time are invalid which is correct and sometimes they are valid !!!

**Comment by henriquemoody** [comment]
I'm a little full of job right now, can you send us a pull requests agains `0.7` branch with this fix? Also with a lot of postal codes on PostalCodeTest?

**Comment by ghazispeakserve** [comment]
No problem we still have a lot of testing to implement. I will propose a fix pull request no less in a month ( I will be away for two weeks ) once I have fixed that issue.

**Comment by henriquemoody** [comment]
Hey @GhaziTriki! Do you have some feedback about this issue?

**Comment by GhaziTriki** [comment]
Sorry but I didn't get any feedback from the UK gov website.
