### ISSUE TITLE
Validating multi-dimensional or nested arrays?

### ISSUE THREAD

**Issue by mscreenie** [Respect/Validation#317]
Could someone post a basic example on how to validate a multi dimensional array ? 

```
array("contact"=>  
  array("number" => 22, "address" => "192 Parks Road" )
 )
```

Would really appreciate some insight!

**Comment by henriquemoody** [comment]
Take a look at the [key](http://respect.li/Validation/docs/key.html) rule.

**Comment by mscreenie** [comment]
Thanks! I'll give this a go.

**Comment by mscreenie** [comment]
So if I was validating this array:

Nested array was:

```
$signup = array("contact"=>  
  array("number" => 22, "address" => "192 Parks Road" ),
"organisation"=>  
  array("type" => "small", "address" => "192 Parks Road" )
 )
```

The code should look something like this

```
v::key('number')->validate($signup["contact"]);
```
And for organisation

```
v::key('number')->validate($signup["organisation"]);
```

?

**Comment by henriquemoody** [comment]
Yes, it's a way of do that, but you also can use one only chain:

```php
$signup = array(
    'contact'=> array(
        'number' => 22,
        'address' => '192 Parks Road',
    ),
    'organization'=> array(
        'type' => 'small',
        'address' => '92 Business Road'
    ),
);

v::key('contact', v::key('number', v::int()))
 ->key('organization',  v::key('type', v::length(1,32)))
 ->validate($signup);//true
```

Ps.: Looks like you have a typo on `organisation`.

**Comment by williamespindola** [comment]
Yes! But i think you want validate the type instead number in organization array?

**Comment by mscreenie** [comment]
Brilliant, thanks for the example / support @henriquemoody. 

Yes of course! How I picked up American spelling I don't know. Must get back and correct code before anyone in the office notices. :Whoops:

**Comment by henriquemoody** [comment]
Good luck! :stuck_out_tongue_closed_eyes:

**Comment by mprince** [comment]
What if I want to validate a generic multi-dimensional array WITHOUT looping through each sub-array? For example I get a series of 'emails' that contains the same 6 fields and I want to to validate these fields against specific rules every time. Is there a way in Respect to do this. Here is an example of what I need:
`use Respect\Validation\Validator as Respect;

$validator = Respect::keySet(
            Respect::key("user_email", Respect::email()),
            Respect::key("display_name", Respect::alpha()),
            Respect::key("folder_name", Respect::in(["transactional", "alert"])),
            Respect::key("campaign_name", Respect::alnum()),
            Respect::key("message_id", Respect::numeric()),
            Respect::key("options", Respect::json())
        );

$params = array(
            'emails'
            => [
                [
                    'user_email' => $email1,
                    'display_name' => 'Test',
                    'campaign_name' => 'TRANSForgotPassword1',
                    'folder_name' => 'transactional',
                    'message_id' => '42334',
                    'options' => '{ "data": "data"}'
                ],
                [
                    'user_email' => $email2,
                    'display_name' => 'Test',
                    'campaign_name' => 'TRANSForgotPassword',
                    'folder_name' => 'alert',
                    'message_id' => '1123',
                    'options' => '{ "data": "data"}'
                ]
            ]
        );

try {
            $validator->assert($params);
        } catch (NestedValidationException $exception) {
            throw new MetaHalt(400, GeneralErrors::VALIDATION_ERRORS($exception->getFullMessage()));
        }`
