### ISSUE TITLE
mb_strlen Alternative

### ISSUE THREAD

**Issue by Nixhatter** [Respect/Validation#319]
Since mb_strlen() is not on enabled on PHP by default, it limits the use of Validation on shared servers, plus you get a lot of people not sure why it's not working.

I understand strlen() is not perfect because it counts bytes and so it changes depending to the encoding, but there should be a middle ground.

An example of its use is in Length() (line 49).
> return mb_strlen($input, mb_detect_encoding($input));

which could be changed to
> return strlen( utf8_decode($input));

This way it supports up to 4 bytes per character and works on default PHP setups. 
Other related issue: https://github.com/Respect/Validation/issues/54

Just a change I needed to do personally and maybe thought it could help.
Thanks again for the validation library!

**Comment by henriquemoody** [comment]
Thanks for bring it to the table.

That's something I was thinking about, we also use bcmath on IP rule.
We must have classes (or traits) to handle strings and maybe numbers as well.

**Comment by dereuromark** [comment]
At the current point in time, mb extension can be seen as a de facto standard. 
I have not seen anything different. Also the major frameworks all require it to function properly with utf8 support. What systems would there be that do not have it enabled by default (or could not do so easily)?

**Comment by henriquemoody** [comment]
According to the [manual](http://php.net/manual/en/mbstring.installation.php) mbstring _is not enabled by default. You must explicitly enable the module with the configure option_, despite all package manager I've seem have it enabled by default.

Any way, we can just embrace mbstring instead of creating an alternative. But I think using `utf8_decode()` is not an option, it will create issues on non-utf8 systems like ISO-8859-1, for example.

I'm in favor of using the default string functions or mb_* functions when mbstring is available, how about you guys?

**Comment by Nixhatter** [comment]
Thanks for looking into it! The problem arises when I write something that will be used on a shared host. Lots of hosts won't have mbstring enabled by default (eg. GoDaddy) and then will force me to add a step in the installation where they create or append the mbstring extension to php.ini. I'm sure in the future mbstring will be turned on by default as dereuromark said, because it has become the standard.


Also good catch henrique, using `utf8_decode()` could mess up a string with ISO-8859-1. However `strlen()` works perfectly with ISO-8859-1 any many other encodings that are limited to 1byte/character.

So here's my new solution:

>if(!function_exists('mb_strlen')) {
>    return mb_strlen($input, mb_detect_encoding($input));
>} else {
>    if (preg_match('!!u', $string)) {
>        // this is utf-8
         return strlen( utf8_decode($input));
>    }
>    else {
>       //  not utf-8 and most likely a single byte 
>      return strlen($input);
>    }
>}


 `if (preg_match('!!u', $string))` taken from http://stackoverflow.com/questions/4407854/how-to-detect-if-have-to-apply-utf8-decode-or-encode-on-a-string/4407996#4407996

I haven't tested the code, and I think you can just stick with your current solution because my problem is probably in the minority. It was just a fun exercise in php and encodings.

**Comment by henriquemoody** [comment]
Those bugs were finally fixed on versions [1.0.12](https://packagist.org/packages/respect/validation#1.0.12) and [1.1.7](https://packagist.org/packages/respect/validation#1.1.7) by #729.

Thanks for reporting! :panda_face:
