### ISSUE TITLE
noWhitespace validator causes warning on array input

### ISSUE THREAD

**Issue by bmorg** [Respect/Validation#346]
Using the `noWhitespace` validator on an array produces a warning (because of the `preg_match` usage):

```php
v::digit()->noWhitespace()->assert(array());
```

The warning:

```
PHP Warning:  preg_match() expects parameter 2 to be string, array given in /.../respect/validation/library/Rules/NoWhitespace.php on line 8
```

Strangely the warning is not shown when using `validate()` instead of `assert()`.

**Comment by henriquemoody** [comment]
This was fixed on versions [0.8.7](https://github.com/Respect/Validation/releases/tag/0.8.7) and [0.9.1](https://github.com/Respect/Validation/releases/tag/0.9.1).

**Comment by bmorg** [comment]
Thanks for the quick fix!

**Comment by henriquemoody** [comment]
Kudos to @augustohp :beer:
