### ISSUE TITLE
Filtering for Rules

### ISSUE THREAD

**Issue by alganet** [Respect/Validation#35]
This is a major feature that will require a lot of work.

I've added filtering support for the Int Rule to make some tests. 

https://github.com/Respect/Validation/blob/develop/library/Respect/Validation/Filterable.php
https://github.com/Respect/Validation/blob/develop/library/Respect/Validation/Rules/AbstractComposite.php
https://github.com/Respect/Validation/blob/develop/library/Respect/Validation/Rules/Int.php

Filtering on rules will allow users to not just validate data, but filter it.

``` php
<?php

$myPureInt = v::int()->filter("12 pigs");
var_dump($myPureInt); //int(12)
```

For this, a lot of discussion may happen on how each current rule will filter data and how future rules will filter data. It is possible also to create filter-only rules that doesn't validate nothing, but filter data.

Filtering and validation must be called in separate steps for now:

``` php
<?php

$validator = v::string()->noWhitespace()->digits()->length(1,20);
$notDirtyAnymore = $validation->filter($someDirtyShit);
$isValid = $validation->validate($notDirtyAnymore);
```

However, it is desirable (yet-no-so-simple-to-do) to have a build in routine that allows filtering and validating to be chained:

``` php
<?php
v::int()->filter()->validate($input); //filter before
v::int()->validate()->filter($input); //filter after
```

I really need some feedback on this.

**Comment by septianw** [comment]
This is good feature, currently what i do is "filter it first and validate it." this feature will make my life simpler.
