### ISSUE TITLE
Validate array structure

### ISSUE THREAD

**Issue by oschwald** [Respect/Validation#350]
I am sure this must be possible, but I am having a hard time figuring out how to validate array structure with this library. By this, I mean that the keys of the array are within a set of key values _and_ that each value associated with each key is of the right type. I initially thought this might be possible with each, but I don't see a way to ensure that the value is the right type for the key. For instance, if I have arrays of the form `['username' => 'name', 'user_id' => 102]`, how do I validate that the array only contains `username` and `user_id` and that `username` always points to a string while `user_id` points to an integer?

**Comment by oschwald** [comment]
I guess this might be possible with something like:

```
v:arr()->key('username', v::string)->key('user_id', v::int())->in(['username', 'user_d'])
```

but this does not seem particularly DRY as the keys need to appear twice. Is there a better way?

**Comment by henriquemoody** [comment]
I'm sorry by my late.

In our feature guide (http://respect.li/Validation/docs/) there is the _Custom Rules_ section that might be useful for you if you want to create custom rules.

I'm not sure why you want a specific array structure, can you elaborate the reason why? Maybe we can implement on Validation if that's a common need.

**Comment by augustohp** [comment]
Hmn, maybe @oschwald wants to validate that the *array* has **only** those keys and nothing more. I can't think on using anything different from what he came up with.

He can create a custom rule for `keysAllowed`, but we could also implement that rule and make it available.

**Comment by oschwald** [comment]
My use case is to validate a data structure matches the required schema for a web service, ensuring that there are no invalid or misspelled keys before the request is sent.

**Comment by alganet** [comment]
How about:

```php
$validator = v::arr()
            ->key('user_id',  v::int(), false) 
            ->key('username', v::string(), false)
            ->length(2); //only specified ammount of keys by count
```

Or a more specific approach with the [call](http://respect.li/Validation/docs/call.html) validator:

```php
$validator = v::arr()
            ->key('user_id',  v::int(), false) 
            ->key('username', v::string(), false)
            ->call('array_keys', v::equals(['user_id', 'username']));
```

The `v::call` in this case allows you to use a custom callback on the input (in this case, only the native `array_keys` function) and then validate the result of this callback using another validator (in this case, [equals](http://respect.li/Validation/docs/equals.html)).

**Comment by oschwald** [comment]
Not sure that would work for my use case as most, but not all of the keys are optional. The solution I posted does work, but it would be nice to have a solution that is both simpler and does not require the key names to be repeated several times. Perhaps some tool in the spirit of JSON Schema would be a better fit, but I was otherwise very happy with this library.

**Comment by augustohp** [comment]
Maybe we could provide `optionalKey` and `requiredKey` in the same spirit of `key`.

**Comment by henriquemoody** [comment]
I understood the request but I think it's unnecessary, with the `key()` rule you can check if the key is present, if there are more keys than expected it shouldn't matter because my code should not use unknown keys.

Any way, I created #374 since looks like there is some interest on that rule, which I will probably not use.

**Comment by henriquemoody** [comment]
@oschwald, take a look on #374 when you can to see if that is what you're expecting.

**Comment by oschwald** [comment]
That looks great to me. :+1:
