### ISSUE TITLE
json validation not correct for empty array

### ISSUE THREAD

**Issue by bartdeman** [Respect/Validation#351]
When you try to validate "[]" (empty array) as in:
```
v::json()->validate("[]");
```
the validation returns false, although [] is valid json.

(Reason is that in php an empty array is considered false, and in Validation/Library/Rules/Json.php the result of json_decode is converted to bool and returned, resulting in false here)

**Comment by henriquemoody** [comment]
Versions 0.8.8 and 0.9.2 fix this bug.

Thanks for reporting!
