### ISSUE TITLE
Alnum additional character not working

### ISSUE THREAD

**Issue by eedithz** [Respect/Validation#352]
Hi, this issue is actually already exists right here https://github.com/Respect/Validation/issues/114. In case no one read my comment on that issue, i created this one, i'm in a hurry :bomb:  . Feel free to remove this issue, and use the old one if neccessary.

I try to do something like this:

v::alnum("@")->validate("my@email.com")

but it return false. I know the issue is resolved, but it seems happen again.

**Comment by alganet** [comment]
Perhaps it's failing on the dot of `.com`, not the `@`. Try:

`v::alnum(".@")->validate("my@email.com");`

**Comment by eedithz** [comment]
Silly me, thanks for your answer.. :+1:
