### ISSUE TITLE
Filesize and FileType Validator?

### ISSUE THREAD

**Issue by joeporterme** [Respect/Validation#356]
Sorry, ill preface this by saying im a newb and finally have this working after some hours of messing around.  i have my validations working but i have a file input in my form.  Not sure if i am missing it or not but is there a File Type Validator and File size? 

Example: Making sure it is a jpg or png file that is less than 1MB being inputed.

**Comment by henriquemoody** [comment]
Hey, @joeporterme, unfortunately these rules do not exist. I will not have time for create them so soon, but if you want, please send a pull request, then me or someone else can review and merge.

**Comment by maxw3st** [comment]
Not sure what language you're using but, in Java this would take two validation steps on  an input field. 
String FileInput;
double filebytes = File.length( FileInput );
double fileMB = ( filebytes / 1024 ) / 1024
if (FileInput == *.jpg || *.png) // checks for a file type that is either jpg or png
    if ( fileMB < 1 );  // checks to see if the file is less than 1MB in size

**Comment by joeporterme** [comment]
Yeah. I have it done in php right now. Just didn't know if it came with RV. Be nice to have all in one :). Thanks for the replies guys.




On Sat, Jun 13, 2015 at 11:57 AM -0700, "Max West" <notifications@github.com<mailto:notifications@github.com>> wrote:


Not sure what language you're using but, in Java this would take two validation steps on an input field.
String FileInput;
double filebytes = File.length( FileInput );
double fileMB = ( filebytes / 1024 ) / 1024
if (FileInput == *.jpg || *.png) // checks for a file type that is either jpg or png
if ( fileMB < 1 ); // checks to see if the file is less than 1MB in size

**Comment by maxw3st** [comment]
It looks like the only real difference between Java and PHP is that in PHP the method is filesize() instead of File.length. Both return a value in bytes, so divide that returned value by 1024 twice. Also, you can put both conditions into one line:

if ( ( $InputFile == *.jpg || $InputFile == *.png ) && ( filesize( $InputFile ) < 1000000 ) )

**Comment by joeporterme** [comment]
This is how i have it working for myself in case anybody is wondering

if (!empty($_FILES['image']['type'])) :
			//This is the directory where images will be saved 
			$target = "/var/www/pathtosebsite/httpdocs/img/"; 
			$target = $target . time() . basename( $_FILES['image']['name']); 
			$allowed = array("image/jpeg", "image/png");
			$file_type = $_FILES['image']['type'];
			$filename  = basename($_FILES['image']['name']);
			$extension = strtolower(pathinfo($filename, PATHINFO_EXTENSION));
		
				$nicetitle = nicetitle($title);
				//change image name
				if (!empty($filename) || !isset($filename)){
					$image = $nicetitle.'-'.time().'.'.$extension;
				} else { 
					$image = $oimage;
				}
			
				// Validate Image Type and Size
					
				if(!in_array($file_type, $allowed) && !empty($file_type)) {
					$errorimage = 'JPG or PNG Files Only';
				}
				if($_FILES["image"]["size"] > 1048576) {
					$errorimagesize = 'File size too big. Limit 1 MB'; }	 
		endif;

**Comment by henriquemoody** [comment]
The rules [Size](https://github.com/Respect/Validation/blob/master/docs/Size.md), [Extension](https://github.com/Respect/Validation/blob/master/docs/Extension.md) and [Mimetype](https://github.com/Respect/Validation/blob/master/docs/Mimetype.md) will be available when version 0.10 be release.

PS.: For now you can use version 0.10-dev, `"respect/validation": "~0.10@dev"` on your "composer.json" file.
