### ISSUE TITLE
Not rule checking instance of AllOff

### ISSUE THREAD

**Issue by tavocado** [Respect/Validation#369]
In the `__construct`, `absorbComposite`, `assert` and `validate` methods in the `Not` rule they're checking for `instanceof AllOff` when I assume it's meant to be `instanceof AllOf`.

**Comment by augustohp** [comment]
Hmn, although I see no functionality is affected by this we have a problem regarding exception messages on composite rules (exceptions from multiple rules).

Thanks for the report, I am trying to address it ASAP.

**Comment by tavocado** [comment]
I've never hit/noticed any problems with it, I was just browsing through the code and my IDE couldn't find it.

**Comment by henriquemoody** [comment]
Just an information, when changed PHPUnit got 4 errors and 2 failures.

**Comment by augustohp** [comment]
I've tried to address all of our usage of this rule, I think I've managed to nail all the possible use cases we are having problems with the current test case on the Pull Request.

Still haven't managed to fix those bugs though. :grimacing:
