### ISSUE TITLE
Release Cycle and Support 

### ISSUE THREAD

**Issue by henriquemoody** [Respect/Validation#373]
It's very important for us to discuss about this. I know we've discussed it early (Respect/project-info#2) but I think every project must have its own release process.

## MAJOR/MINOR versions

- Every 6 months
- No need of pre-releases

It's a very acceptable interval, IMO.

## PATCH versions

- Release right after the bug fix

Actually, that's what happens today.

## Version support

- The last 2 MINOR versions
- The last released version of the last MAJOR version

**Scenario 1:**

- The last released version is 2.5
- The last released version of the last MAJOR version is 1.8

We give support for 1.8, 2.5 and 2.4.

**Scenario 2:**

- The last released version is 2.0
- The last released version of the last MAJOR version is 1.8

We give support for 1.8 and 2.0.

**Comment by augustohp** [comment]
(Y)

**Comment by alganet** [comment]
(Y)

**Comment by augustohp** [comment]
How we should expose this? There is any pattern on keeping this inside a code repository? Maybe a `RELEASES.md` file at the root directory of the project?

**Comment by henriquemoody** [comment]
I think we can use the Wiki for that.

**Comment by alganet** [comment]
The main `README.md` should be enough, right? When a branch is deprecated, we put on that specific branch:

    (This version is deprecated, please see <link to project home/wiki/packagist>)

**Comment by henriquemoody** [comment]
+1 for @alganet's comment, but I think the @augustohp's question was more about where we expose the process itself.

**Comment by alganet** [comment]
> +1 for @alganet's comment, but I think the @augustohp's question was more about where we expose the process itself.

Got it :panda_face: I'd say outside the repo then, because it is information outside any branch.

**Comment by augustohp** [comment]
Wiki is a :+1: for me too.

**Comment by williamespindola** [comment]
:+1: for release and wiki

**Comment by ICarpenter** [comment]
When do you plan to release a version with updated array support for "in" exceptions? 
see here: https://github.com/Respect/Validation/blob/master/library/Exceptions/ValidationException.php#L87?

I am not comfortable using master for stability reasons so having this in a release ASAP would be awesome. Thank you!

**Comment by henriquemoody** [comment]
The last release was on Apr 24, so the next one will be Oct 24, but 2 releases (MAJOR or MINOR) a year is starting to look too much time, indeed.

If we make it shorter, like 3 releases a year (1 release every 4 months) the support for will be only 8 months, which is not that bad since we have LTS for the previous MAJOR version.

I'm in favor to make it shorter, 4 months to release.

Any thoughts?

**Comment by ICarpenter** [comment]
Respect is a pretty mature codebase and the number of releases a year should not need to be more than two or three. I guess the issue is how many large features you plan on releasing in the future.

The "less than awesome" parts of the library that I have encountered are around the customization of errors. This might be remedied by adding features rather than changing existing behavior. For a little context, I work for a medium sized e-commerce platform that has started using Respect as a de-facto standard for validation. We would love to see more granularity in error messaging!

**Comment by henriquemoody** [comment]
I made some improvements on exception messages today, @ICarpenter (69f433db6b01ab1b93741a87fa0e98557dbabd14 and 5a41a6bf0c3694fc814e2fcfba30f04c24f43506) but we cannot have more granularity control with the current design we have, probably after #354 there will be more, depending on which approach we choose.

**Comment by henriquemoody** [comment]
The wiki has been updated.
