### ISSUE TITLE
->bool() - what does it actually validate?

### ISSUE THREAD

**Issue by talz13** [Respect/Validation#376]
I'm trying to use the bool() function to validate a checkbox input on my form.  My validator is defined as:

    $boolValidator = v::notEmpty->bool();
    if ($boolValidator->assert(filter_input(INPUT_POST, 'b_default'))) {
        $b_default = (bool) filter_input(INPUT_POST, 'b_default');
    }

But it always comes back false, as it doesn't seem to be handling string representations of bool?  My checkbox input looks like this:

    <input type="checkbox" name="b_default" <?= $vehicle->b_default ? 'value="TRUE" CHECKED : 'value="FALSE"' ?>>

So the validator should be receiving a string of "TRUE" or "FALSE"... I don't care to have the bool function tell me whether it was true or false, just that it was able to interpret it as a boolean value.

Am I using this incorrectly?

**Comment by augustohp** [comment]
> `$boolValidator = v::notEmpty->bool();`

You have a problem which is not related to what you want, but is a problem wither way: `v::notEmpty()->bool();`.

You've missed `notEmpty` as a method call instead of being an public attribute.

> So the validator should be receiving a string of "TRUE" or "FALSE"... I don't care to have the bool function tell me whether it was true or false, just that it was able to interpret it as a boolean value.

You've practically answered your own question. An "string" is not a "boolean", that is why the validator fails. You can use:

```php
<?php
// ...
$isBooleanString = v::oneOf(
    v::string()->equals('TRUE'),
    v::string()->equals('FALSE')
)->setName('Boolean string');
```

Or you can try converting the input to a boolean before validation.

**Comment by henriquemoody** [comment]
Also, there are rules [True](http://respect.li/Validation/docs/true.html) and [False](http://respect.li/Validation/docs/false.html) you may use.

**Comment by talz13** [comment]
@henriquemoody Thanks, the `true()` function is really what I was looking for in the first place!  I was just a bit lost due to the limited documentation on the `bool()` page.  Using the `true()` function is much better than trying to account on my own for the various string values it could be interpreted from!

@augustohp I now see the `notEmpty` missing the method call in my post... That was just a typo when writing my post (can't copy/paste between PCs!)

Thanks for the quick responses!
