### ISSUE TITLE
Autoload issue

### ISSUE THREAD

**Issue by d3sire** [Respect/Validation#377]
I am having this issues after I have migrated to production server from development server. I am using Capistrano for deployment so my directories structures is default to capistrano. There are two folders in my app directory: current and releases. Current is link to the latest release folder. So after deploying code I started to have this issue: 
```
PHP Warning:  include(/var/www/myapp/releases/20150722212129/v3/vendor/respect/validation/library/Validator.php): failed to open stream: No such file or directory in /var/www/myapp/releases/20150722212129/v3/vendor/composer/ClassLoader.php on line 412

Warning: include(/var/www/myapp/releases/20150722212129/v3/vendor/respect/validation/library/Validator.php): failed to open stream: No such file or directory in /var/www/myapp/releases/20150722212129/v3/vendor/composer/ClassLoader.php on line 412
PHP Warning:  include(): Failed opening '/var/www/myapp/releases/20150722212129/v3/vendor/respect/validation/library/Validator.php' for inclusion (include_path='.:/usr/share/php5:/usr/share/php') in /var/www/myapp/releases/20150722212129/v3/vendor/composer/ClassLoader.php on line 412

Warning: include(): Failed opening '/var/www/myapp/releases/20150722212129/v3/vendor/respect/validation/library/Validator.php' for inclusion (include_path='.:/usr/share/php5:/usr/share/php') in /var/www/myapp/releases/20150722212129/v3/vendor/composer/ClassLoader.php on line 412
PHP Fatal error:  Class 'Respect\Validation\Validator' not found in /var/www/myapp/releases/20150722212129/v3/lib.php on line 6

Fatal error: Class 'Respect\Validation\Validator' not found in /var/www/myapp/releases/20150722212129/v3/lib.php on line 6

``` 

Piece of code where this issue rises:

```
<?php
#use Respect\Validation\Validator as v;
#autoload inclusion here

if ( Respect\Validation\Validator::numeric()->validate(5)) {
        echo 'hi';
}

?>

```

This issue only happens for Validation library, other packages work fine. 
EDIT: Forgot to mention that I am using class map feature of Composer.
EDIT 2: Located real issue, for some reason git doesn't see files in respect folder at all, files are not ignored

**Comment by augustohp** [comment]
I think you have a couple of different issues here, we use composer's autoload feature, meaning that if other dependencies get loaded by it so should Respect/Validation do too.

I don't know how you are using capistrano either but, either way one should not version files inside "vendor" directory.

**Comment by d3sire** [comment]
Thank for your reply. I have already figured out the problem hence issue is closed. By the way can you please elaborate on why one should not version files inside vendor directory?

**Comment by alganet** [comment]
@d3sire because [Composer has a lock](https://blog.engineyard.com/2014/composer-its-all-about-the-lock-file)! You can ensure that when dependencies are fuzzy like "2.*", your deploys will actually use a more specific version "2.1.1" that was grabbed when the `composer.lock` was generated. You should put only the lock on version control.

**Comment by meinzeugde** [comment]
I know this thread is a bit old, but I have just the same problem. I am using composer and have locked a specific version of respect/validation (1.1.9). on my local server everything works fine after have a "composer dump-autoload -o". Capistrano with Composer plugin does just the same when deploying to my server. Even the classmap (vendor\composer\autoload_classmap.php) is generated exactly the same as on my localhost. For some weird reason Respect Validator fails with this kind of message:

> "customRule" is not a valid rule name

when i require my custom rules manually within my index.php everything works out. so my question: how have you solved you issue @d3sire?

**Comment by augustohp** [comment]
@meinzeugde Is the rule of your namespace declared on `composer.json`? I am considering you are executing code that already added a [custom namespace][1] to `Respect\Validation\Validator`.

PS: I created [a guide on how to do custom rules that might be more clear than the documentation][2].

[1]: https://github.com/Respect/Validation/blob/master/docs/README.md#custom-rules
[2]: https://gist.github.com/augustohp/d9275aca4cf6d833888e

**Comment by meinzeugde** [comment]
i tried the following now:

1. composer.json -> add a separate namespace for the rules besides the app namespace
```
{
    "autoload": {
        "psr-4": {
            "App\\": "app",
            "App\\Validation\\Rules\\": "app/validation/rules"
        }
    }
}
```

2. index.php -> changed...
```
Respect\Validation\Validator::with('App\\Validation\\Rules\\');
```
....to...
```
Respect\Validation\Validator::with('App\\Validation\\Rules');
```

No effect...same error.

As i said...if i do `require 'app/validation/rules/myCustomRule.php'` within my index.php everything works both on localhost and on my server. I feared there would be an error because of requiring files twiche, but there isn't. So for me this would be the current workaround.

**Comment by meinzeugde** [comment]
Solved...see edit #3.

**Comment by augustohp** [comment]
> Solved...see Edit 2 and Edit 3.

Nice to know. thanks for the update! 🙇
