### ISSUE TITLE
Tests refactoring

### ISSUE THREAD

**Issue by henriquemoody** [Respect/Validation#379]
We have to refactor the tests before we launch version 2.0.

- [x] Move exception testes (`assert()` and/or `check()`) methods to PHPT
- [x] Remove duplicated tests of `assert()` and `check()` of classes that are children of `AbstractRule`
- [x] Move all integration tests to PHPT tests
- [x] Create `RuleTestCase` class in order to make rule tests easier
- [x] Create tests for `AbstractRule` class
- [x] Create tests for abstract classes
- [x] Create tests for untested rules
- [x] Create integration test suite
- [x] Move unit tests to `tests/unit` directory
- [x] Use `@covers` annotation on rule tests (757c377)
- [x] Use `@group rule ` annotation on rule tests (757c377)

Most of this issue was discussed by @alganet, @augustohp and me on Hangouts.

**Comment by alganet** [comment]
I'm working on the tests for the AbstractRule class.

**Comment by batusa** [comment]
I'm working on the tests for abstract classes (:
