### ISSUE TITLE
Add php-cs-fixer and default configuration

### ISSUE THREAD

**Issue by nochso** [Respect/Validation#388]
[PHP Coding Standards Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) would be a great way to worry less about format/indenting guide lines.

Each fixer can be explicitly included or excluded so it should be no problem to reflect the current practices.
You can define project defaults in a file `.php_cs` which will be used when running it with `./vendor/bin/php-cs-fixer fix`.

I'd recommend using the PSR2 level as a starting point and then including any extra fixers for formatting (e.g. no spaces when concatenating).

**Comment by henriquemoody** [comment]
I use php-cs-fixer on everything I do with PSR2, Respect\Validation included.

Can you provide a pull request with this file?

**Comment by nochso** [comment]
Sure, I'll run it too just to show what it will change.

**Comment by henriquemoody** [comment]
See da193b7.

**Comment by henriquemoody** [comment]
But run it again, also in `tests` directory. There are changes.

**Comment by nochso** [comment]
I added it in require-dev so you can run `vendor/bin/php-cs-fixer fix`. Use `--dry-run --diff` to avoid changing files.

The only change was a trailing space.

Settings are PSR2 plus `phpdoc_params`:
> All items of the @param, @throws, @return, @var, and @type phpdoc tags must be aligned vertically.
Which will actively align @stuff the way it's currently done.

**Comment by nochso** [comment]
Added a couple of fixers in 43ecddf:

* All items of the @param, @throws, @return, @var, and @type phpdoc tags must be aligned vertically.
* Convert double quotes to single quotes for simple strings.
* Group and seperate @phpdocs with empty lines.
* An empty line feed should precede a return statement.
* Remove trailing whitespace at the end of blank lines.
* Removes extra empty lines.
* Unused use statements must be removed.

**Comment by henriquemoody** [comment]
Cool! I will take a better look tomorrow or today, later on, if you don't mind, but it seems pretty great for my.

PS.: Take care when you use `@` on GitHub, you just tagged 5 people when you wrote `@param, @throws, @return, @var, and @type`.

**Comment by nochso** [comment]
Oops! I escaped it as code.

Sure, feel free to mess around with any fixers >PSR2 and see what you prefer or makes sense.
