### ISSUE TITLE
Call method on input?

### ISSUE THREAD

**Issue by FoxxMD** [Respect/Validation#391]
I want to validate an attribute by calling a method on the attribute, is this possible?

Right now I have something like this

    v::attribute('recipient', v::instance('Recipient')->callback('validate'))

Where I want the callback to invoke the `validate()` method on `recipient`. But this doesn't work. Is there some way of going about this?

**Comment by henriquemoody** [comment]
You should try this:
```php
v::attribute('recipient', v::callback(array(new Recipient(), 'validate'))
```

The ``callback`` rule accepts only callable, using `'validate'` it will try to use a function called `validate`

**Comment by FoxxMD** [comment]
Thanks! Your code snippet works but validates a new instance of `Recipient` -- I want to be able to validate the instance of `Recipient` that is at the attribute `recipient` in this class though.

**Comment by henriquemoody** [comment]
In this case you have to use the input, like:

```php
$object->recipient  = new Recipient();

v::attribute('recipient', v::instance('Recipient')->callback([$object->recipient, 'validate']))
    ->assert($object);
```

Sorry, but that's the only way.

**Comment by FoxxMD** [comment]
That's perfect :+1: This is what is working for me:

    v::attribute('recipient', v::callback([$this->recipient, 'validate']))

Thanks!

**Comment by FoxxMD** [comment]
Is it possible to use a method as an attribute rather than a property? Or can that be done with `callback()`?

**Comment by henriquemoody** [comment]
I'm not sure if I understood you, can you give me an example of your needs?

**Comment by FoxxMD** [comment]
I figured it out :)

```
v::call([$this, 'getAddress'], v::callback(function ($val) {
    return $val instanceof AddressContract;
})),
```

**Comment by henriquemoody** [comment]
Actually `Instance` [checks classes and/or interfaces](https://github.com/Respect/Validation/blob/master/library/Rules/Instance.php#L30).

The problem you're facing using the `Instance` rule is probably because you're relying on the `use` statements you have but the rule cannot see outside its own namespace, so you have the use the fully qualified name (like `My\Namespace\AddressContract`). I'm just guessing...

**Comment by FoxxMD** [comment]
Thanks @henriquemoody that was it exactly! One last question...

This works

```
v::callback([$this, 'getWeight'], v::notEmpty()->numeric()),
```

but this doesn't

```
v::callback('getAddress')->instance('\App\Models\Request\Contracts\ToAddress'),
```

I get `Respect\Validation\Exceptions\ComponentException: Invalid callback`

But but the [docs](https://respect.github.io/Validation/docs/callback.html) for callback say you can use a method and the example shows a string as the method name. Do I always have to use `[$this, 'methodName']` in order to call a method on the class?

**Comment by henriquemoody** [comment]
I'm really sorry about my late. It was one day before release the 1.0 version for I was a lot busy. 

Did you find a way to do this?

**Comment by FoxxMD** [comment]
Yes! But I ended up not using it because I lost all of the nice error descriptions that are generated when operating on an attribute. Thanks for all your help!
