### ISSUE TITLE
Throw error on unallowed keys

### ISSUE THREAD

**Issue by Zyles** [Respect/Validation#394]
Is it possible to throw an error if there are keys present that are validated which are not defined in the validator?

For example I have a get request ?foo=bar&second=value

```
$validator = v::arr()
				->setName('parameters')
				->key('foo', 	v::alnum()->notEmpty()->setName('foo')
			);
```

Can I throw an error because "second" is also sent into the validator but not present in arr() and make it "not allowed" per default?

**Comment by henriquemoody** [comment]
We recently implemented the [KeySet](https://github.com/Respect/Validation/blob/master/docs/KeySet.md) rule, but it's going to be released only in the next version, at Oct 24th.

If you don't what to use an unstable version 1.0.x-dev, which we do not recommended for production environments, you can do something like that:

```php
v::arr()
    ->setName('parameters')
    ->key('foo', v::alnum()->notEmpty()->setName('foo'))
    ->call(
        'array_keys',
        v::each(v::in(['foo', 'bar', 'baz']))
    );
```

When you `assert($_GET)` the only accepted keys will be `foo`, `bar` and `baz`.
