### ISSUE TITLE
Better error messaging for 1.0?

### ISSUE THREAD

**Issue by Zyles** [Respect/Validation#395]
Are there plans to fix the error messaging for 1.0 release. I am using it now. Everything works great but that.

I use this library to validate input in rest API so I output the error in a JSON response.

This is my code:

```
$validator = v::keySet(
	v::key('providerid', 		v::int()->notEmpty()),
	v::key('amount', 		v::int()->notEmpty()),
	v::key('fee', 			v::int()->notEmpty()),
	v::key('active', 			v::bool())
);

try {
	$validator->assert($postData);
} catch(NestedValidationExceptionInterface $e) {
	throw new \Exception($e->getFullMessage(), Codes::HTTP_NOT_ACCEPTABLE);
}
```

If I send parameters that should not be included shouldn't the error message say something like "key is not allowed"?

Instead get error response such as:

```
ERROR: \-These rules must pass for \"'1', '9999', '', '20', '20', '1', '1', '1', '1', '1', '1', , \"
```

Shouldn't it echo the key name rather than the value?

Do I need to create my custom error messages for all of this?

**Comment by henriquemoody** [comment]
THB, there is no plans to make messages better in 1.0, but in 2.0, you can check some tests of the new version:

- https://github.com/Respect/Validation/tree/new_api/tests/integration/assert
- https://github.com/Respect/Validation/tree/new_api/tests/integration/check

There are many problems with the exception messages that we know, it's been a PITA  in the current 0.x version. The version 1.x will be just like 0.x, you can see more information on https://github.com/Respect/Validation/issues/364#issuecomment-122103562. I will try to make them better, but I cannot promise that.

Maybe the `findMessage()` method can be helpful for you.

**Comment by Zyles** [comment]
It would be nice if you could get an array like $validator->errors();

That looks like this:

```
[
    "username" => "The username field is required.",
    "password" => "The password field is required.",
];
```
A really simple array with the key and the message.

That way you can render it easy on HTML with a LI element, or you can use it as JSON response in a REST API.

**Comment by henriquemoody** [comment]
That's on track, but for 2.0 as well, not in the $validator class, because if must be stateless, but on the exception class.
