### ISSUE TITLE
[Question] Any way to change the default error validation messages

### ISSUE THREAD

**Issue by 7rust** [Respect/Validation#400]
Is there any way to change the default error messages for certain validation types?

**Comment by henriquemoody** [comment]
There is no way to change the message for the validator itself, unless you create a rule with the same name and them overwrite the exception messages, see https://github.com/Respect/Validation/blob/master/docs/README.md#custom-rules.

You also can create custom messages when asserting the inpu, see https://github.com/Respect/Validation/blob/master/docs/README.md#custom-messages.

If you want something simpler, you can define the default message template for your message, like:

```php
v::email()->setTemplate('This is not an email, dude!')->check($input)
```

I hope this help, you can reopen this issue if you think it's necessary.
