### ISSUE TITLE
New rule: String that is a valid PHP label (variable/function names, etc.)

### ISSUE THREAD

**Issue by thedavidmeister** [Respect/Validation#401]
Would be good to be able to validate that a string is a valid PHP label - useful when writing something that will take input to help create output that we expect to execute later.

From the PHP docs:

http://php.net/manual/en/functions.user-defined.php
http://www.php.net/manual/en/language.variables.basics.php

````
As a regular expression, it would be expressed thus: [a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*
````

**Comment by henriquemoody** [comment]
Fixed by f40eb63d7b640697f612d513ea47b61c6a3f6293
