### ISSUE TITLE
Rule: True is confusing for integers other than 0 and 1 and all floats.

### ISSUE THREAD

**Issue by thedavidmeister** [Respect/Validation#408]
Currently `v::true()` returns valid for every number other than 0, like casting directly to a boolean, but also behaves like `filter_var()` in other respects.

For strings like `'yes'` and `'no'` the validator treats them as valid `true()` and `false()` respectively. This is the behaviour of `filter_var()` but casting these to a boolean both returns `true`.

I had expected `true()` to not validate floats like `0.5` and numbers like `2` as it looked like it was behaving like `filter_var()` in most other respects.

There are no tests written for any numbers other than 0 and 1, and no documentation, so it's hard to tell whether this is a bug or the intended behaviour, it's also dangerous behaviour when the docs only cover the number 1.

**Comment by thedavidmeister** [comment]
confusing results:

<img width="692" alt="screen shot 2015-09-12 at 2 06 14 am" src="https://cloud.githubusercontent.com/assets/629710/9819788/6e04bb6c-58f3-11e5-89e6-6c3ef724416a.png">

**Comment by henriquemoody** [comment]
Yes, we have to make it better. This happens because is uses the PHP behaviour, `$input == true`, and for PHP 0.5 and 2 are also true.

**Comment by henriquemoody** [comment]
Thanks for reporting! :panda_face:
