### ISSUE TITLE
array of the second degree

### ISSUE THREAD

**Issue by silverpark** [Respect/Validation#412]
Hi,

Is there a way to test an array of the second degree ?

For exemple :

```
array(
    'ref' 'dk',
    'app' => array(
        'doc' => 'yml'
        'content' => array(
            'test' => 1
        )
     ),
);
```

I would like test ``->key('app.doc', v::string())̀`` and ``->key('app.content.test`, v::int())``

Best

Daniel

**Comment by henriquemoody** [comment]
Yes, you just need to use `key()` as the rule to validate, take a look on this example: https://github.com/Respect/Validation/blob/master/tests/integration/assert-with-keys.phpt

**Comment by silverpark** [comment]
Thank you ! :)
