### ISSUE TITLE
AbstractCtypeRule don't validate null as valid value

### ISSUE THREAD

**Issue by mrsoto** [Respect/Validation#417]
The base AbstractCtypeRule force that all input has value, this is because AbstractRule don't evaluate null as empty, this invalidate https://github.com/Respect/Validation/blob/master/docs/README.md#input-optional principle.

I'm developing an SPA based on Angular. If a field is not edited then the request don't have this field in the json request.

**Comment by henriquemoody** [comment]
Actually it's not only this rule, the only value considered as _optional_ is `''`, as you can [see on AbstraectRule](https://github.com/Respect/Validation/blob/748b280/library/Rules/AbstractRule.php#L29-L33).

Unfortunately there is a bunch of issues related to it #244, #154, #196, #173, #205, #235, #336

**Comment by henriquemoody** [comment]
Will be fixed on version 1.0, see [changelog](https://github.com/Respect/Validation/blob/311891b/CHANGELOG.md#100---2015-10-24) for more info about the version.

To fix this issue now all rules are mandatory, but you can use [optional()](https://github.com/Respect/Validation/blob/311891b/docs/Optional.md) rule to handle optional values, which now is `null` and an empty string by default.

**Comment by mrsoto** [comment]
Looks that some time there will be v::optional(v::notEmpty()...)

**Comment by henriquemoody** [comment]
Exactly, @mrsoto, that's because `notEmpty()` invalidates values like `0` or `'0'` that are _empty_ but shouldn't be considered as optional.
