### ISSUE TITLE
v::equals('member')->validate($input) fails where $input = "" (empty string)

### ISSUE THREAD

**Issue by buggedcom** [Respect/Validation#418]
Because of the nature of equals, if the input is an empty string, the expected assumption is that it should fail should it not?

**Comment by henriquemoody** [comment]
Unfortunately it's not only `equals()` which has this problem, see #235.

**Comment by henriquemoody** [comment]
Will be fixed on version 1.0, see [changelog](https://github.com/Respect/Validation/blob/311891b/CHANGELOG.md#100---2015-10-24) for more info about the version.

To fix this issue now all rules are mandatory, but you can use [optional()](https://github.com/Respect/Validation/blob/311891b/docs/Optional.md) rule to handle optional values, which now is `null` and an empty string by default.

**Comment by buggedcom** [comment]
Nice one. I wasn't expecting any traction on this for a while since the other issue was quite old.

**Comment by henriquemoody** [comment]
Very old, I must say. BTW, the 1.0 version will be released on Oct 24th. In order to make it compatible with PHP7 there will be API breaks, so, if you want to use 1.0-dev, make sure to pin the version on composer.lock file.
