### ISSUE TITLE
Bug validator In

### ISSUE THREAD

**Issue by silverpark** [Respect/Validation#428]
Hi,

I have a problem, when i use ``v::in(['url', 'email'], false)->notEmpty()->check()`` I receive ``must be in (Array))``

In the class ``InException`` this line does not work ``self::STANDARD => '{{name}} must be in ({{haystack}})',`` because I not receive the haystack values of the array.

It is normal ?

**Comment by henriquemoody** [comment]
Yes, this is normal, but it will change on version 1.0, it will looks like:

```
"value" must be in { "url", "email" }
``

The version will be released on Oct 24th, take a look on the [changelog](https://github.com/Respect/Validation/blob/master/CHANGELOG.md#100---2015-10-24).
