### ISSUE TITLE
Bug oneOf

### ISSUE THREAD

**Issue by silverpark** [Respect/Validation#436]
Hi,

I have a new bug about ``oneOf``, simple exemple for found this bug :
```php
v::create()
            ->key(
                'mode',
                v::string()->notEmpty(),
                true
            )
            ->oneOf(
                v::key(
                    'mode',
                    v::contains('email'),
                    true
                )->key('apply_email', v::email(), true),

                v::key(
                    'mode',
                    v::contains('URL'),
                    true
                )->key('apply_url', v::url(), true)
            )->validate($input);
```

If I run validation of :
```php
$input = array(
    "application" => array(
        "mode" => "email",
        "apply_url" => "http://mycompany.com/AM-1234",
    ),
);
```

I receive 
```
(Key apply_email must be present)
```

But If I run validation of :
```php
$input = array(
    "application" => array(
        "mode" => "url",
        "apply_email" => "am-1234@mycompany.com",
    ),
);
```

I receive :
```
(\"url\" must contain the value \"email\")
```

It is normal ? If yes, why ?

**Comment by henriquemoody** [comment]
You did't write it on your issue but you're probably using `check()` method and it throws the first exception thrown in the stack. See the order:

Chain 1:
1. Has key `mode`?
2. Dos key `mode` contains "email"?
3. Has key `apply_email`?
4. Is key `apply_email` an email?

Chain 2:
5. Has key `mode`?
6. Dos key `mode` contains "mode"?
7. Has key `apply_url`?
8. Is key `apply_url` an URL?

Example 1:

```php
$input = array(
    "mode" => "email",
    "apply_url" => "http://mycompany.com/AM-1234",
);
```

You receive `Key apply_email must be present` because it's the first rule that fails in the chain.

Example 2:

```php
$input = array(
    "mode" => "url",
    "apply_email" => "am-1234@mycompany.com",
);
```

You receive `"url" must contain the value "email"` because it's the first rule that fails in the chain.

**Comment by silverpark** [comment]
I have a big contraints of use ``check()`` and ``assert()`` ?

You told me #425 : 

- Any way, if you use check() instead of assert() you're gonna get this message but not wall the failures will be shown.

- Personally I use check() for most cases, because assert() doesn't display a very user friendly message, IMO.

But you told me here :

- Using check() method and it throws the first exception thrown in the stack. See the order:

Have you a solution for this problem ?

**Comment by henriquemoody** [comment]
What you really want is not to use one rule or other, the validation you want to perform depends on `mode` key, so you should not use [oneOf()](http://respect.github.io/Validation/docs/oneof.html) but [when()](http://respect.github.io/Validation/docs/when.html):


```php
v::create()
    ->key('mode', v::in(array('email', 'url')))
    ->when(
        v::key('mode', v::equals('email')),
        v::key('apply_email', v::email()),
        v::alwaysValid()
    )
    ->when(
        v::key('mode', v::equals('url')),
        v::key('apply_url', v::url()),
        v::alwaysValid()
    );
```
