### ISSUE TITLE
An Or Validator

### ISSUE THREAD

**Issue by silverpark** [Respect/Validation#437]
Hi,

There is a validator who validate if one of validation is true ?

For exemples :
```
v::oneOf(v::contains('email'),v::contains('url'))->validate('email'); // true
v::oneOf(v::contains('email'),v::contains('url'))->validate('url'); // true
v::oneOf(v::contains('email'),v::contains('url'))->validate('toto'); // false
```

A validator like that exists ?

Thank in advance.

**Comment by henriquemoody** [comment]
That's what [oneOf()](http://respect.github.io/Validation/docs/oneof.html) should do, isn't?

**Comment by henriquemoody** [comment]
I think I understand and answer your question on https://github.com/Respect/Validation/issues/436#issuecomment-146570012.

Feel free to reopen this issue any time! :panda_face:
