### ISSUE TITLE
Create integration test for "Bank" rule

### ISSUE THREAD

**Issue by rogeriopradoj** [Respect/Validation#528]

**Comment by henriquemoody** [comment]
Fixed by b1a86e6065c9ac9d55c22f600c979a603f3d4ccd

**Comment by henriquemoody** [comment]
Depends on bav-php/bav#19

**Comment by henriquemoody** [comment]
The "Blank" rule doesn't exist anymore, and instead we have "NotBlank" which already have integration tests.

Thanks for reporting and for your work on the TestFest! 🐼
