### ISSUE TITLE
Create IMEI validator

### ISSUE THREAD

**Issue by hussani** [Respect/Validation#539]
Create a new validator to check valid IMEIs (International Mobile Station Equipment Identity).

The rule is explained on this wiki https://en.wikipedia.org/wiki/International_Mobile_Station_Equipment_Identity

**Comment by henriquemoody** [comment]
Hey, @hussani! Could you send us a pull request with this rule? 

(It's not hard to create one, take a look how: https://github.com/Respect/Validation/blob/master/CONTRIBUTING.md#adding-a-new-validator)

**Comment by hussani** [comment]
@henriquemoody i'm working on it =)
Today's night will send a PR with this rule.

Thanks!

**Comment by henriquemoody** [comment]
Cool!

**Comment by diegoholiveira** [comment]
@henriquemoody and @hussani: done

:nail_care:
