### ISSUE TITLE
Json rule is accepting data which are not json

### ISSUE THREAD

**Issue by batusa** [Respect/Validation#563]
while I was checking out some unit tests, I sported with the [JsonTest](https://github.com/Respect/Validation/blob/master/tests/unit/Rules/JsonTest.php#L52) class, and there's a data provider which includes *strings* such as: 

* 2
* null
* false
* "abc"

as valid json formats.

in my understanding they are not jsons and cannot be validated as a json string.

**Comment by henriquemoody** [comment]
Fixed by dddad80f485dc9307986c59b844740003ab2814b
