### ISSUE TITLE
enhance contribution process to avoid two people working on the same thing

### ISSUE THREAD

**Issue by batusa** [Respect/Validation#605]
let's talk here about how we can enhance the contribution process to avoid this issue.

it started here: https://github.com/Respect/Validation/pull/600

**Comment by diegoholiveira** [comment]
@henriquemoody: a simple mecanism that may work is using the `Assignee` in the issue. We ours projects here we use it and works.

**Comment by henriquemoody** [comment]
@diegoholiveira, yes, but it only works for members of the organization, I cannot assign an issue for someone who isn't part of it.
![screen shot 2015-11-04 at 4 11 36 pm](https://cloud.githubusercontent.com/assets/154023/10947382/c80e7180-830e-11e5-916f-5aec94b9a9cd.png)

**Comment by KennedyTedesco** [comment]
Most of repositories that I know haven't such mechanism. People just have to look before create a PR. Sometimes conflict can occur. It's kinda normal I guess. =(

But, ideas are always welcome. :+1:

**Comment by diegoholiveira** [comment]
Let's move on. I guess we are trying to fix a problem that doesn't exists...

:nail_care:

**Comment by henriquemoody** [comment]
> Most of repositories that I know haven't such mechanism. People just have to look before create a PR. Sometimes conflict can occur. It's kinda normal I guess. =(

I have the same opinion about it.

> Let's move on. I guess we are trying to fix a problem that doesn't exists...

Actually it does exist, but I don't think we can do much than we do now.

A simple comment and checking may fix the problem, like https://github.com/Respect/Validation/issues/379#issuecomment-148925568 and https://github.com/Respect/Validation/issues/379#issuecomment-152268047

Unfortunately everyone must check it before start to working on that, and before start, they must notify in the repository.

**Comment by batusa** [comment]
it's complicated...
the fact of leaving a note on an issue can avoid such thing, but it also doesn't mean the person will really do it (and do it well)...

so as you guys have said, the rule of thumb is: before you do any code, check if already exists an issue/pull request for what you want to do.

another thing is, I think that pull requests about `new features` or `design issues` would be better if they come along with an issue beforehand. in the issue I'll be able to validate my proposal, and a good talk can leads to better code.

**Comment by williamespindola** [comment]
My cents! I think that the process is this:
1. I found a problem or feature
2. Search for this on issues. (Github search is very smart for this)
  - No exists any issue
     - Open the issue and lets work!
  - I found an issue
     - no one working on it?
       - comment on like [#379 (comment)](https://github.com/Respect/Validation/issues/379#issuecomment-148925568) and lets work!
     - some people is working on?
       - Call him by mentioning with `@` and ask for the work 
         - No replays?!
           - comment on like [#379 (comment)](https://github.com/Respect/Validation/issues/379#issuecomment-148925568) and lets work!
         - Reply?!
           - follow and help working together and make it better possible

**Comment by henriquemoody** [comment]
I think 183b3a5f1c8be8926ee1a83de109694e4144d802 fixes it, but if it's not, just comment here and I will reopen this issue.

Thanks for all your comments, guys!

**Comment by batusa** [comment]
:+1:

**Comment by batusa** [comment]
hey guys!

would be good to ask for tests in case of bug fix? (enhance or create a new test method in order to "cover" the bug).

**Comment by henriquemoody** [comment]
No bug fixes should be accepted without a regression test, although I like to avoid making many requests to the contributors.

There are lots of kinds of developers who have contributed do this project along the time, but somethings, and I have to say very often, they just don't have the necessary knowledge to send a pull request that is 100% of what we expect to merge.

Nowadays, instead of make a lot of comments on pull requests and simply wait for changes that sometimes never come, I just prefer to get the hands dirty and do what is necessary to finish the job. I've seem many pull request getting older because contributors not always make the necessary changes and that's not only on this repository.

So, I prefer to keep the bureaucracy the minimum as possible so everyone is able contribute.

**Comment by batusa** [comment]
got it @henriquemoody
