### ISSUE TITLE
Custom error messages for multiple failed validations of the same type

### ISSUE THREAD

**Issue by danfashiongps** [Respect/Validation#610]
If i have an object that is testing for a first name and a last name with a length(1, 32) and they both fail their respective length checks.  How do I get my custom messages for BOTH failed validations?

an example:

``` php

        $u = new \stdClass();

       $u->userName = 'blab lab la';
       $u->firstName = '';
       $u->lastName = '';


try {
            return $this->validator->assert($u);
        } catch (NestedValidationException $exception) {
            $errors = $exception->findMessages([
                'length'        => '{{name}} custom message yay'))
        }
```

In this case both firstName and last Name failed validation but I only get a response for firstName.  How can I get a custom message for both failing length checks?

**Comment by williamespindola** [comment]
Hi @danfashiongps you can use `getFullMessage` to get all messages check the [docs here](https://github.com/Respect/Validation/blob/master/docs/README.md#informative-exceptions)

**Comment by danfashiongps** [comment]
Sorry I should have made this more clear.  I need to get custom responses for each failure.  If firstName and last name fail length, how can I get custom length failure messages for both?  Right now I"m getting a custom response for only the first failure.  The docs don't say anything about this.  The only info on custom messages is to use findMessages():

"Getting messages as an array is fine, but sometimes you need to customize them in order to present them to the user. This is possible using the findMessages() method as well:"

**Comment by danfashiongps** [comment]
Does getFullMessage support custom messages?  If I pass it an array of custom messages just like we do for findMessages().  I don't get custom responses.   Perhaps I'm doing something wrong?

Ideally I'd like to have an array of all of the custom messages (ie getMessages).  But getMessages doesn't seem to take a parameter array of custom error messages either.

If I have an object that has a firstName and a lastName.  I setup a validator to check for both of those attributes to be present and I require their length to be 5.  How do I get custom error messages for both attributes if they both fail on length?

**Comment by danfashiongps** [comment]
Here's my validator (maybe this will help explain it better):

$this->validator =
            v::attribute(
                'firstName',
                v::stringType()
                    ->length(1, 32)
            )
                ->attribute(
                    'lastName',
                    v::stringType()
                        ->length(1, 32)
                )
...

if both fail length, how do i get a custom message for it?

**Comment by henriquemoody** [comment]
The `findMessage()` accepts a key-value array to customize messages, the keys may be the rule name or the name of the validator chain, according you your chain, since you're using `attribute()` rule the _name of the validator chain_ is the name of the attribute itself, so you're able to do this:

```php
//...
} catch (NestedValidationException $exception) {
    $messages = $exception->findMessages([
        'firstName' => 'Custom message for first name',
        'lastName' => 'Custom message for last name',
    ]);
}
```

I think this solves your problem, but feel free to reopen this issue any time. :panda_face:

**Comment by danfashiongps** [comment]
Sorry but that will not solve the problem I am describing.  Setting up a custom message for firstName and lastName does not allow me to see that it was a failure on the length check.   If firstName and lastName fail their corresponding length checks, I do not have a way to see a custom message saying: "{{name}} failed a length check" for both of them.

**Comment by danfashiongps** [comment]
Also i do no have permission to re-open this ticket.

**Comment by henriquemoody** [comment]
The only way I see to do this is by using a [translator](https://github.com/Respect/Validation/blob/master/docs/README.md#message-localization)

**Comment by danfashiongps** [comment]
For now I'm doing this to solve the problem

```
use Respect\Validation\Exceptions;

        Exceptions\LengthException::$defaultTemplates = [Exceptions\LengthException::MODE_DEFAULT => [
                Exceptions\LengthException::BOTH => 'custom message here',
                Exceptions\LengthException::LOWER => 'custom message here',
                Exceptions\LengthException::GREATER => 'custom message here',
            ],
            Exceptions\LengthException::MODE_NEGATIVE => [
                Exceptions\LengthException::BOTH => 'custom message here',
                Exceptions\LengthException::LOWER => 'custom message here',
                Exceptions\LengthException::GREATER => 'custom message here',
            ],
        ];
```

**Comment by pixelfriese** [comment]
+1 I have the same problem. It is not possible to set a nested array of arguments for the findMessages() function.

**Comment by Jossnaz** [comment]
+1

**Comment by kvipe** [comment]
In Respect Validation 1.1 this problem is still relevant

**Comment by zero-void** [comment]
You could do the following... Works well for my use case:
`try {
            $this->v::allOf(
                $this->v::contains('uf')->setName('uf'),
                $this->v::contains('uid')->setName('uid'),
                $this->v::contains('cant')->setName('cant')
            )->assert($queryParams);
        } catch (NestedValidationException $e) {
            $this->isValidQuery = false;
            $this->queryErrors = $e->findMessages([
                'uf' => 'URL must contain the query parameter {{name}}',
                'uid' => 'URL must contain the query parameter {{name}}',
                'cant' => 'URL must contain the query parameter {{name}}'
            ]);
        }`

**Comment by henriquemoody** [comment]
I'm closing issues that are too old, and I'm not really looking at them all. If this is still relevant, please comment here and I will reopen this issue.

Thanks for all your comments! 🐼
