### ISSUE TITLE
v::keySet() not working with superglobals?

### ISSUE THREAD

**Issue by GiacomoP** [Respect/Validation#612]
Hi all, I hope I'm not posting in the wrong place.

With the following code, I always get `false`.
```
v::keySet(
    v::key('id', v::notBlank())
)->validate($_COOKIE)
```

Same with $_SESSION. But if I `var_dump()` them I see they have the "id" set and it's not blank.

If I create an array like this
```
$array = array('id' => 'whatever');
```
The same rule returns `true`.

Am I doing something wrong with these special variables?

**Comment by GiacomoP** [comment]
keySet() validates all keys in the array, not just the one set. Just found this re-reading the documentation, sorry!

**Comment by henriquemoody** [comment]
Yes, you don't need to use `keySet()`, in your case, just `key()` is enough
