### ISSUE TITLE
Client-side Validation

### ISSUE THREAD

**Issue by dragon-driver** [Respect/Validation#622]
I just found this library and think you are doing a great job.
I have one suggestion though, which is something I will have to do for myself for my project (a hybrid app using jquery and php for server-side).

As you know, when performing validation, from a user perspective, it is best to be told of any mistakes before submitting the form, and so devs usually end up either writing or acquiring two validation libraries; one for the server-side and another for the client-side.

A nice and, I believe simple, feature would be having a script in your library which would fed via POST or GET what to check and return a response.
The input and output could than be JSON, making it platform independent and removes the need for another platform specific library, as one could utilise this library on the client-side as well as on the server-side, whatever the coding language may be.

**Comment by fr3dm4n** [comment]
A single point of validation is a good idea, but I think this is not the job of the Validation framework itself. This is the programmers job. But thats just my opinion.

Actually I did exactly this a few weeks ago. I send all changes in form elements via AJAX to the form url. The ValidatonController I wrote will look for an query param to either check a single delivered value (and will not check for missing values) or validate the whole request and continue with the business logic if everything is fine.

**Comment by batusa** [comment]
@dragon-driver Validation is a library meant for server-side validation. The only way to have data validated on client-side by Validation would be to send them by AJAX, although it can have its drawbacks (eg: many requests per input field, etc...). I also agree with @fr3dm4n that this work is a programmer's job.

**Comment by dragon-driver** [comment]
I see your point, but I do not prefer to do it that way. 
But fair enough, Each to his own.

**Comment by henriquemoody** [comment]
We've talked about that once, see #109 but I agree with @fr3dm4n and @batusa.

Also, from my POV, performing an AJAX request to validate data is totally unnecessary, since every request that accepts user's input _must_ validate data before doing something with it because you should _never_ trust that the data is already validated.

There are many ways to handle this on your application, doesn't matter if it's a web service or a web page. The whole point on Validation throwing exceptions then you use `assert()` and `check()` methods is to allow you use a try/catch statement to handle it as you want.

**Comment by thibaudcolas** [comment]
With this discussion and #109 in mind, is there a recommended approach to synchronising the validation rules defined with `Validation` in PHP with what a client-side validation engine would use?

I'm thinking of something like what https://github.com/Respect/Validation/issues/109#issue-10158078 suggests, where there would be a way to serialise validation rules so they can be provided to a JS validation that would translate them to its own engine's rules. For example:

- `v::numeric()` becomes `{ "type: "integer" }`, that can be used with a library supporting JSON Schema.
- `v::numeric()->positive()` becomes  `{ "type: "integer", "minimum":  0}`

I realise this wouldn't work well for all rules Validation supports at the moment – but I wonder if anyone else has explored that route.

**Comment by henriquemoody** [comment]
I'm closing issues that are too old, and I'm not really looking at them all. If this is still relevant, please comment here and I will reopen this issue.

Thanks for all your comments! 🐼
