### ISSUE TITLE
how to hidden the field name in return message 

### ISSUE THREAD

**Issue by mgckid** [Respect/Validation#625]
i'm a phper in China ,province HuBei , city WuHan ,I use Respect/Validation in my website to validate form data, when data validate failed return a error message, I custom the message like:

``` php
        $errorMessage = array(
            'notEmpty' => '{{name}} 不能为空',
            'intVal' => '{{name}} 必须为整数',
            'stringType' => '{{name}}必须为字符',
            'noWhitespace' => '{{name}}不能包含空字符'
        );
```

but I get the message like  'parent_id 不能为空' or   'parent_id必须为整数'. field name  in return message ,make user  misunderstand and expose our var name to cracker。I expect a result that I can  set filed name user friendly by my self to replace the form field name 。for  example  I submit data with filed name  
password and username ,I validate the data not empty ,when has a  Exception return message  '密码不能为空、用户名不能为空' not ‘password 不能为空、username 不能为空’。
 if has a method to do I expected ,can you tell me how to do this? thank you very much.

**Comment by batusa** [comment]
You can do it by using: [`setName($name)`](https://github.com/Respect/Validation/blob/master/docs/README.md#exception-types).

As the doc says: ["If you do not define a name it uses the input to replace this placeholder."](https://github.com/Respect/Validation/blob/master/docs/README.md#custom-messages).

**Comment by henriquemoody** [comment]
It's been a long time since there is no response on this one. I'm gonna close this one but feel free to send a new one if needed! 

I hope you found a resolve for your problem anyways! 🐼
