### ISSUE TITLE
[feature request] support validating GMP?

### ISSUE THREAD

**Issue by divinity76** [Respect/Validation#626]
can support for validating GMP objects/resources be added? for example

``` php
v::intVal()->between(gmp_init("100000000000000000000000000000000000"),gmp_init("200000000000000000000000000000000000"))->validate(gmp_init("100000000000000000000000000000000005")); // true
```

(beware, it was a "resource" in 5.5-, and an object as of 5.6+)

**Comment by henriquemoody** [comment]
I'm closing issues that are too old, and I'm not really looking at them all. If this is still relevant, please comment here and I will reopen this issue.

Thanks for reporting! 🐼
