### ISSUE TITLE
PHP7 and v::attribute

### ISSUE THREAD

**Issue by hmacube** [Respect/Validation#634]
Please run this code in PHP 7.0.1
```PHP
<?php
        $user = new \stdClass;
        $user->name = 'Alexandre';
        $user->birthdate = '1987-07-01';

        $userValidator = v::attribute('name', v::stringType()->length(1,32))
            ->attribute('birthdate', v::date()->age(18));

        var_dump($userValidator->validate($user));
```
After seconds The connection was reset

**Comment by henriquemoody** [comment]
Did you tried it on command-line, or a webserver? If a webserver, could you provide more information, like if you're using Nginx, Apache, PHP-FPM, operating system and such?

**Comment by hmacube** [comment]
After trying more I understand that it is not bug for Respect/Validation or PHP 7.0.1 , it is from XDebug
