### ISSUE TITLE
getName() for Rules wrapped on Option Rule return content instead of field name.

### ISSUE THREAD

**Issue by Axxon** [Respect/Validation#638]
Hello, i use validation exceptions to indicate  what's wrong on a custom class that try to fix inputs , but i observed that the getName() method for optionals fields didn't return a appropriate result (return content instead of field name). So i fixed that in the Attribute class, i repost here my work, i'm sorry cause i don't have any time to create tests for that (however i ran all Respect/Validation tests with my patch on, and it's work).

So on Respect\Validation\Rules\Attribute::__construct();

``` php
public function __construct($reference, Validatable $validator = null, $mandatory = true)
{
    if (!is_string($reference) || empty($reference)) {
        throw new ComponentException('Invalid attribute/property name');
    }

    if (! empty($validator) && method_exists($validator, 'getRules')) {
        $rulesArray     = $validator->getRules();
        $ruleFirstIndex = reset($rulesArray);

        if ($ruleFirstIndex instanceof \Respect\Validation\Rules\Optional) {
            $rules = $ruleFirstIndex->getValidatable()->getRules();
            foreach ($rules as $rule) {
                $rule->setName($reference);
            }
        }

        $validator->setName($reference);
    }

    parent::__construct($reference, $validator, $mandatory);
}
```

**Comment by henriquemoody** [comment]
I'm closing issues that are too old, and I'm not really looking at them all. If this is still relevant, please comment here and I will reopen this issue.

Thanks for reporting! 🐼
