### ISSUE TITLE
AbstractWrapper doesn't pass on setName calls to the wrapped Validatable

### ISSUE THREAD

**Issue by alnorth** [Respect/Validation#647]
When using something like `SubdivisionCode` `setName` calls aren't passed on to the particular class that's wrapped (e.g. `UsSubdivisionCode`). This results in the input value being used as the name in error messages.

I'm working on a PR for this and will add a fix with a test.

**Comment by alnorth** [comment]
Ignore the first commit (559d82c). b20bb93 fixes this issue.

**Comment by henriquemoody** [comment]
@alnorth, can you send a pull request against 1.0 branch?

**Comment by alnorth** [comment]
Will do. (Although your docs seemed to say that bugfixes should be submitted against 0.8).

**Comment by henriquemoody** [comment]
Hum... I will try to make it more clear on our documentation.

**Comment by alnorth** [comment]
It was "Pull requests for bug fixes must be based on the oldest supported version's branch" in the contributing doc plus Example 1 here: https://github.com/Respect/Validation/wiki/Release-Cycle-and-Support.

Pull request submitted as #648.

**Comment by henriquemoody** [comment]
Yes, it must be the _latest_ supported version which is 1.0.

**Comment by henriquemoody** [comment]
I'm sorry, you're right. But thanks any way!

**Comment by alnorth** [comment]
No problem :smile:
