### ISSUE TITLE
Using Validator In Service Locator Pattern

### ISSUE THREAD

**Issue by muratgozel** [Respect/Validation#654]
I'm using the validator by setting it in the service locator class like below:
```php
use Respect\Validation\Validator;
...
$serviceLocator->set( 'validate', new Validator() );
...
```
And getting the service as follows:
```php
class Example
{
    protected $validate;
    public function __construct( DI $service ) {
        $this->validate = $service->get('validate');
    }
    public function setIss( $iss ) {
        if( !$this->validate->email()->validate($iss) ) throw new Exception('Invalid Issuer.');
        $this->iss = $iss;
    }
    public function setScopes( $scope ) {
        if( !$this->validate->url()->validate($scope) ) throw new Exception('Invalid Scope Url.');
        $this->scopes = $scopes;
    }
}
```
There are two methods (email and url) as you can see. While the email validator works, the url validator returns always false. If i call url validator first, then email validator returns always false.

How can i deal with this situation? Am i doing something wrong in the pattern.

**Comment by henriquemoody** [comment]
Each `Validator` instance contains a chain and when you use `email()` and `url()` you're just adding new rules the that chain.

Fortunately there is a method `create()` that creates a new instance of `Validator` without any rule in the chain. So, to avoid changing the main chain:

```php
public function setIss( $iss ) {
    if( !$this->validate->create()->email()->validate($iss) ) throw new Exception('Invalid Issuer.');
    $this->iss = $iss;
}

public function setScopes( $scope ) {
    if( !$this->validate->create()->url()->validate($scope) ) throw new Exception('Invalid Scope Url.');
    $this->scopes = $scopes;
}
```
