### ISSUE TITLE
Missing functionality

### ISSUE THREAD

**Issue by SimTabi** [Respect/Validation#656]
Hi,

I think you missed something i am using the latest version. Seems like `languageCode() `is missing.

**Comment by batusa** [comment]
thanks for reporting that @SimTabi , indeed `LanguageCode` rule is not in the branch `1.0`.

**Comment by henriquemoody** [comment]
Actually that's not a but. This rule was introduced after the release of version 1.0, so it's only available on master that will be released in the next version on April 24th.
