### ISSUE TITLE
callback setTemplate works on assert but not with check #bug

### ISSUE THREAD

**Issue by ksvendsen** [Respect/Validation#662]
Hi 

I found a bug with setTemplate even after https://github.com/Respect/Validation/commit/3ed3114e58b2f516d53d8656efc47c41ce5d824b

This is from unit tests (`assert`)

```php
try { 
  v::callback('is_int')->setTemplate('{{name}} is not tasty')->assert('something'); 
} catch(NestedValidationException $e) { 
  print($e->getFullMessage()); 
}
```
returns: `"something" is not tasty - "something" must be valid`

Which is "good".

But then i do the same validation with `check`

```php
try { 
  v::callback('is_int')->setTemplate('{{name}} is not tasty')->check('something'); 
} catch(NestedValidationException $e) { 
  print($e->getFullMessage()); 
}
```
returns: `- "something" must be valid`

The custom template is gone.

**Comment by henriquemoody** [comment]
Thanks for reporting! 🐼 

It seems a bug but changing it's kind of a new feature (to not say BC breaking). I created #663 but this is going to be merged on master - after some feedback -, and the changed will be release on April 24th with the next version of Validation.
