### ISSUE TITLE
Phone validation with extension and parenthisis

### ISSUE THREAD

**Issue by GhaziTriki** [Respect/Validation#665]
Hello,

I am using Faker library to generated data used in unit tests, that data is validated against the the phone validator however the formats below are not marked as valid:

```
+87(0)2987404846 (parenthisis in the middle of the string)
or
379.620.4294x1673 (x for the extension)
```

Should those be marked as valid by Validation?

**Comment by batusa** [comment]
Hi @GhaziTriki ,

currently, the Phone Number rule doesn't have support to use the character "x" to delimiter an extension. I'm +1 for that.

Your first phone number is not marked as valid because it has "too many" digits (after the parentheses it should not have more than 9 digits). It'd be considered as valid with just `+87(0)298740484`.

Could you tell me where (country, place) this number format is accepted? Thanks!

**Comment by GhaziTriki** [comment]
Hi @batusa,

Looking at E.164 at sepcification https://www.itu.int/rec/T-REC-E.164-201011-I/en the max phone number length is 15. Starting from page 6. That phone number was generated by the Faker library, it looks like +87 is a satellite/gps number.

**Comment by AnrDaemon** [comment]
```php
    v::phone()
    ->assert("+7 (999) 999-99-99")
    ;
```
> "+7 (999) 999-99-99" must be a valid telephone number

It IS a valid phone number. Dashes are on par with spaces - it's an OWS (optional whitespace) character in phone numbers.

**Comment by henriquemoody** [comment]
I'm closing issues that are too old, and I'm not really looking at them all. If this is still relevant, please comment here and I will reopen this issue.

Thanks for reporting! 🐼

**Comment by AnrDaemon** [comment]
```php
use Respect\Validation\Validator as v;

foreach([
  "+7 (999) 999-99-99",
  "+7(999)999-99-99",
  "+7(999)999-9999",
] as $phone) {
  print "Valid phone number {$phone} validation " . ( v::phone()->validate($phone) ? "passed" : "failed") . "\n";
}
```

```
Valid phone number +7 (999) 999-99-99 validation failed
Valid phone number +7(999)999-99-99 validation failed
Valid phone number +7(999)999-9999 validation passed
```

Still an issue.

**Comment by henriquemoody** [comment]
Version 2.3 was release about a week ago. This issue should be fixed now!
