### ISSUE TITLE
conditional validation

### ISSUE THREAD

**Issue by mhndev** [Respect/Validation#680]
consider I have 2 fields and I want my second field to be one of "1", "-1"
if my first field is "X"
and also I want my second field to be "1" if my first field is "Y"
does respect already have this kind of rule??

**Comment by henriquemoody** [comment]
You should try [When](http://respect.github.io/Validation/docs/when.html) rule.

**Comment by mhndev** [comment]
thanks for quick reply.
consider that I have 2 fields and my second field's validation is dependent on first field
so for example I want to say if first field is equal to "some string" then second field just can be 2 or 3 .

as I understood when rule is just used on one field not multiple fields.

**Comment by henriquemoody** [comment]
I should be something like this:

```php
v::when(
    v::key('first field', v::equals('some string')),
    v::key('second field', v::in([2, 3]))
);
```

**Comment by mhndev** [comment]
this is my validation code and it doesn't work.

```          
  v::when(
                v::key('type', v::equals('place')),
                v::key('value', v::equals('1')),
                v::key('value', v::oneOf(
                    v::equals('1'),
                    v::equals('-1'),
                    v::equals('+1')
                ))
            );
```

**Comment by henriquemoody** [comment]
What data are you using? Can you give me some samples?

**Comment by mhndev** [comment]
```php
$data = ['type'=>'place',value=>'1', 'id'=>2];
$data = ['type'=>'comment',value=>'-1', 'id'=>2];
```

when $data['type'] equals to place I want value to be just "1"
and when $data['type'] equals to comment I want value to be "1" or "-1" or "+1"

**Comment by batusa** [comment]
hi @mhndev ,

from the code you posted, it worked for me:

```php
$data = ['type' => 'place', 'value' => '1', 'id' => 2];

v::when(
        v::key('type', v::equals('place')),
        v::key('value', v::equals('1')),
        v::key('value', v::oneOf(
            v::equals('1'),
            v::equals('-1'),
            v::equals('+1')
        ))
    )->validate($data);
```

the code above returns `true`, if I try to change the value of `value`, it returns `false`.

let us know if you have solved this issue. thanks!

**Comment by henriquemoody** [comment]
It's been a long time since there is no response on this one. I'm gonna close this one but feel free to send a new one if needed! 

I hope you found a resolve for your problem anyways! 🐼
