### ISSUE TITLE
Email validator stopped working due to egulias/email-validator's interface update

### ISSUE THREAD

**Issue by redstrike** [Respect/Validation#685]
As suggested, I am using egulias/email-validator to enforce RFC-strict mode. But Validation's Email Validator is stop working after the interface update of egulias/email-validator. I wonder should we update our code, or stick with the old version?

**Comment by lode** [comment]
Any news on this? It would be great if the email validation gets fixed.

**Comment by lode** [comment]
Sorry, nevermind. The old version of egulias/email-validator still works fine. When requiring using `composer require egulias/email-validator "^1"` or something everything runs smooth.
