### ISSUE TITLE
Cannot use 'String' as class name as it is reserved

### ISSUE THREAD

**Issue by notflip** [Respect/Validation#686]
I see you're using the word String as a class name. I think this is deprecated since PHP7? 

> respect/validation/library/Rules/String.php

``` <?php
namespace Respect\Validation\Rules;

class String extends AbstractRule
{
    public function validate($input)
    {
        return is_string($input);
    }
}
```

**Comment by batusa** [comment]
hi @notflip 

what library's version are you using?

we've renamed it in order to be compatible with php7 since the version `1.0`.

**Comment by notflip** [comment]
I noticed I was using an outdated version. My bad!
