### ISSUE TITLE
Re-using a rule, with additional conditions

### ISSUE THREAD

**Issue by nisbeti** [Respect/Validation#687]
I define a rule `$username = v::alnum('.-_@')->noWhitespace()->length(3, 255);` so that I can re-use it anywhere. I then want to use this `$username` rule as the base rule, and add a new condition:
`$newUsername = $username->->uniqueUserField('username');` 
but, this then modifies the underlying $username field.
Is it possible to create copies of base rules, which are not changed by adding additional conditions?

**Comment by henriquemoody** [comment]
You can clone the current rule:

```php
$newUsername = clone $username;
$newUsername->...
```
