### ISSUE TITLE
Ignore first key / array level and validate second level.

### ISSUE THREAD

**Issue by mscreenie** [Respect/Validation#690]
Is it possible to ignore the first level of the nested array and validate against the second? Like this

```
 [*][address]
```
```
*.address
```
```
contacts[*].address
```

Thanks.

**Comment by alganet** [comment]
Try this:

```
use Respect\Validation\Validator as v;
use Respect\Validation\Exceptions\NestedValidationException;

$data = [
    'field1' => 1234,
    'field2' => ['subfield4' => 1234],
    'field3' => ['subfield4' => '1234']
];

$validator = v::each(
		v::key('subfield4', v::stringType(), false)
	);

try {
    $validator->assert($data);
} catch (NestedValidationException $ex) {
    var_dump(array_filter($ex->findMessages([
        'each.subfield4.stringType'
    ])));
}
```

The third parameter for `key` define if it is optional or not, you might omit it to check if all items pass the rule, or only the keys if they are present.

**Comment by henriquemoody** [comment]
If @alganet's answer is not enough feel free to reopen this issue @mscreenie. :)

**Comment by mscreenie** [comment]
If it helps anyone, nested keys work too with ignoring first level or any level I believe:

```
$input = [
	'contact1' => [
		'name' => 'wd',
		'daymark' => 'ffesfewf2232313123212',
		'building' => [
			'enable' => 'd',
			'blank' => 'ffesfewf2232313123212',
			'powerdown' => '5',
			'powerup' => 'wdwdwf'
		]
	],
	'contact2' => [
		'name' => 'wd',
		'daymark' => 'ffesfewf2232313123212',
		'building' => [
			'enable' => 'd',
			'blank' => 'ffesfewf2232313123212',
			'powerdown' => '5',
			'powerup' => 'wdwdwf'
		]
	]
];
```

```
	v::create()
		->each(
			v::key('name', v::length(1, 50)->notEmpty())
				->key('daymark', v::length(1, 50)->notEmpty())
				->key(
					'building',
					v::create()
						->key('enable', v::length(2, 50)->notEmpty())
						->key('time', v::length(2, 50)->notEmpty())
						->key('powerdown', v::length(2, 50)->notEmpty())
						->key('powerup', v::length(2, 50)->notEmpty())
				)

		)->assert($input);

```
But you may have trouble accessing a specific messaage level 

```
	print_r(array_filter($exception->findMessages([
		'each.name' => 'Center name',
		'each.daymark' => 'Center time',
	])));
```

**Comment by henriquemoody** [comment]
Thanks for the appreciation @mscreenie! 😄 

Keep in mind that it's going to get the message of the rule that fails, so if the exception it LengthException there is no `{{keyName}}` on it, although we set the `{{name}}` as the same of its parent, so by doing:

```php
print_r(array_filter($exception->findMessages([
    'each.name' => '{{name}} is invalid etc',
    'each.daymark' => 'Center time',
])));
```

You might get:

```
Array
(
    [each_name] => name is invalid etc
)
```

But unfortunately you can't know the name of the parent because the names must be defined to be shown.

PS.: After version 1.0 the use of `notEmpty()` is not necessary when your change covers it, in your case `length(1...)`.

**Comment by mscreenie** [comment]
How would you access building level errors?

    print_r(array_filter($exception->findMessages([
        'each.name' => '{{keyName}} name is invalid etc',
        'each.daymark' => 'Center time',
        'each.building.enable' => 'Building enabled',
        'each.building.powerdown' => 'Building power down state',
    ])));

I get error 

> <br />
> <b>Fatal error</b>:  Uncaught Error: Call to a member function setTemplate() on null in /var/www/_library/Respect/vendor/respect/validation/library/Exceptions/NestedValidationException.php:84
> Stack trace:
> #0 /var/www/configure/callback.php(410): Respect\Validation\Exceptions\NestedValidationException-&gt;findMessages(Array)
> #1 {main}
>   thrown in <b>/var/www/_library/Respect/vendor/respect/validation/library/Exceptions/NestedValidationException.php</b> on line <b>84</b><br />

**Comment by henriquemoody** [comment]
@mscreenie Can you send me the input, the chain and the version you're using there then I can reproduce the same error?

**Comment by mscreenie** [comment]
Yes. 

I am using the latest version. Here is the full file and differences in output from 1.1.2 and latest. 

I am excluding the key name entirely, something which is possible in a HTML form if a radio button / checkbox is not clicked.
 

`
require_once('../_library/Respect/vendor/autoload.php');

use Respect\Validation\Exceptions\NestedValidationException;
use Respect\Validation\Validator as v;

$input = [
	'contact1' => [
		'daymark' => 'ffesfewf2232313123212',
		'building' => [
			'enable' => 'd',
			'blank' => 'ffesfewf2232313123212',
			'powerdown' => '5',
			'powerup' => 'wdwdwf'
		]
	],
	'contact2' => [
		'name' => 'wd',
		'daymark' => 'ffesfewf2232313123212',
		'building' => [
			'enable' => '1',
			'blank' => '1',
			'powerdown' => '1',
			'powerup' => '1'
		]
	]
];

try {

	v::create()
		->each(
			v::key('name', v::length(1, 50))
				->key('daymark', v::length(1, 50))
				->key(
					'building',
					v::create()
						->key('enable', v::length(2, 50))
						->key('time', v::length(2, 50))
						->key('powerdown', v::length(2, 50))
						->key('powerup', v::length(2, 50))
				)
		)->assert($input);

} catch (NestedValidationException $exception) {

	print_r(array_filter($exception->findMessages([
		'each.name' => 'Center name',
		'each.building.enable' => 'Center time',
		'each.building.powerdown' => 'Center time'
	])));

}`

Output with version "1.1.2"
`Array ( [each_name] => Center name [each_building_enable] => Center time [each_building_powerdown] => Center time )`

With latest
`
Fatal error: Uncaught Error: Call to a member function setTemplate() on null in /var/www/_library/Respect/vendor/respect/validation/library/Exceptions/NestedValidationException.php:84 Stack trace: #0 /var/www/configure/dwd.php(49): Respect\Validation\Exceptions\NestedValidationException->findMessages(Array) #1 {main} thrown in /var/www/_library/Respect/vendor/respect/validation/library/Exceptions/NestedValidationException.php on line 84`

**Comment by mscreenie** [comment]
Looks like it is only when a field / key is missing, the error is produced.

**Comment by henriquemoody** [comment]
@mscreenie, the problem you reported was fixed, although I extremely recommend you to not use the `dev-master` version on production.

**Comment by mscreenie** [comment]
Thanks. I confirm it working. 

Not a major issue but using keyNested inside a key or each does not return the correct nested messages structure.

I have created a working example - The data and rules are a little rough.

```
require_once('../_library/Respect/vendor/autoload.php');

use Respect\Validation\Exceptions\NestedValidationException;
use Respect\Validation\Validator as v;

$input = [
	'contact1' => [
		'daymark' => 'ffesfewf2232313123212',
		'building' => [
			'enable' => 'd',
			'blank' => 'ffesfewf2232313123212',
			'powerdown' => '5',
			'powerup' => 'wdwdwf'
		]
	],
	'contact2' => [
		'name' => 'wd',
		'daymark' => 'ffesfewf2232313123212',
		'building' => [
			'enable' => '1',
			'meta' => [
				'restricted' => true,
				'gov_access' => 'level7',
				'gov_group' => '07'
			],
			'powerdown' => '1',
			'powerup' => '1'
		]
	]
];

try {

	v::create()
		->each(
			v::key('name', v::length(1, 50))
				->key('daymark', v::length(1, 50))
				->key(
					'building',
					v::create()
						->key('enable', v::length(2, 50))
						->key('time', v::length(2, 50))
						->key('powerdown', v::length(2, 50))
						->key('powerup', v::length(2, 50))
						->keyNested('meta.restricted', v::length(1, 20))
						->keyNested('meta.gov_access', v::length(1, 20))
						->keyNested('meta.gov_group', v::length(1, 20)->intVal())
				)
		)->assert($input);

} catch (NestedValidationException $exception) {

	// Does not work - Returns empty array
	print_r(array_filter($exception->findMessages([
		'each.name' => 'Center name',
		'each.building.enable' => 'Center time',
		'each.building.meta.gov_access' => 'gov_access'
		'each.building.meta.gov_group' => 'gov_group'
	])));

	// Works but does not follow nested array structure
	print_r(array_filter($exception->findMessages([
		'each.name' => 'Center name',
		'each.building.enable' => 'Center time',
		'meta.gov_access' => 'gov_access'
		'meta.gov_group' => 'gov_group'
	])));

}
```
