### ISSUE TITLE
Check array key for any value in an array?

### ISSUE THREAD

**Issue by JamesHealdUK** [Respect/Validation#700]
I have a dropdown list that I want to validate, theres 3 values that can be selected and I want to make sure I can only use those specific values.

However, I want to do it inline with my `Validator::Key()` checks like so:

```
$userValidator = Validator::key("gender", Validator::stringType()->equals(["male", "female"])->setName("Gender"))
    ->key("name", Validator::stringType()->length(2, 50)->setName("Name"))
```

I have tried `equals` but it doesnt work with arrays. Is what Im trying to do possible?

**Comment by henriquemoody** [comment]
You should use [in](http://respect.github.io/Validation/docs/in.html) instead.
