### ISSUE TITLE
[Question] Inject a model to a custom rule?

### ISSUE THREAD

**Issue by ArneAnka** [Respect/Validation#701]
Hi!

I [asked a question](http://discourse.slimframework.com/t/use-this-with-rules-for-validation/486/4?u=johan) on the slim support forum, on how to inject a model into a Respect/Validation rule.

Im thrown `Notice: Undefined property: App\Validation\Rules\EmailAvailable::$User in /app/Validation/Rules/EmailAvailable.php on line 11` and that is this [line](https://github.com/ArneAnka/slim-test/blob/master/app/Validation/Rules/EmailAvailable.php#L11) (ps yes that is the repo I'm having troubles with).

So my question is how do i inject respect with the model form the container? 

Validation is injected in [index.php](https://github.com/ArneAnka/slim-test/blob/master/public/index.php#L55), and everything works perfect, except for [custom rules](https://github.com/ArneAnka/slim-test/blob/master/app/Controllers/AuthController.php#L89)...

Thanks in advance!

**Comment by teseo** [comment]
Did you get any progress on this?

**Comment by henriquemoody** [comment]
This is not a Respect problem, neither a Slim problem, this is a OOP problem.

That's your rule there:

```php
namespace App\Validation\Rules;
use Respect\Validation\Rules\AbstractRule;
class EmailAvailable extends AbstractRule
{
    public function validate($input)
    {
        return $this->UserModel->doesEmailAlreadyExist($input);
    }
}
```

The `$this->UserModel` is not defined in any place on this class and it needs to be injected somehow:

```
namespace App\Validation\Rules;

use App\Models\UserModel;
use Respect\Validation\Rules\AbstractRule;

class EmailAvailable extends AbstractRule
{
    private $userModel;

    public function __construct(UserModel $userModel)
    {
        $this->userModel = $userModel;
    }

    public function validate($input)
    {
        return $this->userModel->doesEmailAlreadyExist($input);
    }
}
```

So, everytime you use this rule you have to inject that on the constructor, like:

```php
$validator = new EmailAvailable($this->UserModel);
$validator->validate($input);
```

Or, if you add your custom namespace:

```
v::emailAvailable($this->UserModel)->validate($input);
```
