### ISSUE TITLE
using v::length() when input could be string or int

### ISSUE THREAD

**Issue by FoxxMD** [Respect/Validation#703]
I have a rule that looks like this

``` php
v::attribute('sku', v::notEmpty()->length(1, 100))
```

`sku` may be a string or a number. When it is a number the rule is not validating if the number > 100. Is there some way I can cast `sku` to a string before validating or some use of oneOf() that might ignore numbers?

**Comment by henriquemoody** [comment]
I'm closing issues that are too old, and I'm not really looking at them all. If this is still relevant, please comment here and I will reopen this issue.

Thanks for all your comments! 🐼
