### ISSUE TITLE
How can I give user  error message I want to give

### ISSUE THREAD

**Issue by Justin0983** [Respect/Validation#705]
Hi,there.I need a favor.
I don't use default error message when I validate some data.Just give user error message I specified.

$userValidator = v::attribute('name', v::stringType()->length(1,32))
                  ->attribute('birthdate', v::date()->age(18));

$userValidator->validate($user); 

like code above,how to make it happen?Such as validate 'name',give user a kind of message that 'name you input is invalid' I  specified.

Thank you for your help!

**Comment by seitbekir** [comment]
It is really good question.

What about make something like in popular NodeJS validators.

like
```php
$field = v::numberic("the value must be null");
```
Or
```php
$field = v::numberic(new ValidationError("the value must be null"));
```

Last is not looks pretty, but it more useful;

**Comment by henriquemoody** [comment]
You can specify your own messages with `findMessages()`, see http://respect.github.io/Validation/docs/#getting-messages-as-an-array-by-name

If my answer is not enough, feel free to reopen this issue or create a new one any time.

🐼
