### ISSUE TITLE
How can I translate error message of English to another Language 

### ISSUE THREAD

**Issue by Justin0983** [Respect/Validation#706]
Hi,all.How can I translate make error message of English to Chinese when It's fail if validate one data like 'username'.Does Validation have language packs?
Thank you for your help.

**Comment by auburus** [comment]
Hi!

You have a detailed explanation about how translation works [here](https://github.com/Respect/Validation/tree/master/docs#message-localization).

**Comment by henriquemoody** [comment]
@Justin0983, unfortunately  we don't have language packs...

If @auburus's answer is not enough, feel free to reopen this issue or create a new one any time.

🐼
