### ISSUE TITLE
Validator find failure

### ISSUE THREAD

**Issue by pquerner** [Respect/Validation#710]
Having checks like these:

```
v::arrayVal()->each(v::boolType()->equals(TRUE))->validate($_allVals);
```

Either reveal true or false on success.

However, is there a way to find out which, if any, element failed the validation process?
Or do I have to do this myself after checking the return value of said validation process.

Thanks!

**Comment by henriquemoody** [comment]
You can have a detailed information using `assert()`, or `check()`. Doesn't it fit your needs?

**Comment by henriquemoody** [comment]
If my answer is not enough, feel free to reopen this issue or create a new one any time.

🐼
