### ISSUE TITLE
Please Help me => Class Validator not found!

### ISSUE THREAD

**Issue by pedram64** [Respect/Validation#715]
I'm new in composer but I could get vendor, `composer.lock` and `composer.json` from cmd then I paste them to my project without Validation_Master folder.
My project Path: `C:\wamp64\www\php Projects\project 1\(here there are test.php and vendor, composer.lock and composer.json)`
Validation_Master folder path: `C:\wamp64\www\php Projects\Validation_Master`
My Code is:
```
<?php
require "vendor/autoload.php";
use Respect\Validation\Validator as v;
$number = 123;
v::numeric()->validate($number);
?>
```
But Give Me This Error :
Fatal error: Class 'Respect\Validation\Validator' not found in C:\wamp64\www\php Projects\project 1\test.php
--------------------------------------------------------
What did I do?!!?
copy Validation_Master folder to the path of test.php ==> (Failed )
copy Vendor folder to the path of Validation_Master folder and required from there ==> (Failed )
Manipulate namespace a lot and add namespace Respect\Validation to the code ==> (Failed )
What's The PROBLEM ????
How Can I use Your Library ????? Please Answer me basically(I read docs before but didn't help)
I appreciate and sorry that I've written a lot :+1:

**Comment by batusa** [comment]
Try to run `composer dump-autoload`

Reference: https://getcomposer.org/doc/03-cli.md#dump-autoload

**Comment by pedram64** [comment]
with the former code and the `composer dump-autoload` nothing happened and still get error.
I really don't understand what's wrong??!

**Comment by pedram64** [comment]
SOLVED: I used the composer.json that is in the Validation_Master Folder while I must create my own composer.json.
that was stupid LOL
