### ISSUE TITLE
Please Help! `Fatal error: Uncaught Error: Call to undefined function Respect\Validation\Rules\mb_strlen() `

### ISSUE THREAD

**Issue by CasperHK** [Respect/Validation#717]
When I run the following method, I got error `Fatal error: Uncaught Error: Call to undefined function Respect\Validation\Rules\mb_strlen() `.

``` php
<?php
    require_once("./vendor/autoload.php");
    use Respect\Validation\Validator as v;

    class InputValidator {
        public static function isUsernameCorrect($username) {
            $usernameValidator = v::alnum()->noWhitespace()->length(1, 15);
            $result = $usernameValidator->validate($username);
            return $result;
        }
    }
?>
```

I called it in this way:

``` php
var_dump(InputValidator::isUsernameCorrect("casper1234"));
```

### Error Message

> Fatal error: Uncaught Error: Call to undefined function Respect\Validation\Rules\mb_strlen() in /var/www/html/PHPSimVlidator/vendor/respect/validation/library/Rules/Length.php:57 Stack trace: #0 /var/www/html/PHPSimVlidator/vendor/respect/validation/library/Rules/Length.php(49): Respect\Validation\Rules\Length->extractLength('casper1234') #1 /var/www/html/PHPSimVlidator/vendor/respect/validation/library/Rules/AllOf.php(45): Respect\Validation\Rules\Length->validate('casper1234') #2 /var/www/html/PHPSimVlidator/InputValidator.php(17): Respect\Validation\Rules\AllOf->validate('casper1234') #3 /var/www/html/PHPSimVlidator/InputValidator.php(102): InputValidator::isUsernameCorrect('casper1234') #4 {main} thrown in /var/www/html/PHPSimVlidator/vendor/respect/validation/library/Rules/Length.php on line 57

How to solve it?

**Comment by auburus** [comment]
It means that you are missing the required extension `mbstring`. I think it's enabled by default on some Linux distributions, but I'm not sure. 

Please, use a version of PHP that includes this extension (or [install it](http://php.net/manual/en/mbstring.installation.php) yourself :smile: )

**Comment by CasperHK** [comment]
I am using Ubuntu 16.04 with php7.0 running on the service apache2

| Key     | Value              |
|:---------|:-------------------|
| OS      | Ubuntu 16.04 |
| PHP    | php7.0           |
| Server | apache2        |

**Comment by auburus** [comment]
Come on, I've searched `install php mbstring ubuntu` on google, and [this answer](http://stackoverflow.com/a/37011840) was right in the first page...

**Comment by CasperHK** [comment]
Oh~ I'm so stupid. 😥

**Comment by auburus** [comment]
Don't worry at all, we all start at some point :blush: 

Mark the issue as closed if you solve it, please
