### ISSUE TITLE
Custom Rules Documentation

### ISSUE THREAD

**Issue by dlee3** [Respect/Validation#722]
I recently created a custom rule for a project I was working on and noticed that the documentation for creating custom rules is not quite complete. I will be creating an updated version and sending a pull request later today.

**Comment by StarveTheEgo** [comment]
Where is it?

**Comment by henriquemoody** [comment]
I'm closing issues that are too old, and I'm not really looking at them all. If this is still relevant, please comment here and I will reopen this issue.

Thanks for all your comments! 🐼
