### ISSUE TITLE
Any new updates on recent KeyNested and SetName bugs?

### ISSUE THREAD

**Issue by mscreenie** [Respect/Validation#724]
Hi 

I just wanted to bump this and ask if there is any plans to fix these bugs by current maintainers. Apologies for being persistent (I know its free software and support is free), the bugs are affecting two important functions.  @batusa  @henriquemoody @alganet

Issues related:
https://github.com/Respect/Validation/issues/719
https://github.com/Respect/Validation/issues/620
https://github.com/Respect/Validation/issues/689

I'd like to know because I used this framework in two of my projects and need to decide whether to remove Respect and find alternatives, the bugs were reported 3 months ago. Thanks and all the best.

**Comment by henriquemoody** [comment]
Those bugs were finally fixed on versions [1.0.11](https://packagist.org/packages/respect/validation#1.0.11) and [1.1.6](https://packagist.org/packages/respect/validation#1.1.6) by #675.

I'm very sorry about my delay (I talked about that already https://github.com/Respect/Validation/issues/620#issuecomment-237474435).

Thanks for reporting! :panda_face:
