### ISSUE TITLE
keyNested Validator data type check should be JIT

### ISSUE THREAD

**Issue by CameronHall** [Respect/Validation#727]
Currently, the keyNested validator determines the applicable getReference function by checking the data type of the variable that you're checking against. 

```php
error_reporting(-1);

use Respect\Validation\Validator as v;

$work = new stdClass();
$work->number = "+61.(03) 4546 5498";
$work->countryCode = 61;
$work->primary = true;

$personal = new stdClass();
$personal->number = "+61.0406 464 890";
$personal->country = 61;
$personal->primary = false;

$phoneNumbers = new stdClass();
$phoneNumbers->personal = $personal;
$phoneNumbers->work = $work;

$validateThis = ['phoneNumbers' => $phoneNumbers];

v::keyNested('phoneNumbers.personal.country', v::intType(), false)
    ->keyNested('phoneNumbers.personal.number', v::phone(), false)
    ->keyNested('phoneNumbers.personal.primary', v::boolType(), false)
    ->keyNested('phoneNumbers.work.country', v::intType(), false)
    ->keyNested('phoneNumbers.work.number', v::phone(), false)
    ->keyNested('phoneNumbers.work.primary', v::boolType(), false)
    ->check($validateThis);
```

The above example will encounter a 'Fatal Error' with the reason of "Cannot use object of type stdClass as array".

This is because `$validateThis` is an array and, the keyNested validator selects the correct getReference function based upon the data type of `$validateThis`. Ideally, the check would be JIT and the data type check would be done on the second last key in the validation reference. Meaning, we'd be checking the data type of `phoneNumbers->work`.

If it is agreed that it should be done this way then I'm happy to create the PR :)

**Comment by henriquemoody** [comment]
Fixed on versions 1.0.10 and 1.1.5.

Thanks for reporting! 🐼
