### ISSUE TITLE
Image Validatos tells a class is missing

### ISSUE THREAD

**Issue by damanzano** [Respect/Validation#737]
class 'finfo' not found /respect/validation/library/Rules/Image.php on line 23

**Comment by prisis** [comment]
You need to install the fileinfo extension for php.

**Comment by henriquemoody** [comment]
The documentation even says:
> This rule relies on [fileinfo](http://php.net/fileinfo) PHP extension.

http://respect.github.io/Validation/docs/image.html

I'm closing this issue, since it's not a issue, but feel free to comment any time. 

🐼
