### ISSUE TITLE
Numeric class considered deprecated in PHP7

### ISSUE THREAD

**Issue by cwalsh** [Respect/Validation#740]
According to https://secure.php.net/manual/en/migration70.incompatible.php#migration70.incompatible.other.classes `Numeric` should be considered deprecated as a class name. It doesn't cause an error in PHP7 yet, unlike `Float` etc. but it might be worth changing this sooner rather than later.

In the comments for https://github.com/Respect/Validation/issues/362 it was suggested that among the other PHP7 changes, Numeric be renamed NumericValue or similar. Was this just missed or ignored as not significant?

**Comment by bacheson** [comment]
PHP Fatal error:  Cannot use 'Int' as class name as it is reserved in .../respect/validation/library/Rules/Int.php on line 4"

**Comment by henriquemoody** [comment]
Thanks for reporting, @cwalsh! It was really missed! 😞 I will check all of then again.

@bacheson, please upgrade the version of the library, then you're not going to have this problem.

**Comment by cwalsh** [comment]
Thank you, @henriquemoody!
