### ISSUE TITLE
Argument 2 passed to Egulias\EmailValidator\EmailValidator::isValid() must be an instance of Egulias\EmailValidator\Validation\EmailValidation

### ISSUE THREAD

**Issue by innobrig** [Respect/Validation#742]
I am using the following code to attempt to validate an email address:

    if (!Validator::email()->validate($email)) {
            // do something here
     }

and I'm getting the following error: 

>  Argument 2 passed to Egulias\EmailValidator\EmailValidator::isValid() must be an instance of Egulias\EmailValidator\Validation\EmailValidation, none given, called in /var/www/html/BoostCMS/vendor/respect/validation/library/Rules/Email.php on line 37 and defined

I have the following entry in my composer.json

    "egulias/email-validator": "^2.1"

and the files are in place under my /vendor directory.

Am I doing something wrong or is this a bug?

**Comment by souzace** [comment]
I have some problem, so.. while Respect don't fix the issue, i changed my composer of "egulias/email-validator": "^2.1" to "egulias/email-validator": "~2.1" make a composer update and followed the instructions on egulias github profile https://github.com/egulias/EmailValidator
`use Egulias\EmailValidator\EmailValidator;
use Egulias\EmailValidator\Validation\RFCValidation;

$validator = new EmailValidator();
$validator->isValid("example@example.com", new RFCValidation());
`

**Comment by innobrig** [comment]
Thanks for your suggestion, your workaround is just what I needed.

**Comment by souzace** [comment]
Your welcome brother!

**Comment by henriquemoody** [comment]
I'm sorry by my delay. This was fixed by #750.

The fix is available on versions 1.0.15 and 1.1.10.

Thanks for reporting! 🐼
