### ISSUE TITLE
V::regex chokes on non-strings

### ISSUE THREAD

**Issue by dvv** [Respect/Validation#747]
Hi!

This https://github.com/Respect/Validation/blob/master/library/Rules/Regex.php#L25 is not guarded against input being, say, an array, and causes critical error instead of validation error.

Neither
```php
V::key("foo", V::stringType()->regex('/^FOO+$/u'))
```
nor
```php
V::key("foo", V::regex('/^FOO+$/u')->stringType())
```
does not ensure input is string prior to checking against regex.

Is this intended? If yes, how to cope with the issue without subclassing Regex/RegexException?

TIA,
--Vladimir

**Comment by henriquemoody** [comment]
This was fixed by #749.

The fix is available on versions 1.0.15 and 1.1.10.

Thanks for reporting! 🐼
