### ISSUE TITLE
alnum() validates properly, but incorrect error

### ISSUE THREAD

**Issue by sbshara** [Respect/Validation#757]
Dears,

When using alnum, it validates as required (a-z, A-Z, 0-9) but when something is wrong, it's giving a misleading error (field must contain only letters (a-z) and digits (0-9).

Can you please add the (A-Z) to the error.

Thank you.

**Comment by williamespindola** [comment]
I think the error messages covers the simples functionality, but you can change it as you wish, see how to replace error messages https://github.com/Respect/Validation/blob/master/docs/README.md#custom-messages

**Comment by henriquemoody** [comment]
What would make more sense for a regex pattern match, but for Alnum rule it's just indicative.

Thanks for reporting! 🐼
