### ISSUE TITLE
Validating indexed subarrays?

### ISSUE THREAD

**Issue by codmpm** [Respect/Validation#759]
Hi guys,

Sorry for crossposting, but I think this is a more appropriate place...
http://stackoverflow.com/questions/40511540/validating-sub-arrays-with-respect-validation

I've used [Respect/Validation](https://github.com/Respect/Validation) successfully for my general concern.

But now I'm validating some form Input where the user can check multiple checkboxes and the data is send with an array.
The form looks something like this:

    <form method="post" action="">
        <input type="text" name="firstname">
        <input type="text" name="lastname">
    
        <input type="checkbox" name="options[]" value="1">
        <input type="checkbox" name="options[]" value="2">
        <input type="checkbox" name="options[]" value="3">
    
        <button type="submit">Send</button>
    </form>

So, my post-data will look like this:

    Array
    (
        [firstname] => Peter
        [lastname] => Parker
        [options] => Array
            (
                [0] => 1
                [1] => 3
            )
    )

I've build a validation rule which works: 

    <?php
    //used in class, so "use Respect\Validation\Validator AS v;"
    
    $validReq = v::create()
        ->key('firstname', v::stringType()->length(1, 32))
        ->key('lastname', v::stringType()->length(1, 32))
        ->key('options', v::optional(v::arrayType()))
        ->setName('valid request');

My question now is, how do I validate the array `options` with (e.g.) `v::intVal()`?

Maybe I've just oversaw how to accomplish this. Thank you for your time.

Cheers,
Patrik

**Comment by alganet** [comment]
Maybe the [Each](http://respect.github.io/Validation/docs/each.html) validator works best for this case. Something like `->key('options', v::optional(v::arrayType()->each(v::intVal())))`.

**Comment by codmpm** [comment]
You sir, are my hero. 
This is far too simple if I had not overread `each()`...

Cheers!

**Comment by Jossnaz** [comment]
btw how to request at least say, 3 check boxes to be checked? e.g. at least 3 values in the array
