### ISSUE TITLE
Unwanted additional error message in some cases

### ISSUE THREAD

**Issue by shivenigma** [Respect/Validation#760]
This is a great package, I am using it on my second project now. I like everything but in some cases, it returns a not so meaningful error message along with the validation errors.
```
$authValid = Valid::key('email', Valid::email())
                ->key('password', Valid::stringType()->notEmpty()->length(8, 25));
```
By using the above rules I am getting the following error messages

> "email must be valid email",
> "These rules must pass for password",
> "password must be a string",
> "password must have a length between 8 and 25"

In the above array the second message doesn't convey any meaning for me, at least for my requirement. Can I remove that generic message and only have the other messages by default?

**Comment by williamespindola** [comment]
You can try replace the messages, see docs https://github.com/Respect/Validation/blob/master/docs/README.md#informative-exceptions

**Comment by shivenigma** [comment]
I worked around using replacing messages
