### ISSUE TITLE
Using reflection to resolve rule classes

### ISSUE THREAD

**Issue by bradynpoulsen** [Respect/Validation#767]
I was just looking through the `Factory::rule` method and noticed that it uses `ReflectionClass` as its approach to check that it's a valid rule.

Is there a reason why ReflectionClass was used instead of `is_subclass_of` and `new {$class}`?
 * `is_subclass_of` has been available since PHP 4

**Comment by bradynpoulsen** [comment]
Here is a benchmark results (and script) I performed to verify that `is_subclass_of` would be faster than Reflection.
```
Beginning benchmark with 100,000,000 samples against Respect\Validation\Rules\AllOf
Beginning Reflection tests...
Beginning Functional tests...

Used a sample size of 100,000,000 subclass checks and creations
Reflection took 154.92484688759
Functional took 130.72710704803
Difference 24.197739839554
```
[benchmark.php.txt](https://github.com/Respect/Validation/files/629788/benchmark.php.txt)

**Comment by henriquemoody** [comment]
The reflection is necessary to check if the object `isInstantiable()`, that's already done for WIP version 2.0.

However, thanks for reporting! 🐼
