### ISSUE TITLE
Nested Validation // Ideas / Questions

### ISSUE THREAD

**Issue by Hirbod** [Respect/Validation#769]
Hi,

im struggling around to understand the NestedValidations.

```php
Array
(
    [0] => All of the required rules must pass for Name
    [1] => Name darf keine Sonderzeichen enthalten
    [2] => Name darf nicht länger als 32 Zeichen sein
    [3] => All of the required rules must pass for Vorname
    [4] => Vorname must be a string
    [5] => Vorname must have a length between 1 and 32
    [6] => E-Mail ist keine gültige E-Mail Adresse
    [7] => Geschlecht must be a string
    [8] => Straße must be a string
    [9] => Hausnummer darf nur aus Zahlen und Buchstaben bestehen
    [10] => All of the required rules must pass for PLZ
    [11] => PLZ must contain only digits (0-9)
    [12] => PLZ must have a length greater than 5
    [13] => Stadt must be a string
    [14] => Nationalität must be a string
    [15] => Alter must be a valid date
)
```

My Questions:

1) How to translate
"All of the required rules must pass for {{name))". I was already able to translate the real error messages, but not that "introducing" line.

2) The introducing-line repeats for every group, while not having a real group retrospective to the array. IMHO this is confusing, as you don't know which group actually triggered (a multi-associative array would be much better for output)

```php
Array
(
  Array (
      [0] => All of the required rules must pass for Name
      [1] => Name darf keine Sonderzeichen enthalten
     [2] => Name darf nicht länger als 32 Zeichen sein
) Array (
    [0] => All of the required rules must pass for Vorname
    [1] => Vorname must be a string
    [2] => Vorname must have a length between 1 and 32
   ...
```

3) Is it possible to remove the "introducing-line"? I don't want to have that sentence all over inside of my error output, just the real error messages. I know it only appears when one validation has multiple issues.

4) When I translate v::length() it only applies to the first one (name) and not for others. How do i translate length for stringType (all sorts of) and digits?

```php
            $errors = $exception->findMessages([
                'stringType' => '{{name}} darf keine Sonderzeichen enthalten',
                'alnum' => '{{name}} darf nur aus Zahlen und Buchstaben bestehen',
                'length' => '{{name}} darf nicht länger als 32 Zeichen sein',
                'digit' => '{{name}} darf nur aus Zahlen bestehen',
                'email' => '{{name}} ist keine gültige E-Mail Adresse',
                'age' => '{{name}} muss mindestens 18 sein'
            ]);
```

**Comment by bytetonight** [comment]
`$errors = $exception->findMessages([
                'stringType' => '{{name}} darf keine Sonderzeichen enthalten',
                'alnum' => '{{name}} darf nur aus Zahlen und Buchstaben bestehen',
                'length' => '{{name}} darf nicht länger als 32 Zeichen sein',
                'digit' => '{{name}} darf nur aus Zahlen bestehen',
                'email' => '{{name}} ist keine gültige E-Mail Adresse',
                'age' => '{{name}} muss mindestens 18 sein'
            ]);`
Currently the code above will always produce an Array with a length of (length of passed Array) whether a rule passed or not. If a check for a certain rule passes, the resulting template will just be empty but present in the result. In addition, the order of the hard-coded Array passed to findMessages is used, as opposed to the order of the rules applied to the validation, making it somewhat difficult to pull the first item to display.
Example : I need to check an Email field so in Slim I would do :
`$validation = $this->container->validator->validate($request, [
            //various other fields and rules,
            'Email' =>  v::notEmpty()->email(),
        ]);`
Then I'd append 'notEmpty' => '{{name}} must not be empty' to the Array above.
Presumed I then leave the Email field empty in the form, the first fail contained in $errors would be the {{name}} is not a valid Emailaddress where as I would expect the order of my validation checks to be applied, therefore returning the {{name}} must not be empty message.

A solution temporarily at least would be if findMessages just returns an Array of Exceptiontypes [Fieldname =>['alnum', 'notEmpty', 'etc. etc.']] in the order of validation.

**Comment by bytetonight** [comment]
For now my quick & dirty work-around is :

```php
class Validator
{
    protected $errors;
    protected $messagesDE = [
        'notEmpty' => '{{name}} darf nicht leer sein.',
        'alpha'    => '{{name}} darf nur Buchstaben enthalten.',
        'alnum'    => '{{name}} darf nur Zahlen (0-9) und Buchstaben (A-z) enthalten.',
        'numeric'  => '{{name}} darf nur Zahlen enthalten.',
        'length'   => '{{name}} muss größer {{minValue}} und kleiner {{maxValue}} Zeichen sein.',
        'email'    => '{{name}} ist keine gültige Emailadresse.',

    ];

    public function validate(Request $request, array $rules)
    {
        $tempLanguage = 'de'; //will come from elsewhere later on
        foreach ($rules as $field => $rule)
        {
            try
            {
                $rule->setName(ucfirst($field))->assert($request->getParam($field));
            }
            catch (NestedValidationException $ex)
            {
                if ($tempLanguage === 'de')
                {
                    $this->errors[$field] = $ex->findMessages($this->messagesDE); //German messages
                }
                else
                {
                    $this->errors[$field] = $ex->getMessages(); //Default messages
                }
            }
        }
        $tempErrors = $this->errors;
        $this->errors = [];
        foreach ($tempErrors as $key => $value)
        {
            foreach ($value as $v)
            {
                if (!empty($v))
                    $this->errors[$key][] = $v;
            }
        }
        $_SESSION['validationErrors'] = $this->errors;

        return $this;
    }

    public function failed()
    {
        return !empty($this->errors);
    }
}
```

**Comment by thibaudcolas** [comment]
> How to translate
> "All of the required rules must pass for {{name))". I was already able to translate the real error messages, but not that "introducing" line.

My workaround for this (which comes from `v::allOf` in my project) was to use `setName('IGNORE_ERROR')` on the validator, then configure the error handling to discard all errors that contain `IGNORE_ERROR`. This seems very brittle, but is the only way I found to discard the message.

I don't understand why this rule has an error message to start with – it's only meant to be used combined with other rules, and adding an extra error message doesn't add any value to whoever is reading the errors.

**Comment by henriquemoody** [comment]
With so many open issues, it's become hard to really know what's really important and what I have fixed already.

I'm closing issues that are too old, and I'm not really looking at them all. If this is still relevant, please comment here and I will reopen this issue.

Thanks for reporting! 🐼
