### ISSUE TITLE
May be a bug

### ISSUE THREAD

**Issue by JasonKid** [Respect/Validation#770]
Why `Validator::positive()->between(0x01, 0xFF, true)->validate(‘4345g’)` returns `true` but `Validator::positive()->between(0x01, 0xFF, true)->validate(‘555g’)` returns `false`?

**Comment by andysnell** [comment]
I'm not sure if this is so much a bug as it is relying too much on implicit type juggling, as you are passing non-numeric strings to be evaluated as integers.  The `between()` method relies on the `filterInterval() method I've copied below.  What is happening is that when you pass try to validate the string '555g' it fails the first, second, and third if statements and is returned as itself, which when compared to an integer by PHP, is juggled to 555; however, when you validate '4345g', it only fails the first and second if statements.  '4345g' is considered by the interpreter to be a valid `strtotime()` string, and the function returns a DateTime object in the year 4345.  While you can compare two DateTime objects with the comparison operators, you cannot cast validly cast a DateTime object to an integer -- it raises a notice and returns 1.  **That is, given the current function below and how the comparisons are made the string '4345g' is eventually cast as 1 for comparison to the minimum and max values.**

```php
    protected function filterInterval($value)
    {
        if (!is_string($value) || is_numeric($value) || empty($value)) {
            return $value;
        }

        if (mb_strlen($value) == 1) {
            return $value;
        }

        try {
            return new DateTime($value);
        } catch (Exception $e) {
            // Pokémon Exception Handling
        }

        return $value;
    }
```

**Comment by JasonKid** [comment]
@andysnell thanks for your time, I've understood it~
