### ISSUE TITLE
Getting started ....

### ISSUE THREAD

**Issue by WalhallaX** [Respect/Validation#771]
Hello,

I'm sorry for posting this request on Github.
I want to use Respect/Validation in my project, but  don't have experience with composer. I am developing locally with Xampp. I have installed composer and ran the mentioned command in the manual. 

> composer require respect/Validation

No error has been displayed. I think the Installation went fine. There is a folder at "\xampp\php\vendor\respect\Validation" containing the data.

I restarted the webserver and opened my PHP project. I used the following lines for a test:

``use Respect\Validation\Validator as v;
$number = 123;
v::numericVal()->validate($number); // true``

As expected it didn't work. (Fatal error: Class 'Respect\Validation\Validator' not found)

What else do I need to do?

Also I do have concerns about using it. What will I do when my project is finished and I would want to run it on a paid webserver? I don't think I could run composer there ...

Please give me some more information. I really want to use the Validation!

Thank you

**Comment by copynpaste** [comment]
`require 'vendor/autoload.php';`

Build your dependencies local and push them all together to your server.

**Comment by WalhallaX** [comment]
Thank you - I got it.
I also read a tutorial on composer/autoload.
Now I understand the system.

The first thing I tried was this basic example:
`$number = 123;
v::numericVal()->validate($number); // true`

It throws an error:

> Fatal error: Uncaught exception 'Respect\Validation\Exceptions\ComponentException' with message '"numericVal" is not a valid rule Name ...

But everything else I tried worked. Nice

**Comment by WalhallaX** [comment]
Oh, this rule was renamed. "Numeric" works ...

**Comment by shackrock** [comment]
I will note that this needs to be addressed in the documentation, as the docs still reference numericVal:
https://github.com/Respect/Validation/blob/master/docs/NumericVal.md
and
https://github.com/Respect/Validation/blob/master/docs/VALIDATORS.md links to the above page.

**Comment by reimax** [comment]
require 'vendor/autoload.php';
use Respect\Validation\Validator as v;

$number = 123; 
v::numericVal()->validate($number); // true
result: "numericVal" is not a valid rule name

$test = v::stringVal()->validate("test");
result: "stringVal" is not a valid rule name

**Comment by henriquemoody** [comment]
On the documentation of every rule on _master_ there is a _CHANGELOG_, check out [NumericVal](https://github.com/Respect/Validation/blob/master/docs/NumericVal.md) and [StringVal](https://github.com/Respect/Validation/blob/master/docs/StringVal.md) and check which version are you using right now.

NumericVal will be renamed at version 2.0.0 and StringVal will be created at the same version. 2.0.0 is not released yet. :)

I'm closing the issue since it's not a issue, but feel free to write comments any time.

🐼

**Comment by reimax** [comment]
https://github.com/Respect/Validation
example:
`Complex rules made simple: v::**numericVal**()->positive()->between(1, 255)->validate($input).`

install via composer from doc:
composer require respect/validation

and in composer.json:
{
    "require": {
        "respect/validation": "^1.1"
    }
}

The documentation is obtained already for 2.0, but composer default install 1.1. In this, the whole problem was received.

**Comment by henriquemoody** [comment]
That's exactly what I'm saying, you're using version 1.1, so you should use _Numeric_ instead of _NumericVal_.  Version 2.0 is not released yet.

The documentation of the current version can be found on the website: http://respect.github.io/Validation/docs/numeric.html
