### ISSUE TITLE
Prevent exposure of values

### ISSUE THREAD

**Issue by shadowhand** [Respect/Validation#774]
I work in health care IT and want to be able to use this package. The problem is that there appears to be no way to prevent exposure of input data in exceptions. In terms of error reporting, this is not a problem, since it can be assumed that the user receiving the error is the one inputting the data.  The problem is that any exception that contains [PHI](https://en.wikipedia.org/wiki/Protected_health_information) might result in the PHI being transmitted to a logging service, etc if uncaught.

It would be nice if there was a global setting or some way to disable the exception message from containing the input values. This would ensure that PHI would never end up in a third party logging service that is not authorized to hold such information.

Similar concerns would apply to credit cards, national identity numbers, etc.

**Comment by henriquemoody** [comment]
With so many open issues, it's become hard to really know what's really important and what I have fixed already.

I'm closing issues that are too old, and I'm not really looking at them all. If this is still relevant, please comment here and I will reopen this issue.

Thanks for reporting! 🐼
