### ISSUE TITLE
Attribute validator does not work with privately inherited fields

### ISSUE THREAD

**Issue by fracz** [Respect/Validation#776]
Example:

```php
class A {
    private $property;
    public function __construct($property) {
        $this->property = $property;
    }
    public function getProperty() {
        return $this->property;
    }
}

class B extends A {
}

$validator = Validator::attribute('property');
$a = new A(true);
$b = new B(true);

$validator->validate($a); // true
$validator->validate($b); // false !!
```

IMO, it's not intuitive that the second validation fails because of the `private` field modifier. Changing it to the `protected` makes the validation pass.

While I understood the logic behind this when I discovered that `protected` works, I thing it might be worth mentioning in the docs that the `attribute` validator behaves in this way.

**Comment by henriquemoody** [comment]
With so many open issues, it's become hard to really know what's really important and what I have fixed already.

I'm closing issues that are too old, and I'm not really looking at them all. If this is still relevant, please comment here and I will reopen this issue.

Thanks for reporting! 🐼
