### ISSUE TITLE
Using an Array to check against, while also all Catching Errors for display

### ISSUE THREAD

**Issue by shackrock** [Respect/Validation#794]
Hi all.  I know Github may not be the right place for Q&A/Help, but I don't know where else the community is active (maybe that can be added to the readme for "if you need more help..."

I am attempting to catch errors utilizing Validator. I used their example to create an array of checks. Although that seems to work ok, I then attempted to catch any error messages so that I could display it to the user. I saw no method to do so as a full array (check everything, store all messages in an array). So instead, I tried to cycle through using the check method in Validator.

This is inside of a class method, using the F3 (Fat Free) Framework.

I end up with the following error:

`Cannot use object of type Respect\Validation\Validator as array`

The code is below. What is the proper way to perform this task using arrays here?

```
$registerValidator = Respect\Validation\Validator::attribute('email', Respect\Validation\Validator::email()->length(1,null)->notEmpty())
                                ->attribute('address', Respect\Validation\Validator::stringType()->length(3,null)->notEmpty())
                                ->attribute('city', Respect\Validation\Validator::alpha()->length(2,60)->notEmpty())
                                ->attribute('state', Respect\Validation\Validator::alpha()->length(2,2)->notEmpty())
                                ->attribute('zip', Respect\Validation\Validator::intType()->length(5,5)->notEmpty());

            foreach($this->f3->get('POST') as $key => $value){
                try{
                    $registerValidator[$key]->check($value);
                } catch (\InvalidArgumentException $e) {
                    $errors = $e->getMainMessage();
                    $this->userMessage($errors, 'warning');
                    $this->f3->reroute('/register');
                }
            }
```

I have also tried to use the assert method as found in the readme docs, but utilizing the below change, I get a different error at a 500 Server Internal Error, instead of seeing my echo:

```
       try{
            $registerValidator->assert($this->f3->get('POST'));
        } catch (Respect\Validation\Validator\NestedValidationException $e) {
            $errors = $e->getMessages();
            echo($errors); // I can't even get here.
            foreach($errors as $error){
                $this->userMessage($error, 'warning');
            }
            $this->f3->reroute('/register');
        }
```
With this 500 Error, rather than seeing my Echo, so the page stops loading entirely.
`All of the required rules must pass for ...`

Thanks

**Comment by copynpaste** [comment]
Try Stackoverflow: http://stackoverflow.com/questions/tagged/respect-validation

**Comment by henriquemoody** [comment]
http://stackoverflow.com/a/42279178/1419363

Thanks for reporting! 🐼
