### ISSUE TITLE
Array to string conversion in ValidationException.php on line 70 when using array method reference

### ISSUE THREAD

**Issue by fracz** [Respect/Validation#799]
[The docs](https://github.com/Respect/Validation/blob/master/docs/Call.md) say I can use an array notation for callback for both `call` and `callback` validators. However, the following code resutls in 

> PHP Notice:  Array to string conversion in C:\projects\some-project\vendor\respect\validation\library\Exceptions\ValidationException.php on line 70

```php
<?php
use Respect\Validation\Validator;

require 'vendor/autoload.php';

class A {
    public function parse(string $url) {
        return parse_url($url);
    }
}

$object = new A;
$url = 'http://www.google.com/search?q=respect.github.com';
Validator::call(
    [$object, 'parse'],
    Validator::arrayVal()->key('scheme', Validator::startsWith('https'))
)->assert($url);
```

It is only a notice - I know. But notices break PHPUnit tests in strict configuration.

---
Edit: Actually, with closuers it is even worse:

> Object of class Closure could not be converted to string

with the following code:

```php
Validator::call(
    function($url){ return parse_url($url); },
    Validator::arrayVal()->key('scheme', Validator::startsWith('https'))
)->assert($url);
```

**Comment by henriquemoody** [comment]
The but was fixed on 1.0.17 and 1.1.12.

Just upgrade your version!

Thanks for reporting! 🐼
