### ISSUE TITLE
How can I set custom error message inside the KEY validation ?

### ISSUE THREAD

**Issue by BaNdErOzZz** [Respect/Validation#805]
`try{`
`    Validator::key('email', Validator::email()->setTemplate('WRONG EMAIL !!!!!!'))->assert(['email' => 'qwe']);`
 `}catch (NestedValidationException $e){`
`            var_dump($e->getMessages()); die();`
`        }`

Shows: "_email must be valid email_" instead of "_WRONG EMAIL !!!!!!_" .

But if I use  `Validator::email()->setTemplate('WRONG EMAIL !!!!!!')->assert('qwe')` it's working !

I use 1.1.12 version.

**Comment by BaNdErOzZz** [comment]
Any suggestions ?

**Comment by fracz** [comment]
Seems like a dup of #619

**Comment by henriquemoody** [comment]
It should be fixed in the version 1.1.19 which I intent to release very soon.

Thank you very much for reporting! 🐼
