### ISSUE TITLE
Create "Time" rule

### ISSUE THREAD

**Issue by AlastairDewar** [Respect/Validation#810]
Request for a new feature to validate time supporting the following formats:

Format | Description | Values
-------|-------------|--------
`g` | 12-hour format of an hour without leading zeros   | 1 through 12
`G` | 24-hour format of an hour without leading zeros   | 0 through 23
`h` | 12-hour format of an hour with leading zeros      | 01 through 12
`H` | 24-hour format of an hour with leading zeros      | 00 through 23
`i` | Minutes with leading zeros                        | 00 to 59
`s` | Seconds, with leading zeros                       | 00 through 59
`u` | Microseconds                                      | 000000 through 999999
`v` | Milliseconds                                      | 000 through 999
`a` | Lowercase Ante meridiem and Post meridiem         | am or pm
`A` | Uppercase Ante meridiem and Post meridiem         | AM or PM

The rule should accept only those formats plus spaces and any non-alphanumeric character, so we can do something like: `g:i A`

**Comment by AlastairDewar** [comment]
I just came across the SF validator which supports Time, perhaps just add a native Validator to call this function to save writing a new one?

**Comment by henriquemoody** [comment]
Makes sense. Our _Date_ validator is actually a _DateTime_ validator. Would be a good idea to rename Date to DateTime and create the Date and Time validators.

**Comment by henriquemoody** [comment]
@AlastairDewar, don't forget that you can also use [Sf](http://respect.github.io/Validation/docs/sf.html) rule.

**Comment by henriquemoody** [comment]
Thanks for reporting! 🐼 

Fixed by #912
