### ISSUE TITLE
Postal code validation not set for Cayman Islands

### ISSUE THREAD

**Issue by RCooLeR** [Respect/Validation#820]
Missing regex for KY country code
http://www.caymanpost.gov.ky/portal/page/portal/poshome/posnpimages/POSTCODE%20FINDER%20COLOUR.pdf

**Comment by nickl-** [comment]
Please submit a pull request for review.

**Comment by henriquemoody** [comment]
Fixed by a44f97f

This fix _will_ be available in version 2.0.6, which will be released together with a couple more of postal code fixes.

Thanks for reporting! 🐼
