### ISSUE TITLE
Split luhn check from credit card check

### ISSUE THREAD

**Issue by REBELinBLUE** [Respect/Validation#823]
The Luhn algorithm isn't just used by credit cards, for example the company I work at has loyalty cards which also use luhn check, but the CreditCard validator can't be used as it also checks that the number matches the known patterns for the various brands.

I think it would be useful to separate verifyMod10 into a separate validator https://github.com/Respect/Validation/blob/94a79c033a53aa9fe05b794d502de70116ab8fb7/library/Rules/CreditCard.php#L81-L99 and change CreditCard to use it

**Comment by henriquemoody** [comment]
Fixed by #868

Thanks for reporting! 🐼
