### ISSUE TITLE
Create "Date" rule

### ISSUE THREAD

**Issue by henriquemoody** [Respect/Validation#826]
Request for a new feature to validate date supporting the following formats:

Format  | Description                                                           | Values
--------|-----------------------------------------------------------------------|-------------------------
`d`     | Day of the month, 2 digits with leading zeros                         | 01 to 31
`j`     | Day of the month without leading zeros                                | 1 to 31
`S`     | English ordinal suffix for the day of the month, 2 characters         | st, nd, rd or th
`F`     | A full textual representation of a month, such as January or March    | January to December
`m`     | Numeric representation of a month, with leading zeros                 | 01 to 12
`M`     | A short textual representation of a month, three letters              | Jan to Dec
`n`     | Numeric representation of a month, without leading zeros              | 1 to 12
`Y`     | A full numeric representation of a year, 4 digits                     | Examples: 1988 or 2017
`y`     | A two digit representation of a year                                  | Examples: 88 or 17

The rule should accept only those formats plus spaces and any non-alphanumeric character, so we can do something like: `F jS, Y` (e.g. May 1st, 2017).
***
Depends on #821

**Comment by DaniloBenevides** [comment]
Hello, still need help on this issue ?

**Comment by henriquemoody** [comment]
@brunoluiz was working on it, but it would be fine by me if you would like to take over. See #875. Or you can also help on #810

**Comment by DaniloBenevides** [comment]
I will start with #810 if when i finish it #875 still undone i will help there too.

**Comment by henriquemoody** [comment]
Fixed by #911. Do you have any update about the `Time` rule, @DaniloBenevides?

**Comment by henriquemoody** [comment]
Hey, @DaniloBenevides! Don't worry about it, I took care of it, see #911 and #912.

However, if you still want to contribute, you can check some "Easy pick" issues: https://github.com/Respect/Validation/labels/Easy%20Pick

🐼

**Comment by DaniloBenevides** [comment]
Thanks @henriquemoody , I will search one.
