### ISSUE TITLE
storing validation rules to database

### ISSUE THREAD

**Issue by paranic** [Respect/Validation#828]
I have already read issue #72 on Annotation Support
and i think this would be a nice feature if you inspire developers with some examples to use it.

actually what i need is a bit different
i have members with their properties in database
and members_groups records
i just want to store validation/filtering rules in a column at  members_groups table
and then occasionally filter members and add them to the group(s) they pass validation

and then be able to visualize this library to a web interface so the user can create dynamic groups.
my first main concern is how to store rules at the database

does anyone have any idea?

**Comment by nickl-** [comment]
I believe this is beyond the scope of this project. Respect/Validation is intended as a utility to simplify coding validations.

What you seem to be looking for sounds more like user roles and permissions rather than validation.

Closed issue: out of scope

**Comment by paranic** [comment]
hey nickl don't stick on my example :-) the idea is to have a more database friendly validation rules storage.

it will give new opportunities to this library

**Comment by nickl-** [comment]
It is not the purpose of this library to retrieve data from a db, to parse a csv file or to get values from a form. It is only intended to simplify the validation of the data once you already obtained it.

It is not a rules system so I cannot see how you would make it store rules, this is out of scope.
