### ISSUE TITLE
"dateTime" is not a valid rule name

### ISSUE THREAD

**Issue by vikasgupta0159** [Respect/Validation#832]
I am trying to validate date using this code
```
// Loading Library:
use Respect\Validation\Validator as v;

$from_date = "31-May-2017";
if( !v::dateTime('j-M-Y')->validate($from_date) ){
	$this->setErrorMessage("Invalid date format");
}

// and it is showing me this error:

An uncaught Exception was encountered
Type: Respect\Validation\Exceptions\ComponentException
Message: "dateTime" is not a valid rule name
```

**Comment by StuartStephens** [comment]
Getting the same issue with dateTime()

` $error = false;

    try {
        $fname = filter_var(trim($_POST['fname']), FILTER_SANITIZE_STRING);

        $lname = filter_var(trim($_POST['lname']), FILTER_SANITIZE_STRING);

        $dob = trim($_POST['dob']);

        v::key('fname', v::stringType()->notEmpty()->length(2, 32))
            ->key('lname', v::stringType()->notEmpty()->length(2, 32))
            ->key('dob', v::dateTime('d-m-Y')->notEmpty())
            ->assert($_POST);
            
    }

    catch (InvalidArgumentException $e) {
        $messages = $e->findMessages([
            'fname' => 'name error message.',
            'lname' => 'lname error message.',
            'dob' => 'dob error message.',
        ]);
        $messages = array_filter($messages);
        foreach($messages as $key=>$value){
            
            ${$key._error} = $value;
            $error= 'true';
        }
    }
    catch (Exception $esp) {
        echo $esp->getMessage();
        $error = 'true';
    }`


Goes straight to 2nd catch and says '"dateTime" is not a valid rule name'

**Comment by henriquemoody** [comment]
Check the version you're using and the changelog of this rule: https://github.com/Respect/Validation/blob/master/docs/DateTime.md#changelog

**Comment by fab01** [comment]
If you are using 'composer require' it gets automatically the version 1.1.12 which is not up to date.
I fixed the issue by changing manually the branch to "dev-master" in composer.json:

```
"require": {
        "respect/validation": "dev-master",
```

**Comment by henriquemoody** [comment]
Composer gets by default the stable version of all libraries.

You should be careful every time you use `dev-master` of any library. It's a development version, and it's your own risk, things may break.

**Comment by fab01** [comment]
Yes, just in this case I have been forced to dev-master... normally I never play with branches
Otherwise the stable version would not support the "dateTime" validation according to the documentation. 
Anyway as far as I can see this is a pretty old issue.
Looking forward to get the stable version with dateTime validation fix.

**Comment by henriquemoody** [comment]
You can still use [Date()](http://respect.github.io/Validation/docs/date.html) on old versions if you want.
