### ISSUE TITLE
Validation of multidimensional array

### ISSUE THREAD

**Issue by rudovaa** [Respect/Validation#833]
I need to validate a multidimensional array of articles, where each element has such structure
```
$article = array(
    'persons'=> array(
        array('id' => 82, 'value' => 'Peter J. Abrams'),
        ... (varies for each article)
    ),
    'journal' => array(
        'id' => '124526',
        'value' => 'Science'
    ),
    'title'=> 'Example title',
);
```
I understand how to validate 'journal' and 'title' using 
```
v::key('journal', v::keySet(
           v::key('id', v::int()),
           v::key('value', v::stringType()())
         )
 ->key('title',  v::stringType())
 ->validate($signup);//true
```

But in my case 'persons' don`t have the same dimension from article to article.

So my question could you please advise me how to validate each 'article' which have different number of elements in 'persons' array.

**Comment by nickl-** [comment]
Please provide more information. What do you consider to be a valid persons key?

**Comment by henriquemoody** [comment]
It's been a long time since there is no response on this one. I'm gonna close this one but feel free to send a new one if needed! 

I hope you found a resolve for your problem anyways! 🐼
