### ISSUE TITLE
new validation rule:  isSuperSet and isDisjointedSet

### ISSUE THREAD

**Issue by Singwai** [Respect/Validation#834]
I would like to propose 2 new validations to determine 

1 - if an array contain all values of another array.
2 - if an array contain none of the values of another array.

**Comment by nickl-** [comment]
Would you like to submit a pull request to implement?

**Comment by Singwai** [comment]
https://github.com/Respect/Validation/pull/892 This PR determine if array contain all values of another array

**Comment by nickl-** [comment]
#892 supersedes... closing
