### ISSUE TITLE
URL-Validator without the protocol

### ISSUE THREAD

**Issue by Syndesi** [Respect/Validation#840]
Hi,

is it possible to implement a rule like the url()-validator but without presupposing the protocol?

**Comment by nickl-** [comment]
Have a look at the [list of String type validators](https://github.com/Respect/Validation/blob/1.1/docs/VALIDATORS.md#string) there is sure to be something that you could use for this.

**Comment by henriquemoody** [comment]
It's been a month since there is no response on this one. I'm gonna close this one but feel free to send a new one if needed! 

As @nickl- suggested you could use one of the other validators, like `v::not(regex('/^http/'))`.

I hope you found a resolve for your problem anyways! 🐼
