### ISSUE TITLE
new validation rule: IBAN 

### ISSUE THREAD

**Issue by Chriskamphuis** [Respect/Validation#843]
I would propose one new validation rule that deterimines if an input is a proper IBAN as described on [this](https://en.wikipedia.org/wiki/International_Bank_Account_Number) wikipedia page.

**Comment by Chriskamphuis** [comment]
I would like to submit a pull request to implement this.

**Comment by henriquemoody** [comment]
Hey, @Chriskamphuis! I will be more than happy with your PR!

**Comment by DaniloBenevides** [comment]
Hello , anyone working on this issue ?

**Comment by mazentouati** [comment]
@henriquemoody is this implemented ? If not I'll work on it;

**Comment by henriquemoody** [comment]
It's all yours @mazentouati!

**Comment by henriquemoody** [comment]
Closed by #1194
