### ISSUE TITLE
customize error message

### ISSUE THREAD

**Issue by km3945** [Respect/Validation#845]
```php
try {
	$post=[
		'name'=>'',
		'nick'=>''
	];
	v::create()
		->key('name', v::stringType()->notEmpty()->setName('adds_name|name'))
		->key('nick', v::stringType()->notEmpty()->setName('adds_nick|nick'))
		->assert($post);
}catch (NestedValidationException $e){
	$e->findMessages([
		'stringType' => '{{name}} STRING',
		'notEmpty' => '{{name}} EMPTY'
	]);
	dd($e->getMessages());
}
```
Output:

array (2)
   0 => "adds_name|name EMPTY"
   1 => "adds_nick|nick must not be empty"

Expect:

array (2)
   0 => "adds_name|name EMPTY"
   1 => "adds_nick|nick EMPTY"

I want to customize the error message

**Comment by henriquemoody** [comment]
With so many open issues, it's become hard to really know what's really important and what I have fixed already.

I'm closing issues that are too old, and I'm not really looking at them all. If this is still relevant, please comment here and I will reopen this issue.

Thanks for reporting! 🐼
