### ISSUE TITLE
intVal and float-like strings

### ISSUE THREAD

**Issue by mattsah** [Respect/Validation#849]
I've noted when validating form input that intVal() allows a string such as '500.00' to pass as an int.  This is a bit of a problem once attempts are made to insert it into the DB.  Thoughts on changing this?

**Comment by arthur-rrs** [comment]
`<?php
/*
 * This file is part of Respect/Validation.
 *
 * (c) Alexandre Gomes Gaigalas <alexandre@gaigalas.net>
 *
 * For the full copyright and license information, please view the "LICENSE.md"
 * file that was distributed with this source code.
 */
namespace Respect\Validation\Rules;
class IntVal extends AbstractRule
{
    public function validate($input)
    {
       -return is_numeric($input) && (int) $input == $input;
      +return +is_numeric($input) && (int) $input == $input && false == strpos($input, '.');
    }
}
`

**Comment by henriquemoody** [comment]
This issue will be fixed in the version 1.1.18. Thanks for reporting! 🐼
