### ISSUE TITLE
how to install it without composer

### ISSUE THREAD

**Issue by phil123456** [Respect/Validation#858]
Hello,

I cant install composer on windows (cfr https://github.com/composer/composer/issues/6725)

can you tell me how to install your validator staticaly/manualy ?

thanks

**Comment by henriquemoody** [comment]
Without Composer you have to copy the code and implement [PSR-0](http://www.php-fig.org/psr/psr-0/) autoloader yourself.

**Comment by phil123456** [comment]
wow took you long enough :-)
in the mean time I just added require_once, so far so good
