### ISSUE TITLE
Date passes unexpectedly

### ISSUE THREAD

**Issue by Jossnaz** [Respect/Validation#861]
`                    ->key('motr_date_of_birth', v::date('m/d/Y'))`

will pass input
`10/10/84` as valid

the problem is that this function is used in the respect library
```
$info = date_parse_from_format('m/d/Y', '10/10/84');
var_dump($info);
```

returns:

`array(12) { ["year"]=> int(84) ["month"]=> int(10) ["day"]=> int(10) ["hour"]=> bool(false) ["minute"]=> bool(false) ["second"]=> bool(false) ["fraction"]=> bool(false) ["warning_count"]=> int(0) ["warnings"]=> array(0) { } ["error_count"]=> int(0) ["errors"]=> array(0) { } ["is_localtime"]=> bool(false) }`

e.g. all good

**Comment by Jossnaz** [comment]
current workaround is this manual work:


    ```
if(date('m/d/Y', strtotime($_POST['motr_date_of_birth'])) != $_POST['motr_date_of_birth']){
      $motr_field_errors['motr_date_of_birth'] = 'Please enter your date of birth in the format MM/DD/YYYY (ex: 05/29/1985)';
    }
```

but it's clumsy

**Comment by henriquemoody** [comment]
The validation is correct `10/10/84` is a valid date in `m/d/Y` format, once 84 is also an year. If you want to get a specific date range you should use something like `v::date('m/d/Y')->min('1000 years ago')`
