### ISSUE TITLE
email validation failed

### ISSUE THREAD

**Issue by lanlin** [Respect/Validation#872]
This email address come from the lists.php.net mailing robot

## email address:
php-general-uc.1355065098.adaplbockllfebeiggpp-lanlin1987=gmail.com@lists.php.net
php-general-uc.1400015774.ggjhebfndcpbcgpljcdd-php=renatius.de@lists.php.net

**Comment by henriquemoody** [comment]
Hey, @lanlin! Did you try to install `egulias/email-validator`?

**Comment by lanlin** [comment]
@henriquemoody thanks, it works!

The [email validator doc](http://respect.github.io/Validation/docs/email.html) hasn't mention of this. May you take a little time to add to this?
