### ISSUE TITLE
charset('Windows-1252') always evaluates to false

### ISSUE THREAD

**Issue by alexweltman** [Respect/Validation#873]
No matter what I validate, charset always returns ```false``` when using the [Windows-1252 charset](https://en.wikipedia.org/wiki/Windows-1252). 
```php
v::charset('Windows-1252')->validate("test"); // returns false, but shouldn't!
v::charset('Windows-1252')->validate("123"); // returns false, but shouldn't!
```

**Comment by alexweltman** [comment]
looks like this validator uses mb_detect_encoding, which is not supported for Windows-1252
https://stackoverflow.com/questions/22125469/unexpected-result-from-mb-detect-encoding-with-windows-1252

**Comment by nickl-** [comment]
Closed: Known issue
