### ISSUE TITLE
regex does not work as expected for french words with accents

### ISSUE THREAD

**Issue by phil123456** [Respect/Validation#876]
Hello,

I try to validate a frech text "sécurité" with accents, but it seems validate returns false

    if(!v::regex("/^[a-z0-9\p{L}\s\-'’.,:@\[\]\(\)]+$/im")->validate($data)) )
    {
        ... error
    }

I checked my regex in https://regex101.com/ and it works

how can I make this work correctly ? what am I missing

thanks

**Comment by rhagni** [comment]
@phil123456 What's your package and PHP version? Is your `$data` not an array?

I tried to reproduce without success:
```
C:\tmp> mkdir foo-test & cd foo-test

C:\tmp\test> composer require respect/validation
Using version ^1.1 for respect/validation
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing symfony/polyfill-mbstring (v1.6.0): Loading from cache
  - Installing respect/validation (1.1.14): Loading from cache

C:\tmp\test> vim index.php
```

```php
<?php

require "vendor/autoload.php";

use Respect\Validation\Validator as v;

$data = "sécurité";

if (!v::regex("/^[a-z0-9\p{L}\s\-'’.,:@\[\]\(\)]+$/im")->validate($data)) {
    echo "not match";
} else {
    echo "match";
}
```

```
C:\tmp\test> php index.php
match
```

My versions:

```
C:\tmp\test> php -v
PHP 7.1.3 (cli) (built: Mar 14 2017 23:33:39)
[...]
C:\tmp\test> composer -V
Composer version 1.4.1 2017-03-10 09:29:45
```

**Comment by phil123456** [comment]
php 7.0.10 with wamp..I'll chekc if the issue appears on the prod system(redhat)
thanks for giving it a test

**Comment by williamespindola** [comment]
@phil123456 show us the error, as you said you don't using composer and import it manually, maybe something is missing during import. With error message we can analyze better.

**Comment by phil123456** [comment]
there is no error messsage, it returns false instead of true

**Comment by rhagni** [comment]
I have found a probable solution to your problem.

After your reply I have tried my own example and so doesn't match anymore, so I remember I have changed my ".vimrc" some days ago, switching my default encoding from WINDOWS-1252 to UTF-8. 

So... let's try (following my old example):
```
C:\tmp\test> php index.php
not match
C:\tmp\test> file --mime-encoding *
composer.json: us-ascii
composer.lock: us-ascii
index.php:     utf-8
vendor:        binary

C:\tmp\test> iconv -f UTF-8 -t MS-ANSI index.php > index-ms-ansii.php

C:\tmp\test> file --mime-encoding *
composer.json:      us-ascii
composer.lock:      us-ascii
index-ms-ansii.php: unknown-8bit
index.php:          utf-8
vendor:             binary

C:\tmp\test> php index-ms-ansii.php
match
```
(Remembering: To iconv "CP1252", "MS-ANSI" are alias to "WINDOWS-1252", or vice-versa)

So, you can do something like this:
```php
if (isUtf8($data)) {
    $data = utf8_decode($data);
}
```

"isUtf8" is an universal function to my codes:
```php
function isUtf8($data) {
    $pattern = "~[\xC2-\xDF][\x80-\xBF]|
        \xE0[\xA0-\xBF][\x80-\xBF]|
        [\xE1-\xEC\xEE\xEF][\x80-\xBF]{2}|
        \xED[\x80-\x9F][\x80-\xBF]|
        \xF0[\x90-\xBF][\x80-\xBF]{2}|
        [\xF1-\xF3][\x80-\xBF]{3}|
        \xF4[\x80-\x8F][\x80-\xBF]{2}~s";

    return (bool) preg_match($pattern, $data);
}
```

**Comment by phil123456** [comment]
sorry haven't seen you replies lately, I'll have a look

in the meantime I used this that sem to work better

 (!v::regex("/^[0-9a-z\p{L}\s\’\'\:\.\-\,\!\[\]\(\)\@]+?$/ium")->validate($data)) )

adding the u did the trick I think

**Comment by henriquemoody** [comment]
With so many open issues, it's become hard to really know what's really important and what I have fixed already.

I'm closing issues that are too old, and I'm not really looking at them all. If this is still relevant, please comment here and I will reopen this issue.

Thanks for reporting! 🐼
