### ISSUE TITLE
Change the docs of master branch to stable docs version

### ISSUE THREAD

**Issue by fuadmuhtaz** [Respect/Validation#877]
When use `composer require respect/validation` the composer install version ^1.1 as default. When i'm read VALIDATORS doc from this repo, the VALIDATORS docs use version 2.0. So many validators from the doc not valid when use default installation, and it make me confused when first time use.

I think show docs version from default installation will be better for new comer like me :D

Sorry for my bad english :3

**Comment by henriquemoody** [comment]
I changed the default branch to 1.1 to avoid those misunderstandings, even though the documentation says that they were renamed https://github.com/Respect/Validation/blob/master/docs/DateTime.md#changelog
