### ISSUE TITLE
Idea new function for case contains list character :)

### ISSUE THREAD

**Issue by tieutantan** [Respect/Validation#878]
Hi, can you create function require must contain one or more element in list character be like this example.

`v::contains_list(['word', '@', '/'])->validate('lorem ipsum'); ` 
// return false

`v::contains_list(['word', '@', '/'])->validate('lorem ipsum word'); ` 
// return true

`v::contains_list(['word', '@', '/'])->validate('lorem ipsum @ word'); ` 
// return true

Now you have `v::in(mixed $haystack)` and `v::contains(mixed $value)`, but there only check 1 element like word or character, we need function can check multiple value.

Thanks for reading. Love you 💯%

**Comment by henriquemoody** [comment]
With so many open issues, it's become hard to really know what's really important and what I have fixed already.

I'm closing issues that are too old, and I'm not really looking at them all. If this is still relevant, please comment here and I will reopen this issue.

Thanks for reporting! 🐼
