### ISSUE TITLE
Validate::dateTime() not working, Validate::date() fails on certain dates.

### ISSUE THREAD

**Issue by GhostMech** [Respect/Validation#880]
Hi.

When I use Validate::date() on something like 11/31/2017, it returns TRUE when it should return FALSE.
Same thing with entering 2017-11-31.

Also, when I TRY Validate::dateTime() it fails with this: 
Uncaught Respect\Validation\Exceptions\ComponentException: "dateTime" is not a valid rule name

**Comment by fuadmuhtaz** [comment]
When you not input the format, rule date will use 
`return false !== strtotime($date)`
[https://github.com/Respect/Validation/blob/22f1f14430155c21c1d6ba271a652f28c5057851/library/Rules/Date.php#L40](url)

When you install this library from composer, the docs you must use is in branch 1.1.
 [https://github.com/Respect/Validation/blob/1.1/docs/VALIDATORS.md](url)

I'm open issue about the docs #877

**Comment by henriquemoody** [comment]
Check the DateTime changelog and the version you have installed: https://github.com/Respect/Validation/blob/master/docs/DateTime.md#changelog

PHP sometimes fail to _guess_ which format you're trying to match, I do recommend you to use an specific format for that, like `v::date('d/m/Y')` so you're sure it will be a proper date.
