### ISSUE TITLE
More information in Alnum

### ISSUE THREAD

**Issue by elshobokshy** [Respect/Validation#881]
It's not written in Alnum.md that we need to separate arguments with a space, I had to look in the code to figure it out.
It would be nice to edit this :  

> A parameter for extra characters can be used:
> 
> v::alnum('-')->validate('foo - 123'); // true

to something like : 

> A parameter for extra characters can be used:
> 
> v::alnum('- ! :')->validate(': foo - 123 !'); // true

Source : https://github.com/Respect/Validation/blob/master/docs/Alnum.md

**Comment by williamespindola** [comment]
Sometime we lost the possibilites :D So, you can do this PR, we will be grateful for receive it.

**Comment by henriquemoody** [comment]
This is now available in the website. See http://respect.github.io/Validation/docs/alnum.html

Thanks for contributing! 🐼
