### ISSUE TITLE
Using validators with ArrayObject's offsetSet?

### ISSUE THREAD

**Issue by PatrickSJ** [Respect/Validation#889]
Let's say I have a list of rules for all of the attributes of an object:
`Validator::key('attr_1', Validator::rule_1()->rule_2()->rule_3())
               ->key('attr_2, Validator::rule_1()->rule_2()->rule_3())
`

Now, if I want to validate the entire object that's all well and good, but with PHP's ArrayObject (and other classes implementing ArrayAccess) you can go things like `$obj['attr_1'] = 'foo'`.  However, in situations where I'm doing this I can't validate since ALL rules are being evaluated.

What if not everything is set yet?  I do want exceptions thrown if an invalid value is set for a specific attribute, but I do not want to check all of the rules.

Is there a way to check only the rules for a specific key if all of the keys and their rules have been predefined?

**Comment by henriquemoody** [comment]
With so many open issues, it's become hard to really know what's really important and what I have fixed already.

I'm closing issues that are too old, and I'm not really looking at them all. If this is still relevant, please comment here and I will reopen this issue.

Thanks for reporting! 🐼
