### ISSUE TITLE
AbstractInterval->filterInterval() returns DateTime and that ends with error!

### ISSUE THREAD

**Issue by urmasrosenberg** [Respect/Validation#908]
Code: v::intVal()->between(1900, 2040)->setName('year')

everything works fine, until input is something that can parsed as date. For example **2018-01-25**, then in Max/Min classes, input is filtered by filterInterval() but as it returns DateTime object, casting error happens:

"**Object of class DateTime could not be converted to int**"

as there will be comparsion like this: dateTimeObject < 1900

Ideas:
* casting to DateTime should not happen, or do separate classes BetweenDate, BetweenInt
* add class untilFirstFail or smth, which can take rule list like OneOf/AllOf, but rules are checked until first error (so we would not compare() if intVal() already fails)
* before filter return false if input is not number?
* return false if types are not comparable?
* return false if (only?) one is object?

Comparsion problem if converted to DateTime()
'2018-01-10' < '518-01-11' => true (string 2.. is smaller than 5..)
new DateTime('2018-01-10') < new DateTime('518-01-11') => false (year 2018 greater than 518)

**Comment by urmasrosenberg** [comment]
It should, I think, check the value already in IntVal object, but it doesn't. It checks only for float and boolean, to return false. String goes through.

From there it gets through Min/Max class where filterInterval() is called and it ends up with 
[AbstractInterval:39] return new DateTime($value);

Object is returned it ends up with casting error

**Comment by henriquemoody** [comment]
Thanks for reporting and for the proposed solutions! 🐼 

 I cooked #1060 to solve the problem, check it out!

About the validation _getting_ there: if you use `IntVal` but you validate your input with `assert()` all rules in the chain will be validated, Validator will not skip the next rule if the current one fails (unless if you use `check()`)

**Comment by henriquemoody** [comment]
The fix is available in version 1.1.21

And again, thanks for reporting! 🐼

**Comment by urmasrosenberg** [comment]
Thanks for responses and fix!
