### ISSUE TITLE
Be careful for the 'in' validator

### ISSUE THREAD

**Issue by zilzurna** [Respect/Validation#914]
Hello everyone,

I found an issue and want to notice you. So, when you give the "true" value to the "in" function then it could always pass the validation.

Example;
````php
#input true or 'true'

v::in([1, 0]); # true
v::in(['X', 'Y', 'Z']); # true

v::in([1, 0], true); # false
v::in([1, 0])->intVal(); # false
v::in(['X', 'Y', 'Z'], true); # false

**Comment by Nessworthy** [comment]
Hi Zilzurna,

This is expected I imagine. If you want strict type checking, then you should use the second argument. The boolean flag is the equivalent between checking using `==` and `===`.

When evaluating against a boolean without strictly checking types, "truthy"/"falsey" values will also match. The examples above would also apply when checking false against 0, an empty string, an empty array, or null.

**Comment by zilzurna** [comment]
Yes @Nessworthy, you are right also applies for the opposite.

People have to be careful when using the In function. Extra explanation may be good in the documentation.

Thanks.

**Comment by henriquemoody** [comment]
With so many open issues, it's become hard to really know what's really important and what I have fixed already.

I'm closing issues that are too old, and I'm not really looking at them all. If this is still relevant, please comment here and I will reopen this issue.

Thanks for reporting! 🐼
