### ISSUE TITLE
Validate url is an image

### ISSUE THREAD

**Issue by elshobokshy** [Respect/Validation#915]
Is there a way to validate that the give url is an image, meaning the url has a .jpg/png .. etc extension?

**Comment by nickl-** [comment]
You can test if the string [endsWith](https://github.com/Respect/Validation/blob/1.1/docs/EndsWith.md)

**Comment by elshobokshy** [comment]
Thanks @nickl- ! It's not safe to just check for the string's name but it's a nice workaround for now :)

**Comment by nickl-** [comment]
@elshobokshy yw

**Closed: answered**

Feel free to post a new issue if you have further questions.
