### ISSUE TITLE
$validator->assert($input) work error

### ISSUE THREAD

**Issue by yizhihouzi** [Respect/Validation#917]
.eg code,

$validator = Validator::max(24);
$validator->assert(25);

fault log,
/usr/local/php7/bin/php /Users/yizhihouzi/Desktop/eg/index.php
PHP Fatal error:  Uncaught Error: Call to undefined method Respect\Validation\Exceptions\AllOfException::setInvalidArgumentExceptionRelated() in /Users/yizhihouzi/Desktop/eg/vendor/respect/validation/library/Rules/AllOf.php:27
Stack trace:
#0 /Users/yizhihouzi/Desktop/eg/index.php(18): Respect\Validation\Rules\AllOf->assert(25)
#1 {main}
thrown in /Users/yizhihouzi/Desktop/eg/vendor/respect/validation/library/Rules/AllOf.php on line 27

**Comment by yizhihouzi** [comment]
the Respect/Validation  version is "1.1.15"

**Comment by yizhihouzi** [comment]
@henriquemoody @GrahamCampbell

**Comment by henriquemoody** [comment]
Can you sent us the code itself?

**Comment by henriquemoody** [comment]
It's been a long time since there is no response on this one. I'm gonna close this one but feel free to send a new one if needed! 

I hope you found a resolve for your problem anyways! 🐼
