### ISSUE TITLE
Is this library dead?

### ISSUE THREAD

**Issue by codeaid** [Respect/Validation#919]
I was looking at some issues and pull requests and there are quite a few from more than 2 years ago, some very useful too amongst them. Also the latest 6 commits are 2 from July, 2 from October and 2 from December last year.

Is anyone still maintaining this library? I'm guessing it gained all the stars in its initial stint but then it got quietly abandoned?

Thanks in advance!

**Comment by henriquemoody** [comment]
Besides there is been activity, check out the master branch: https://github.com/Respect/Validation/commits/master
