### ISSUE TITLE
Errors from PHPCompatibility checker

### ISSUE THREAD

**Issue by p-golovin** [Respect/Validation#922]
FILE: Respect/Validation/Rules/Numeric.php
14 | WARNING | 'numeric' is a soft reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_CLASS)

FILE: Respect/Validation/Rules/Call.php
18 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4

**Comment by nickl-** [comment]
> FILE: Respect/Validation/Rules/Numeric.php
> 14 | WARNING | 'numeric' is a soft reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_CLASS)

Can't do much about new keywords conflicting with existing names, the class name will have to change to avoid this warning.

`Number` is one possible rename candidate or perhaps the more verbose `Numerical` is more appropriate.

**Comment by henriquemoody** [comment]
This is already fixed on master!

Thanks for reporting! 🐼
