### ISSUE TITLE
Is it possible to group validators into new validators.

### ISSUE THREAD

**Issue by utkant** [Respect/Validation#930]
Hello...

I was just working on some validation and I was thinking if it would be possible to do the following.

Is there any way to turn for example this:
```
->key('city', v::noWhiteSpace()->notEmpty())
->key('id', v::num())
->key('line1', v::noWhiteSpace()->notEmpty())
->key('line2', v::noWhiteSpace()->notEmpty())
->key('zip', v::noWhiteSpace()->notEmpty()),
```

into 
`->address()`

It would make it easier to reuse than copy pasting and maintaining the first option...

**Comment by utkant** [comment]
I know you can make your own validator rules, but how can you reuse the existing ones in the validator rules? The documentation is not very clear on this since all examples require that you actually write the whole validation in the custom rule. I would like a way to group these validations into a custom validation.

**Comment by williamespindola** [comment]
Is your address is a string or an array? The possibilities that I remember is [Reuse a validator](https://github.com/Respect/Validation/blob/22f1f14430155c21c1d6ba271a652f28c5057851/docs/README.md#validator-reuse) or group the validator with [OneOf](https://github.com/Respect/Validation/blob/1.1/docs/OneOf.md) or [AllOf](https://github.com/Respect/Validation/blob/1.1/docs/AllOf.md)

Have a look:
```php
use Respect\Validation\Rules;

$usernameValidator = new Rules\AllOf(
    new Rules\Alnum(),
    new Rules\NoWhitespace(),
    new Rules\Length(1, 15)
);
$usernameValidator->validate('alganet'); //true
```

**Comment by utkant** [comment]
That is good if I wanted to put a lot of different validators into my code. But I wanted to make a Rule which consists of several other rules... I saw that there was some example of that in the Domain Rule but I was wondering if there was any other better and faster way of doing it. 

Something like: 

`namespace App\Validation\Rules;

use Respect\Validation\Rules\AbstractRule;
use Respect\Validation\Validator as v;

class Address extends AbstractRule {
    public function validate($input) {
        return v::noWhiteSpace()->notEmpty()->validate($input->city) &&
                v::noWhiteSpace()->notEmpty()->validate($input->countryId) &&
                v::noWhiteSpace()->notEmpty()->validate($input->countyId) &&
                v::noWhiteSpace()->notEmpty()->validate($input->id) &&
                v::noWhiteSpace()->notEmpty()->validate($input->line1) &&
                v::noWhiteSpace()->notEmpty()->validate($input->line2) &&
                v::noWhiteSpace()->notEmpty()->validate($input->stateId) &&
                v::noWhiteSpace()->notEmpty()->validate($input->zip);
    }
}`

I know this does not work but you see what I was thinking...

**Comment by williamespindola** [comment]
You can do something like this:

```php
use Respect\Validation\Rules;

class AddressValidator extends Rules\AllOf
{
    public function __construct()
    {
        return $this->addRules([
            new Rules\ Attribute('city',        new Rules\ NoWhitespace),
            new Rules\ Attribute('city',        new Rules\NotEmpty),
            new Rules\ Attribute('countryId',        new Rules\NoWhitespace),
            new Rules\ Attribute('countryId',        new Rules\NotEmpty),
            new Rules\ Attribute('line1',        new Rules\NoWhitespace),
            new Rules\ Attribute('line1',        new Rules\NotEmpty),
            // TODO other attributes
        ]);
    }
}
```
Executing
```php
class Address
{
    public $city;
    public $countryId;
    public $line1;
}
$addressValidator = new AddressValidator;

call_user_func($address, new Address);
```
See [Attribute](https://github.com/Respect/Validation/blob/1.1/docs/Attribute.md)

**Comment by utkant** [comment]
That would still leave me with a AddressValidator and not an Address Rule... :)

**Comment by utkant** [comment]
The good thing about adding an address rule is that if I need to change something I can do it in one place. If I were to make address validators throughout the system it would mean changing several places. An alternative would be to make a central address validator which can be reused, but then that would mean that I would end up with lots of validators instead of just one. I think I will study the domain rule and use that as a template for making my own address rule...

**Comment by henriquemoody** [comment]
The Domain rule is not really a good example of how to use rules to create new rules. Also it's important to say that "rule" and "validator" are pretty much the same thing.

What I would recommend you do to is to create your own rule:

```php
namespace My\Validation\Rules;

use Respect\Validation\Rules\AbstractWrapper;
use Respect\Validation\Validator as v;

final class Address extends AbstractWrapper
{
      public function __construct()
      {
            $this->validatable = v::create()
                  ->attribute('city', v::noWhiteSpace()->notEmpty())
                  ->attribute('countryId', v::noWhiteSpace()->notEmpty())
                  ->attribute('countyId', v::noWhiteSpace()->notEmpty())
                  ->attribute('id', v::noWhiteSpace()->notEmpty())
                  ->attribute('line1', v::noWhiteSpace()->notEmpty())
                  ->attribute('line2', v::noWhiteSpace()->notEmpty())
                  ->attribute('stateId', v::noWhiteSpace()->notEmpty())
                  ->attribute('zip', v::noWhiteSpace()->notEmpty());
      }
}
```

Then register your custom namespace:

```php
v::with('My\\Validation\\Rules\\');
```

And then just use it:
```php
v::address()->assert($addressObject);
```

**Comment by utkant** [comment]
Aha, that is a good way of doing it. I will follow that pattern for my rules. It is what I was looking for...
