### ISSUE TITLE
[QUESTION] How suppress error messages for some validation?

### ISSUE THREAD

**Issue by petronetto** [Respect/Validation#945]
I'm trying use for validating an User creation, but, when if a compare `password` with `password_confirmation`, I got the password typed: `password_confirmation must be equals "secret"`

Here's my code:
```
$validation = v::key('password', v::alnum()->length(6, 36))
    ->keyValue('password_confirmation', 'equals', 'password');
```

Thanks!

**Comment by henriquemoody** [comment]
It's been a long time since there is no response on this one. I'm gonna close this one but feel free to send a new one if needed! 

I hope you found a resolve for your problem anyways! 🐼

**Comment by henriquemoody** [comment]
And thanks @infodusha for the proposed solution!
