### ISSUE TITLE
Array validation

### ISSUE THREAD

**Issue by akorz** [Respect/Validation#955]
Hello, I have DTO object

```
class CreateCountryCommandDTO extends DTO
{
	/**
	 * @var string
	 */
	public $name;

	/**
	 * @return array
	 */
	public function rules(): array
	{
		v::with('App\\Domain\\Country\\Validator\\CountryName');

		return [
			'name' => v::CountryName($this->container)->setName('name'),
		];
	}
}
```

Where CountryName is my validator 

```
class CountryName extends AllOf
{
    /**
     * CountryName constructor.
     * @param ContainerInterface $container
     * @param string|null $id
     * @throws \Respect\Validation\Exceptions\ComponentException
     */
	public function __construct(ContainerInterface $container, string $id = null)
	{
		parent::__construct(
			new StringType(),
			new NotEmpty(),
			new Alpha(),
			new Length(1, 100),
			new CountryNameUnique($container, $id)
		);
	}
}
```

When the $name is just a string it's ok. But how to validate $name if it looks like?

```
Array
(
    [en] => English Name
    [es] => Spanish Name
    [ru] => Russian Name
)
```

**Comment by nickl-** [comment]
You will want to use the `attribute` (for object attributes) or `key` (for array keys) validators.

There are some examples in the [feature guide](https://github.com/Respect/Validation/blob/1.1/docs/README.md#validating-object-attributes) and the documentation for [attribute](https://github.com/Respect/Validation/blob/1.1/docs/Attribute.md) and [key](https://github.com/Respect/Validation/blob/1.1/docs/Key.md) respectively... you could also have a look see at [keyset](https://github.com/Respect/Validation/blob/1.1/docs/KeySet.md) which is a helper to the `key` validator.

Good luck!
