### ISSUE TITLE
SPF validation

### ISSUE THREAD

**Issue by daddyy** [Respect/Validation#960]
Hi what about this to fork?

    public static function emailSpf($email, $domain) {
            $result = false;
            $tempDomain = \WrShop\Core\Util::getDomainName($domain);
            $shellRes = shell_exec("nslookup -q=TXT " . $tempDomain . " 2>&1");
            $tempEmail = explode('@', $email);
            if (stripos($shellRes, end($tempEmail)) !== false) {
                $result = true;
            }
            return $result;
    }

**Comment by henriquemoody** [comment]
I wouldn't like to have validations that depend on external resources, but I encourage you to create a custom validator for your application if that's needed!

If you have any questions let me know.

🐼

**Comment by daddyy** [comment]
Hi sorry, i am sorry for late reponse.
the method can be rewritten ofcourse :-)
then U will use only shell_exec

`
/**
 @param $email string for check, for Respect can by use his validation for email
 @example example@domain.tld
 @param $domainName domain for which is check the email os has SPF, for Respect can by use his 
validation for domainName
 @example domain.tld mail.domain.tld
 @return boolean
 @todo please change the shell_exec with dns_get_record
**/
public static function emailSpf(string $email,string $domainName):bool {
        $result = false;
        $shellRes = shell_exec("nslookup -q=TXT " . $domainName . " 2>&1");
        $tempEmail = explode('@', $email);
        if (stripos($shellRes, end($tempEmail)) !== false) {
            $result = true;
        }
        return $result;
}
`
