### ISSUE TITLE
TLD domains update

### ISSUE THREAD

**Issue by r--w** [Respect/Validation#994]
Please update all new TLD domains as listed in http://data.iana.org/TLD/tlds-alpha-by-domain.txt
currently we are missing many of them

**Comment by gpredl** [comment]
TLD check is useless without current list.
As mentioned in https://github.com/Respect/Validation/issues/824 there is a Public Suffix list available.

**Comment by gpredl** [comment]
Added Pull request for optional usage of LayerShifter\TLDDatabase
https://github.com/Respect/Validation/pull/1071

**Comment by henriquemoody** [comment]
This is already available
